
# (PART\*) Tema I: Introducción a los estudios médicos y la estadística  {-}


# Introducción

La situación siguiente os va a ser familiar con la que está cayendo este 2020. Suponed que se ha realizado un ensayo clínico sobre una muestra de individuos para determinar

* si una nueva vacuna es efectiva para prevenir una enfermedad;
* o si una nueva terapia es más efectiva, o tiene menos efectos secundarios adversos, que las terapias anteriores
* o si una nueva técnica diagnóstica para una determinada enfermedad es más precisa que las anteriores, o igual de precisa pero más barata o máas rápida o menos intrusiva.

El última instancia, la información obtenida en este estudio se ha recogido sobre un conjunto más o menos pequeño de individuos, y queremos saber hasta dónde se puede generalizar al total de la población mundial, o al menos a la población de nuestro entorno.  La estadística es la que nos permite esta generalización.

Se ha definido estadística de muchas maneras. La que más nos gusta, y que entronca con la situación que acabamos de explicar, es que la **estadística** es la ciencia que permite adquirir conocimiento generalizable a partir de datos. Una definición en la que apenas sobran palabras:

* Hemos obtenido unos **datos** sobre un grupo de individuos.
* A partir de estos datos, queremos **generalizar** el **conocimiento** que hemos obtenido sobre estos individuos al total de la población de la que los hemos escogido.
* Y no se trata de trucos de magia adivinatoria, sino de una ciencia cuya metodología ha sido validada por medio de demostraciones matemáticas o, en el peor de los casos, mediante experimentos con números. No se trata de adivinac

Como decimos, la situación de partida a la hora de aplicar técnicas estadísticas es que disponemos de un conjunto de datos que describen algunos aspectos de un grupo de individuos elegidos de una población. El análisis estadístico de estos datos puede ser entonces de dos tipos básicos:

*  **Análisis descriptivo**, cuando nuestro objetivo sea resumir, representar y explicar los datos concretos de los que disponemos. La **estadística descriptiva**  es el conjunto de técnicas que se usan con este fin. 

* **Análisis inferencial**, si nuestro objetivo es deducir  (**inferir**),  a partir de estos datos, información significativa sobre el total de la población de interés.  Las técnicas que se usan en este caso forman la **estadística inferencial**.

Ambos tipos de análisis están relacionados. Por un lado, porque es conveniente (obligatorio, en nuestra opinión) empezar cualquier análisis inferencial dando un vistazo a los datos que se usarán. Por otro, porque muchas técnicas descriptivas permiten estimar propiedades de la población de la que se ha extraído la muestra. Por citar un ejemplo, la media aritmética de las alturas de una muestra de individuos nos da un valor  más o menos representativo de esta muestra, pero también se puede usar para *estimar*  la altura media de los individuos de la población total.

La estadística inferencial entra en juego cuando se quiere obtener información sobre una población y no se tiene acceso a todos los individuos de la misma. Si por ejemplo quiero conocer la altura media  de los estudiantes matriculados en una asignatura concreta de la UIB en un curso concreto, en principio no necesito para nada la estadística inferencial. Son pocos, los mido a todos y calculo la media (en todo caso, este sería el dominio de la estadística descriptiva).  Si en cambio quiero conocer la altura media de los residentes en les Illes Balears de 18 años, seguramente me será muy difícil acceder a todos ellos. Entonces, tomaré una muestra de ellos, los mediré y a partir de estas medidas estimaré el valor que me interesa. Naturalmente, el resultado solo será aproximado, con un cierto margen de error y una cierta probabilidad de que la media real sea muy diferente de la que he estimado.

**Aquí falta una transición.**

La **Medicina Basada en la Evidencia** (**MBE**) consiste  en "la utilización consciente, explícita y juiciosa de la mejor evidencia científica disponible para tomar decisiones sobre el cuidado de los pacientes individuales" (D. Sackett *et al*, ["Evidence based medicine: what it is and what it isn't"](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2349778/pdf/bmj00524-0009.pdf) *British Medical Journal* 312 (1996), pp. 71-72). La metodología que se aplica en la MBE se basa en cuatro pasos:

1.  Formular de manera precisa una pregunta a partir del problema clínico del paciente.

1. Localizar referencias sobre su respuesta en la literatura médica.

1. Evaluar de forma crítica la evidencia encontrada dichas referencias.

1. Aplicación las conclusiones de dicha evaluación a la práctica.

En este curso nos vamos a centrar en el tercer paso.  Para evaluar la fuerza de la evidencia obtenida  en un estudio médico, necesitamos ser capaces de determinar si el estudio se ha llevado a cabo correctamente, si el análisis de los datos se ha realizado de manera correcta, si las conclusiones a las que se llega están bien fundamentadas y hasta qué punto son válidas en el caso clínico concreto que nos ocupa. Si las conclusiones del estudio se han obtenido mediante técnicas de estadística (ya sabéis, para generalizar lo observado sobre los sujetos de la muestra usada a toda una población), está claro que para evaluar su validez son necesarios unos mínimos conocimientos de estadística y diseño de investigación.






