
# Algunos conceptos básicos en estadística {#chap:conceptos}

## Unidad de observación

En un estudio estadístico, la **unidad de observación** es, para entendernos, el tipo de qué o de quiénes que van a ser objeto de medición durante la investigación. En los estudios médicos normalmente serán personas, pero no siempre:

* Pueden ser sucesos que les pasen a personas, de manera que una misma persona pueda ser observada varias veces: por ejemplo, embarazos,  operaciones quirúrgicas, o el efecto de administrar, en momentos diferentes, diferentes tratamientos para una misma enfermedad crónica a un enfermo.

* Pueden ser partes de personas. Por ejemplo, si queremos estudiar si el uso de teléfono móvil aumenta el riesgo de cáncer de piel en las orejas, en los participantes del estudio compararemos la oreja dominante en este sentido con la otra, de manera que la unidad de observación son las orejas de las personas, no las personas.

* Recordad que en los estudios ecológicos (Sección \@ref(sec:ecol)) la unidad de información son las comunidades de las que se mide algún dato global. Por ejemplo, podemos medir en diferentes centros de educación primaria de una ciudad el gasto medio diario en sus máquinas expendedoras de alimentos procesados y el índice de masa muscular medio de sus alumnos, para estimar si hay alguna relación entre estas dos cantidades. Aquí, la unidad de observación son los centros de educación primaria, no los alumnos.


## Población y muestra

En un estudio inferencial, queremos deducir (**inferir**) información sobre una **población** a partir de una **muestra** de la misma. 

En general, una **población** es simplemente un conjunto de individuos u objetos sobre los que queremos conocer alguna información. Esta población puede estar perfectamente definida en un lugar y tiempo: por ejemplo, los habitantes de España a día de hoy. Pero normalmente su definición será difusa. Si, por ejemplo, queremos estimar algo sobre "los españoles mayores de 65 años", ¿de quién estamos hablando exactamente? ¿De los que están vivos justo ahora? ¿De todos los que han habitado España desde que esta se fundó? ¿Incluimos los que aún no han nacido y que cuando nazcan lleguen a cumplir 65 años?

Tranquilos, no nos vamos a romper mucho la cabeza con esto. Pero al menos tenéis que ser conscientes de que una población puede contener objetos que en realidad no existen ni hayan existido ni vayan a existir, sino simplemente que "podrían existir". Y en medicina especialmente, cuando queremos estimar si un tratamiento será efectivo para tratar una cierta enfermedad... incluyendo los casos que aún no han contraído la enfermedad. Hablaremos entonces de una población **virtual** (en otros sitios la encontraréis descrita como población **metafórica**).

Por ejemplo, cuando decimos que 

> "La probabilidad de que salga Cara al lanzar una moneda equilibrada al aire  es 1/2", 

lo que significa es que 

> "Si tomamos la población formada por todos los posibles lanzamientos de todas las posibles monedas equilibradas, en la mitad de sus miembros el resultado es Cara."

Los miembros de esta población son todos los "posibles" lanzamientos de monedas equilibradas, los que se han realizado a lo largo de la historia, los que se realizarán en el futuro, y los que se podrían haber realizado o se podrían realizar en el futuro pero en realidad no se han hecho ni se harán nunca.


Otro ejemplo. Imaginad que comparamos las notas que (vosotros, estudiantes de primer curso del grado de Medicina de la UIB de este año académico) sacáis en dos cuestionarios diferentes sobre un mismo tema, digamos que uno sobre conceptos y el otro de cálculos, y que en el primero obtenéis una nota media mayor que en el segundo. Inferimos que un estudiante de primer curso de Medicina saca de media mejor nota en tests de conceptos que en tests aritméticos. ¿Quién es este "estudiante de primer curso de Medicina"?  ¿Sobre qué población "inferimos" información a partir de este resultado? 

No sobre solo vosotros y para estos dos tests concretos, ya que entonces no estamos infiriendo nada, simplemente calificamos, constatamos que una nota media ha sido más alta que la otra, y paramos aquí. 


La población a la que querríamos generalizar los resultados podría ser  la de "todos los posibles estudiantes como vosotros que estuvieran cursando una asignatura como esta y se les pusieran tests similares a los de nuestro experimento", que como veis ni está del todo bien definida ni ciertamente está formada exclusivamente por "individuos" que existan, o que hayan existido o que necesariamente vayan a existir. Naturalmente, esta población virtual la resumiremos en "los estudiantes de primer curso de Medicina".

Hasta ahora hemos hablado de la población, a menudo virtual, sobre la que queremos obtener información. Está será nuestra **población objetivo**, que hay que distinguir de la **muestra**:

* **Población objetivo**: un conjunto de sujetos con una o varias características sobre las que deseamos obtener información.

* **Muestra**:  el grupo de los sujetos concretos en los que medimos las características de interés.

```{example}
Vosotros sois una muestra de muchas poblaciones:
  
* "Los estudiantes de primer curso de Medicina en España"
* "Los estudiantes de la UIB de este curso"
* "Los jóvenes europeos"
* "Los mamíferos bípedos"
* ...


```

```{example}
Una serie de 10 lanzamientos de una moneda equilibrada concreta es una muestra de la población de "los posibles lanzamientos de monedas equilibradas".


```

A la hora de determinar la validez de un estudio, es muy importante comparar la población objetivo con la:

* **Población muestreada**: el conjunto de sujetos (**unidades de observación**, en el sentido de la sección anterior) del que se extrae la muestra. 

Usualmente, la población muestreada será un subconjunto de la población objetivo definido por una serie de restricciones, pero puede no serlo: pensad, por ejemplo, en los estudios ecológicos, donde la población objetivo son individuos y la población muestreada son grupos de individuos.

```{example,tuberculosisrusia}
Dad un vistazo al artículo ["Risk factors for pulmonary tuberculosis in Russia: case-control study"](https://www.bmj.com/content/332/7533/85.short)
(R. Coker *et al*, *British Medical Journal*  332 (2006), pp. 85-87). Su objetivo es "Determinar los factores de riesgo para la tuberculosis pulmonar en Rusia". Por lo tanto:

```

* La **población objetivo** es toda la población de Rusia.

Ahora bien, la muestra se tomó solo entre los adultos de la ciudad de [Samara](https://es.wikipedia.org/wiki/Samara) y durante 2003. Por lo tanto:

* La **población muestreada** fueron los adultos que vivían en la ciudad de Samara en 2003.

Finalmente, leemos que los casos fueron todos los adultos diagnosticados de tuberculosis pulmonar de la población muestreada a los que se administró un  DOTS (Tratamiento Acortado Directamente Observado), en total 334. Como controles se tomó al azar el mismo número de personas entre la población adulta sin historial de tuberculosis  de la ciudad.

* La **muestra** fueron estas 668 personas.


```{example, Hola}
Para conocer la opinión de sus lectores sobre la familia real española, una conocida revista del corazón propuso una encuesta en línea en su web y analizó las respuestas. En este **estudio transversal**:

````

* La **población objetivo** es la formada por "los lectores de esta revista".
* La **población muestreada** es la formada por los lectores actuales de esta revista con acceso a Internet. 
* La **muestra** son los miles de personas concretas que voluntariamente respondieron la encuesta.

En el Ejemplo \@ref(exm:tuberculosisrusia), puede que la población muestreada no fuera representativa de **toda** Rusia. Los habitantes de una de las ciudades más pobladas de Rusia, a unos 1500 km al sudeste de Moscú, ¿tienen las mismas características que los habitantes de una aldea perdida en mitad de la nada siberiana? Pues no lo sabemos, pero creemos que no. Además, la muestra de casos tampoco representa en colectivo de tuberculosos de Samaran, puesto que solo se tomaron aquellos que reunían las condiciones para un tratamiento concreto (los tuberculosos con frotis bucal negativo a veces no se incluyen en un programa DOTS).

En el Ejemplo \@ref(exm:Hola) está más claro que la población muestreada no es representativa de la población objetivo: seguramente excluye, por ejemplo, los lectores ancianos o los de zonas rurales con acceso difícil a Internet. Por otro lado, la muestra es aún más restrictiva, ya que los participantes fueron voluntarios, y sus características pueden ser diferentes de las de los lectores que prefirieron no opinar sobre este tema (por si el CNI vigila estas cosas...)  o de las de los lectores que nunca responden encuestas.


Si la población muestreada no es representativa de la población objetivo, los resultados del estudio no tienen por qué ser generalizables a esta última: diremos entonces  que se ha dado un **sesgo de falta de  representatividad**. Hablaremos sobre sesgos en la Sección \@ref(sec:sesgos).

```{example}
Al escogeros a vosotros como una muestra de la población de estudiantes de primer curso de Medicina, podríamos entender como población muestreada, por ejemplo, la de  "los estudiantes que en el año académico 2020/21 cursan primer curso de Medicina en una universidad española". Seguramente esta población muestreada tiene características muy diferentes de las de los estudiantes que hace 40 años cursaron primer curso de Medicina en una universidad española, o de las de los estudiantes que este año académico cursan primer curso de Medicina en una universidad estadounidense.

```

```{block2,type="rmdexercici"}
Si lanzo 10 veces una moneda equilibrada de 1 euro concreta, ya hemos quedado que la población objetivo está formada por todos "los posibles lanzamientos de monedas equilibradas". ¿Cuál sería la población muestreada? ¿Es representativa de la población objetivo?
  
```



```{block2,type="rmdimportant"}
Un estudio médico toma información sobre una muestra de individuos y la generaliza a una población objetivo. Si nos ha interesado leerlo, seguramente será porque su población objetivo contiene, o al menos está relacionada con, la población que nos interesa a nosotros. Pero la muestra habrá sido tomada de una población muestreada que no tiene por qué coincidir con nuestra población de interés.  Es muy importante poder decidir entonces si las conclusiones a las que se llega en el estudio se pueden aplicar o no a nuestra población. 

```

No es el objetivo de este curso el que podáis tomar esta decisión, no va de estadística sino de la experiencia médica que aún os falta. Pero sí que al menos seáis conscientes de que un resultado  estimado para una población puede no ser extrapolable a otra población.


```{example}
En el estudio ["D-dimer as a biomarker for disease severity and mortality in COVID-19 patients: a case control study"](https://link.springer.com/article/10.1186/s40560-020-00466-z)(Y. Yao *et al*, *Journal of Intensive Care*  8:49 (2020)) se compararon diversas características clínicas, analíticas y radiológicas entre los pacientes que fallecieron (17 en total) y los que no fallecieron (231) en un grupo de pacientes de COVID-19 tratados en el hospital Renmin de la Universidad de Wuhan. Su objetivo era determinar qué características entre las estudiadas aumentaban el riesgo de fallecimiento entre los enfermos de COVID-19. 

Se encontró una asociación estadísticamente significativa entre  tener un nivel de dímero D en sangre muy alto, superior a 2 mg/l, y un aumento en el riesgo de [*exitus*](https://es.wikipedia.org/wiki/Exitus). Querríamos decidir si esta asociación también es válida para nuestros pacientes.


```

¿Cuál es el problema? Pues que la población objetivo  del estudio es la de todos los enfermos de COVID-19, pero según el artículo la población muestreada fue la de "pacientes con al menos dos síntomas de COVID-19 y PCR positiva tratados en ese hospital concreto de Wuhan". Así que de entrada, los pacientes con un solo síntoma quedan excluidos. Además, habría que valorar si la población asignada a ese hospital se parece o no a la balear. Por ejemplo, la tasa de letalidad de la COVID-19 entre el grupo de pacientes examinados fue del 6.85%, mientras que en las Baleares es de alrededor del 2.4%, aunque este  dato refiere al total de infectados, incluyendo los asintomáticos. También habría que valorar si la asociación observada se debe a algún confundidor. Por ejemplo, la edad media de los sujetos de la muestra con niveles elevados de dímero D era significativamente más alta que la de los que tenían un nivel normal, y la COVID-19 es más letal entre los ancianos. ¿Será la edad un factor de confusión en este estudio?   

```{block2,type="rmdexercici"}
En el artículo ["Tuberculosis treatment survival of HIV positive TB patients on directly observed treatment short-course in Southern Ethiopia: A retrospective cohort study"](https://bmcresnotes.biomedcentral.com/articles/10.1186/1756-0500-5-682) (D. Shaweno, **BMC Research Notes** 5:682 (2012)) se quiso estudiar si  la infección por VIH afecta la supervivencia a corto plazo de pacientes con tuberculosis (TB). Para ello, se consideraron todos los pacientes que habían participado en un estudio previo: se trataba de pacientes diagnosticados de TB durante el periodo 2006-2010 a los que se prescribió un tratamiento concreto de quimioterapia de 8 meses de duración y que además pasaron un test de VIH en el momento del diagnóstico positivo de TB. De este grupo de pacientes,  se escogieron al azar un subgrupo de 370 VIH-positivos y otro de 370 VIH-negativos, y se anotó el número de pacientes de cada uno de estos dos subgrupos que murieron durante el curso del tratamiento de 8 meses. La conclusión fue que la tasa de mortalidad entre los paciente de TB VIH-positivos es mayor que entre los que son VIH-negativos.


*(a)* ¿Cuáles son la población objetivo, la población muestreada y la muestra? 

*(b)* ¿Creéis que la población muestreada es representativa de la población objetivo?

```