

## Sesgos {#sec:sesgos}

Un **sesgo** es cualquier tipo de error sistemático en el diseño o la ejecución de un estudio que pueda afectar la corrección de las conclusiones obtenidas. Por ejemplo, si en un estudio transversal sobre hipertensión usamos un esfigmomanómetro que sistemáticamente mide una presión arterial más alta que la real, se produce un sesgo: se detectará una prevalencia mayor de hipertensos que la real. Los errores que pueden dar lugar a sesgos no se han de confundir con el error aleatorio inherente a las mediciones (por ejemplo, los debidos a la medición imprecisa del esfigmomanómetro, que solo llega hasta una cierta precisión, o a la variación natural  de la presión arterial en un individuo a lo largo del día).

Muchos autores han producido listas larguísimas de tipos de sesgos que muestran la creatividad de los humanos a la hora de cometer errores y de ponerles nombres a los mismos. Aquí solo vamos a introducir algunos de los más comunes.

1. **Sesgo de selección**: Cuando la muestra no es representativa de la población objetivo. Por poner un ejemplo exagerado, si queremos saber la incidencia del cáncer de pecho en una comunidad y para ello tomamos una muestra de solo hombres. Hay varios subtipos que vale la pena distinguir:

     a. **Sesgo de selección diferencial**: Cuando el sesgo de selección se da de manera diferente en los diferentes grupos de sujetos considerados. Por ejemplo: nos preguntamos sobre la influencia de algunos factores de riesgo en la diabetes, y tomamos como casos diabéticos hospitalizados y como controles personas sanas que no están hospitalizadas (a este tipo de sesgo en concreto, tomar como casos solo casos hospitalizados, se le llama **sesgo de Berkson**). 

     b. **Sesgo de falta de representatividad**: Cuando la muestra no es representativa debido a un defecto en su obtención: por ejemplo, voluntarios  que rellenan una encuesta.

     c. **Sesgo de supervivencia**: Considerar los pacientes vivos como representativos de los enfermos de una enfermedad con una alta tasa de mortalidad.


2. **Sesgo de clasificación** (o **de medida**, **de información**): Cuando el método de medición de características de los sujetos (o de su clasificación) es defectuoso. Incluye, por ejemplo:

     a. **Sesgo de recuerdo**: En estudios de casos y controles en los que recojamos la información sobre exposición por medio de encuestas, los casos tiene mayor tendencia a recordar su exposición a circunstancias que ellos asocien a la enfermedad que los controles. Aquí también podríamos incluir la posibilidad que un encuestado haya olvidado información, o simplemente que mienta.

     b. **Sesgo de procedimiento**: Cuando el clínico analiza de manera diferente un grupo que otro; por ejemplo, en un ensayo clínico llevar a cabo un mayor seguimiento de los que toman el nuevo tratamiento comparado con los que toman el anterior.

     c. **Sesgo de detección**: Cuando se usan varias metodologías con diferente sensibilidad para detectar una enfermedad o una exposición. Por ejemplo; si para saberlos sujetos si han tomado un medicamento, a algunos pacientes se les pasa una encuesta y a otros se consulta su historial clínico.

     d. **Sesgo de atención**: Cuando los participantes en un estudio alteran su comportamiento porque se saben observados. Por ejemplo: en un estudio sobre el efecto del ejercicio físico en la salud, puede que los sujetos del grupo ``ejercicio físico'' decidan tomar otros nuevos hábitos saludables.

     e. **Sesgo del entrevistador**: Cuando el entrevistador influye en las respuestas de los entrevistados.

     f. **Sesgo de error instrumental**: Cuando los instrumentos usados para medir alguna característica son defectuosos. Por ejemplo: el esfigmomanómetro del primer párrafo.

3. **Sesgo de confusión**:  Cuando el efecto de la exposición a un riesgo objeto de estudio se confunde con el de la exposición a otro factor de riesgo (el **factor de confusión**) que no se tiene en cuenta pero que influye en el resultado (y, por ejemplo, va y es el verdadero causante de la enfermedad que estamos estudiando). Por ejemplo: en un estudio de casos y controles se detectó una asociación entre tomar café y sufrir cáncer de páncreas, pero en realidad lo que pasó es que muchos consumidores de café fumaban  (un 89%, frente a un 35% de los no consumidores de café) y era el fumar el que realmente estaba asociado al cáncer de páncreas.






