

## Sesgos {#sec:sesgos}

Un **sesgo** es cualquier tipo de error sistemático en el diseño o la ejecución de un estudio que desplace en algún sentido los datos recogidos (en el total de la muestra o en un subgrupo de la misma), es decir, que los **sesgue**,  y pueda afectar la corrección de las conclusiones obtenidas. Por ejemplo, si en un estudio transversal sobre hipertensión usamos un esfigmomanómetro que sistemáticamente mide una presión arterial más alta que la real, se produce un sesgo: se detectará una prevalencia mayor de hipertensos que la real. 

Los errores que pueden dar lugar a sesgos no se han de confundir con el error aleatorio inherente a las mediciones (por ejemplo, los debidos a la medición imprecisa del esfigmomanómetro, que solo mide la tensión hasta una cierta precisión, o a la variación natural de la presión arterial en un individuo a lo largo del día). La estadística nos proporciona herramientas para tratar el error aleatorio, pero las fuentes de sesgo se han de eliminar al diseñar el estudio o   detectarlas al leer un estudio para valorar la validez de sus conclusiones.

Muchos autores han producido [listas larguísimas de tipos de sesgos](https://catalogofbias.org/biases/) que muestran la creatividad de los humanos a la hora de fastidiarla y de poner  nombres a las diferentes maneras de fastidiarla. Aquí solo vamos a introducir algunos de los más comunes.

1. **Sesgo de selección**: Se produce cuando la muestra no es representativa de la población objetivo. Por poner un ejemplo exagerado, sería el caso si quisiéramos saber la incidencia del cáncer de pecho en una comunidad y para ello tomáramos una muestra de solo hombres. 

    Hay varios subtipos que vale la pena distinguir:
    
     a. **Sesgo de falta de representatividad**: Cuando la muestra no es representativa debido a un defecto en su obtención.
     
         Por ejemplo, una muestra formada por voluntarios que rellenen una encuesta o que se ofrezcan para que les hagan unas pruebas dolorosas a cambio de una compensación económica.
         
         Por poner un ejemplo importante en medicina, si nos preguntamos sobre la influencia de algunos factores de riesgo en la diabetes, y tomamos tanto los casos como los controles entre pacientes hospitalizados (a este tipo de sesgo en concreto, tomar como casos y controles solo casos hospitalizados, se le llama [**sesgo de Berkson**](https://academic.oup.com/ije/article/43/2/511/680126)).  Los pacientes hospitalizados tendrán unas patologías más severas que la población en general, y puede que su exposición a factores de riesgo no sea  representativa de la de la población en general.

     b. **Sesgo de selección diferencial**: Cuando el sesgo de selección se da de manera diferente en los diferentes grupos de sujetos considerados. 
     
           Siguiendo con el ejemplo de la influencia de algunos factores de riesgo en la diabetes, se daría si tomáramos  los casos entre pacientes hospitalizados y los controles entre pacientes sanos, no hospitalizados. 


     c. **Sesgo de supervivencia**: Cuando se toma una muestra de pacientes vivos de una enfermedad con una alta tasa de mortalidad. En este caso, es muy probable que la muestra incluya más enfermos que hayan sobrevivido más de lo esperado a la enfermedad, y estos no tienen por qué ser representativos de la población general de enfermos de esta enfermedad.


2. **Sesgo de de medida**: Se produce cuando el método de medición de características de los sujetos es defectuoso en una dirección concreta. Incluye, por ejemplo:

     a. **Sesgo de memoria**: En estudios en los que recojamos la información sobre exposición por medio de entrevistas o encuestas, existe la posibilidad de que algunos encuestados hayan olvidado información, o simplemente de que mientan en temas delicados. 

     a. **Sesgo de memoria diferencial**: Es un caso particular del anterior. En estudios de casos y controles en los que recojamos la información sobre exposición por medio de encuestas, los casos tienen mayor tendencia a recordar su exposición a circunstancias que ellos asocien a la enfermedad que los controles. 


     c. **Sesgo de procedimiento**: Cuando el clínico analiza de manera diferente un grupo que otro.
     
         Se daría, por ejemplo, en un ensayo clínico si se llevara a cabo un seguimiento  más frecuente a los que toman un nuevo tratamiento que a los controles.

     d. **Sesgo de detección**: Cuando se usan varias metodologías con diferente sensibilidad para detectar una enfermedad o una exposición. 
     
         Se daría, por ejemplo, si para saber si los sujetos de una muestra han tomado un medicamento, a algunos se les pasa una encuesta y a otros se les consulta su historial clínico.

     d. **Sesgo de atención**: Cuando los participantes en un estudio alteran su comportamiento porque saben que participan en un estudio (a veces se le llama **efecto Hawthorne**). 
     
          Se podría dar, por ejemplo, en un estudio sobre el efecto del ejercicio físico en la salud si los sujetos del grupo de intervención (a los que se ha asignado el hacer ejercicio físico) deciden tomar otros nuevos hábitos saludables porque saben que se les ha asignado al grupo "saludable". 
          

    e. **Sesgo de error instrumental**: Cuando los instrumentos usados para medir alguna característica son defectuosos. 
    
        Sería el caso, por ejemplo, del esfigmomanómetro del primer párrafo.

3. **Sesgo de confusión**. Se da cuando el efecto de la exposición a un riesgo A  se confunde con el de la exposición a otro factor B (el **confundidor**) que está asociado a la exposición a A y que es el verdadero causante del desenlace  X que estamos estudiando.

    Hemos explicado varios ejemplos de confundidores al hablar de los problemas dre los estudios de casos y controles (Sección \@ref(sec:cyc)). Por ejemplo, la asociación entre que la madre sea fumadora y una disminución del riesgo que el hijo tenga síndrome de Down, debida en realidad al factor de confusión dado por la edad de las madres (Ejemplo \@ref(exm:fumarDownCC)). Por poner otro ejemplo, si en un estudio se observa una asociación entre una patología durante el embarazo y un defecto en los recién nacidos, podría ser que la causa del defecto no fuera la enfermedad de las madres sino el tratamiento que se les hubiera admninistrado relacionado con la misma.

Hay muchos otros tipos de sesgos. No es importante saber sus nombres, de hecho ni tan solo de los que hemos dado aquí. Lo importante es aplicar el sentido común al leer la Metodología de un estudio para entender qué elementos podrían haber desviado los datos recogidos y cómo estos sesgos afectan las conclusiones del estudio.

```{example,Hola2}
Volvamos al Ejemplo \@ref(exm:Hola), en el que explicábamos el caso de una conocida revista del corazón que, para conocer la opinión de sus lectores sobre la familia real española,  propuso una encuesta en línea en su web. ¿Qué sesgos se pudieron dar?
  
  
```

**(1.a)** ¿Sesgo de falta de representatividad? Sí, claro. Los voluntarios que rellenan encuestas en Internet no tienen por qué ser representativos del total de lectores de la revista.

**(1.b)** ¿Sesgo de selección diferencial? No, porque no se eligieron dos grupos.
 
**(1.c)** ¿Sesgo de supervivencia? No, se supone que les interesaba conocer la opinión de sus lectores vivos en ese momento, ¿no? 

**(2.a)** ¿Sesgo de memoria? Sí, claro, tenemos que tenerlo en cuenta siempre que se recoja información por medio de cuestionarios o entrevistas. Los participantes podrían  haber querido dar una mejor opinión de la familia real española que la que realmente tienen para quedar bien, o hacer quedar bien a la revista.

**(2.b)** ¿Sesgo de memoria diferencial? De nuevo, no, porque no se eligieron dos grupos.

**(2.c,d)** ¿Sesgo de procedimiento o de selección? No, por el mismo motivo
     
**(2.e)**  ¿Sesgo de atención? No, porque no se hizo un seguimiento a los participantes, por lo que si cambiaron su comportamiento, no afectó al resultado de la encuesta. 

**(2.f)** ¿Sesgo de error instrumental? Podría ser, si el cuestionario estuviera amañado en algún sentido. A lo mejor recordáis el famoso caso de la encuesta de satisfacción de Ryanair en 2017 en la que en la pregunta sobre el grado de satisfacción con el vuelo las únicas respuestas que se ofrecían eran "Excelente", "Muy buena", "Buena", "Aceptable" y "OK".

```{block2,type="rmdromans"}
No hace falta ser tan burdo a la hora de amañar un cuestionario. En una encuesta en el Reino Unido en el 2015, a la pregunta "¿Está usted de acuerdo en permitir a los jóvenes de 16 y 17 años votar en el referéndum del Bréxit?", un 52% respondió que sí y un 41% que no. Hasta ahí bien. Pero en la misma encuesta, bastantes preguntas después, se les pedía "¿Está usted de acuerdo en reducir la edad de voto de los 18 años a los 16 en el referéndum del Bréxit?", y a esa pregunta respondieron que sí el 37% y que no el 56%.
```

**(3)** ¿Sesgo de confusión? Dado que, por así decirlo, se trataba de un estudio transversal de prevalencia, sin intentar estimar relaciones de causa-efecto, no tiene sentido preguntarse por la existencia de confundidores.

Otra cosa sería si se hubiera pretendido estudiar qué características hacen que se opine mejor o peor sobre la familia real española. Entonces sí que podrían entrar en juego factores de confusión. Para no meternos en berenjenales, ahí lo dejamos.



## Ejercicios

### Problemas {-}


**(1)** En el estudio ["Tuberculosis treatment survival of HIV positive TB patients on directly observed treatment short-course in Southern Ethiopia: A retrospective cohort study"](https://bmcresnotes.biomedcentral.com/articles/10.1186/1756-0500-5-682) (D. Shaweno, **BMC Research Notes** 5:682 (2012)) se quiso estudiar si  la infección por VIH afecta la supervivencia a corto plazo de pacientes con tuberculosis (TB). Para ello, se consideraron todos los pacientes que habían participado en un estudio previo: se trataba de pacientes diagnosticados de TB durante el periodo 2006-2010 a los que se prescribió un tratamiento concreto de quimioterapia de 8 meses de duración y que además pasaron un test de VIH en el momento del diagnóstico positivo de TB. De este grupo de pacientes,  se escogieron al azar un subgrupo de 370 VIH-positivos y otro de 370 VIH-negativos, y se anotó el número de pacientes de cada uno de estos dos subgrupos que murieron durante el curso del tratamiento de 8 meses. La conclusión fue que la tasa de mortalidad entre los paciente de TB VIH-positivos es mayor que entre los que son VIH-negativos.


**(a)** ¿Cuáles son la población objetivo, la población muestreada y la muestra? 

**(b)** ¿Creéis que la población muestreada es representativa de la población objetivo?


**(2)** Tenemos una población clasificada en dos estratos, A y B. La subpoblación A representa un 20% de la población y la B el 80% restante. Hemos tomado una muestra aleatoria estratificada formada por 100 sujetos de cada subpoblación. Hemos medido una cierta característica  X de estos sujetos. La media de los valores de X de los sujetos A ha dado 5 y la media de los valores de X de los sujetos B ha dado 10.

**(a)** ¿Qué vale la media de los valores de X de toda la muestra de 200 sujetos?

**(b)** A partir de estos datos, ¿qué estimáis que vale la media de X en el total de la población?

**(3)** Deseamos llevar a cabo un estudio para determinar si la probabilidad que un diabético tipo 2  en las Baleares tiene una mayor probabilidad de infectarse de COVID-19 que una persona sin esa patología. Además, queremos poder comparar las probabilidades entre los diabéticos de Mallorca, de  Menorca y de Ibiza. Como parte del estudio, tendremos que tomar una muestra de diabéticos tipo 2 y realizarles un análisis de anticuerpos. Hemos calculado que para que las conclusiones sean fiable, necesitamos analizar 50 diabéticos de cada isla.

Explicad en detalle cómo obtendríais esta muestra de diabéticos; el procedimiento ha de ser fácil de llevar a cabo y ha de dar muestras razonablemente representativas de las poblaciones de diabéticos.

**(4)** En un [estudio llevado a cabo en Sidney en su verano de 1989-90](https://ajph.aphapublications.org/doi/abs/10.2105/AJPH.83.12.1701) (*American Journal of Public Health* 83 (1993), pp. 1701-1706)  se quiso  determinar la asociación entre nadar en playas contaminadas y sufrir enfermedades infecciosas agudas. Para ello se visitaron durante varios días de verano doce playas de los alrededores de Sidney y se invitó a participar en el estudio a varios individuos en cada ocasión. Se excluyeron individuos que hubieran nadado o que hubieran sufrido alguna enfermedad infecciosa en algún momento durante los 7 días anteriores. A los que aceptaron participar en el estudio, se les llamó por teléfono al día siguiente para pedir si habían nadado o no el día anterior y se les volvió a llamar al cabo de una semana para pedirles si habían sufrido alguna enfermedad infecciosa desde el día de playa. Si no contestaron a la primera llamada ya no se realizó la segunda llamada. En total se enroló 3989 sujetos, pero solo atendieron las dos llamadas 2968 de ellos. Por otro lado, se midió el nivel de contaminación del agua de las playas los días que se reclutaron bañistas en el estudio. El resultado fue un incremento del 33% del riesgo de sufrir una enfermedad  infecciosa  entre los que nadaron en aguas contaminadas respecto de los que nadaron en aguas no contaminadas, y de un 116% respecto de los que no nadaron.

*(a)* ¿De qué tipo de estudio creéis que se trata?  Justificad vuestra respuesta.

*(b)* ¿Qué sesgos se pudieron dar debido a la manera como se reclutaron los participantes o a la manera como se recogieron los datos? ¿Cómo se podrían haber evitado?




### Test {-}

**(1)** En una población se quiere determinar la prevalencia de pediculosis en niños menores de 12 años. Para ello se divide la población en barrios y en cada uno de ellos se toma una muestra aleatoria cuyo tamaño idóneo ha sido previamente determinado. El tipo de muestreo utilizado ha sido:	

1. Muestreo aleatorio simple.
1. Muestreo aleatorio estratificado.
1. Muestreo aleatorio por conglomerados.
1. Muestreo sistemático.


**(2)** Disponemos de las listas de todos los pacientes tratados por hipertensión en todos los centros de salud de una ciudad. Cada lista está ordenada por fecha de nacimiento. Para tomar una muestra de hipertensos, escogemos dos centros de salud al azar, y en cada uno de ellos cada décimo paciente en su lista de hipertensos. ¿Qué tipo de muestreo hemos usado?

1. Polietápico: por conglomerados tanto de los centros de salud como de los pacientes.

1. Sistemático.

1. Polietápico: por conglomerados de los centros de salud y sistemático de los pacientes.

1. Aleatorio simple.

1. Polietápico: estratificado de los centros de salud y sistemático de los pacientes.

1. Polietápico: estratificado de los centros de salud y aleatorio simple de los pacientes.



