# Estudios

## Tipos de estadística



Habitualmente, dispondremos de una serie de datos que describirán algunos
aspectos de un conjunto de individuos de una población, y querremos analizarlos. El análisis estadístico de estos datos puede ser de dos tipos básicos:

*  **Análisis descriptivo**, cuando nuestro objetivo sea resumir, representar y explicar los datos concretos de los que disponemos. La **estadística descriptiva**  es el conjunto de técnicas que se usan con este fin. 

* **Análisis inferencial**, si nuestro objetivo es deducir  (**inferir**),  a partir de estos datos, información significativa sobre el total de la población de interés.  Las técnicas que se usan en este caso forman la **estadística inferencial**.

Ambos tipos de análisis están relacionados. Por un lado, porque es conveniente (obligatorio, diría yo) empezar cualquier análisis inferencial dando un vistazo a los datos que se usarán. Por otro, porque muchas técnicas descriptivas permiten estimar propiedades de la población de la que se ha extraído la muestra. Por citar un ejemplo, la media aritmética de las alturas de una muestra de individuos nos da un valor  más o menos representativo de esta muestra, pero también se puede usar para *estimar*  la altura media de los individuos de la población total.


## Unidad de estudio


## Población




En todo estudio estadístico conviene tener claro quiénes son la población objetivo y la población muestreada, y distinguirlas de la muestra:

* **Población objetivo**: un conjunto de sujetos con una o varias características que podemos medir y deseamos estudiar

* **Población muestreada**: el subconjunto de la población, definido por algunas características extra, del que se extrae la muestra

* **Muestra**:  el grupo de los individuos concretos de la población a los que medimos las características de interés.




Por ejemplo, si quisiéramos estudiar alguna característica de los estudiantes de grado de la UIB, entenderíamos que estos forman la población de interés, y si entonces escogiéramos al azar 10 estudiantes de cada grado, obtendríamos una muestra de esta población. Pero también podríamos considerar los estudiantes de grado de la UIB como una muestra de la población de los estudiantes universitarios españoles: depende del estudio que queramos realizar.






