---
title: "Untitled"
output: html_document
date: "2023-09-10"
---



[fragile] 
\frametitle{Homoestacidad}

La otra condición que se tiene que cumplir es la homoestacidad, igualdad de varianzas.

La manera más popular de comprobarla (cuando aceptamos que las muestras provienen de distribuciones normales) es con el \red{test de Bartlett}, implementado en \texttt{R} en la función \red{\tt bartlett.test}

\begin{lstlisting}
> bartlett.test(N.E~Trat, data=Datos1)

	Bartlett test of homogeneity of variances

data:  N.E by Trat
Bartlett's K-squared = 2.1692, df = 2, 
   p-value = 0.338
\end{lstlisting}

Podemos aceptar que tienen varianzas iguales




\subsection{ANOVA de bloques}





\frametitle{Ejemplo 2}
Queremos comparar los efectos de dos analgésicos y un placebo en el tratamiento de la cefalea. El efecto lo cuantificamos mediante el tiempo (en min.) que tarda en desaparecer una cefalea con el tratamiento.


Hemos escogido 10 enfermos de cefalea y a cada uno le hemos aplicado los tres tratamientos en diferentes episodios de cefalea. 
El orden de los tratamientos ha sido aleatorio.






\frametitle{Ejemplo 2}
Si 

* $\mu_1$: Tiempo medio tomando placebo

* $\mu_2$: Tiempo medio tomando analgésico A

* $\mu_1$: Tiempo medio tomando analgésico B



queremos realizar el contraste:
$$
\left\{
\begin{array}{l}
H_0 : \mu_1 =\mu_2 =\mu_3 \\
H_1 : \mu_1\neq \mu_2\mbox{ o }\mu_1\neq \mu_3\mbox{ o }\mu_2\neq \mu_3
\end{array}
\right.
$$




\frametitle{ANOVA de bloques}

Aunque hemos usado un factor, no podemos realizar un ANOVA de 1 vía: las muestras no son independientes, sino emparejadas\pause


El \red{ANOVA de bloques} generaliza el contraste de medias para dos muestras emparejadas, a $k$ muestras emparejadas


Tenemos $k$ tratamientos que queremos comparar


Escogemos $b$ \emph{bloques}: conjuntos de $k$ sujetos emparejados (por ejemplo, $k$ copias del mismo sujeto)

Dentro de cada bloque, asignamos aleatoriamente a cada sujeto un tratamiento, de manera que cada tratamiento se use exactamente una vez dentro de cada bloque





\frametitle{ANOVA de bloques}

El contraste que se quiere realizar es
$$
\left\{
\begin{array}{l}
H_0 : \mu_{1} =\mu_{2} =\cdots =\mu_{k} \\
H_1 : \mbox{Hay $i,j$ tales que } \mu_{i}  \neq \mu_{j}
\end{array}
\right.
$$
donde cada $\mu_{i}$ es la media del tratamiento $i$-ésimo

La filosofía del contraste es similar: la variabilidad de los datos  se descompone en la suma de

* la variabilidad de las medias muestrales de los tratamientos

* la variabilidad de las medias de los bloques

* la variabilidad residual debida a factores aleatorios al escoger las muestras


Se compara la variabilidad de las medias muestrales con la variabilidad residual



\frametitle{Suposiciones del contraste}

Para que las conclusiones tengan sentido, ha de pasar:


* Las $k\cdot b$ observaciones son muestras aleatorias  (de tamaño $1$)
independientes de $k\cdot b$ poblaciones


* Todas estas $k\cdot b$ poblaciones son  normales y con la misma
varianza


* No hay \emph{interacción} entre los bloques y los tratamientos: las diferencias entre las medias poblacionales de las $a$ poblaciones definidas por un bloque y las de las $a$ poblaciones definidas por otro bloque son iguales


Ninguna se puede contrastar, por lo tanto el experimentador ha de decidir si se cumplen según su experiencia

Si puede haber interacción, se recomienda usar un ANOVA de 2 vías








\frametitle{Ejemplo 2}
Los resultados obtenidos son los siguientes:
\begin{center}
\begin{tabular}{c|ccc}
\multicolumn{1}{c}{ }&\multicolumn{3}{c}{Tratamiento}\\\hline
Bloque &1 (placebo) &2 (analg. A)&3 (analg. B)\\\hline
 1 & 35 & 20 & 22\\
2 & 40 & 35 & 42\\
3 & 60 & 50 & 30\\
 4 & 50 & 40 & 35\\
5 & 50 & 30 & 22 \\
6 & 52 & 30 & 25\\
7 & 37 & 22 & 18\\
8 & 45 & 30 & 28\\
 9 & 40 & 45 & 35\\
10 & 47 & 40 & 37
\end{tabular}
\end{center}


[fragile]
\frametitle{Ejemplo 2}\vspace*{-1ex}

Guardo los datos en un dataframe

\begin{lstlisting}
> N.C=c(35,20,22,40,35,42,60,50,30,50,
    40,35,50,30,22,52,30,25,37,22,18,
    45,30,28,40,45,35,47,40,37)
> Bloques=as.factor(rep(1:10,each=3))
> Trat=rep(c("Plac.","A","B"),10)
> Datos2=data.frame(N.C,Bloques,Trat)
> str(Datos2)
'data.frame':	30 obs. of  3 variables:
 $ N.C    : num  35 20 22 40 35 42 60 50 30 50 ...
 $ Bloques: Factor w/ 10 levels "1","2","3","4",..: 1 1 1 2 2 2 3 3 3 4 ...
 $ Trat   : Factor w/ 3 levels "A","B","Plac.": 3 1 2 3 1 2 3 1 2 3 ...
\end{lstlisting}


[fragile]
\frametitle{Ejemplo 2}

\begin{lstlisting}
> head(Datos2,9)
  N.C Bloques  Trat
1  35       1 Plac.
2  20       1     A
3  22       1     B
4  40       2 Plac.
5  35       2     A
6  42       2     B
7  60       3 Plac.
8  50       3     A
9  30       3     B
\end{lstlisting}


[fragile]
\frametitle{Ejemplo 2}

Para calcular la tabla del ANOVA de bloques, se aplica \texttt{summary(aov( ))} \blue{sumando el factor tratamiento y el factor bloques}


\begin{lstlisting}
> summary(aov(N.C~Trat+Bloques,data=Datos2))
          Df Sum Sq Mean Sq F value   Pr(>F)    
Trat       2 1384.8   692.4  18.830 3.87e-05 ***
Bloques    9 1254.5   139.4   3.791  0.00777 ** 
Residuals 18  661.9    36.8                     
---
Signif. codes:  0 `***' 0.001 `**' 0.01 `*' 0.05 `.' 0.1 ` ' 1
\end{lstlisting}

El significado de las entradas de la tabla ANOVA es similar al de 1 vía

Se mira el p-valor de los tratamientos, \red{\tt Trat}: es $0.0000387$.


[fragile]
\frametitle{Ejemplo 2}

Como hemos obtenido evidencia de que hay medias diferentes, podemos buscar cuáles, realizando todos los contrastes por parejas

Ahora son contrastes de muestras emparejadas: se indica con \texttt{paired=TRUE} en \texttt{pairwise.t.test}


[fragile]
\frametitle{Ejemplo 2}

\begin{lstlisting}
> pairwise.t.test(Datos$N.C, Datos$Trat, 
  paired=TRUE, p.adjust.method="bonferroni")

	Pairwise comparisons using paired t tests 

data:  Datos$N.C and Datos$Trat 

      A      B     
B     0.1921 -     
Plac. 0.0040 0.0024

P value adjustment method: bonferroni 
\end{lstlisting}

Hay evidencia de que A y B son diferentes que el Placebo, pero no hay evidencia de diferencia entre ellos




\subsection{ANOVA de 2 vías}


\frametitle{ANOVA de dos vías}

\emph{Experimento factorial}: comparamos las medias de subpoblaciones definidas mediante combinaciones de niveles de 2 o más factores


El caso más sencillo es el \emph{ANOVA de 2 vías}:


* Usamos dos factores (\emph{dos vías})


* Tomamos muestras aleatorias independientes \blue{del mismo tamaño} de cada combinación de niveles de los dos factores



[fragile]
\frametitle{Ejemplo 3}

Deseamos contrastar si el nivel de colesterol depende del sexo o la complexión de las personas

Hemos creado una tabla de datos con el nivel de colesterol de 30 personas de cada combinación Sexo-Complexión y la hemos guardado en nuestro Dropbox

\begin{lstlisting}
> Dat.Col=read.table("https://www.dropbox.com/s/i516p5eg0u3ol8t/colesterol.txt?raw=1",header=T)
\end{lstlisting}


[fragile]
\frametitle{Ejemplo 3}

\begin{lstlisting}
> str(Dat.Col)
'data.frame':	180 obs. of  3 variables:
 $ chol : int  195 193 215 188 179 227 255 235 183 196 ...
 $ frame: Factor w/ 3 levels "large","medium",..: 1 3 1 1 3 2 2 3 2 1 ...
 $ sex  : Factor w/ 2 levels "female","male": 2 1 1 1 2 1 2 1 1 1 ...
> table(Dat.Col[,2:3])
        sex
frame    female male
  large      30   30
  medium     30   30
  small      30   30
\end{lstlisting}



\frametitle{Ejemplo 3}

Nos puede interesar:


* Contrastar si hay diferencia en el nivel medio de colesterol según el sexo, teniendo en cuenta que una parte de la variabilidad proviene de la complexión

* Contrastar si hay diferencia en el nivel medio de colesterol según la complexión, teniendo en cuenta que una parte de la variabilidad proviene del sexo

* Contrastar si hay diferencia en el nivel medio de colesterol según la combinación sexo-complexión

* Contrastar si en el nivel medio de colesterol se observa interacción entre el sexo y la complexión (que el efecto de los niveles de un factor se magnifiquen en los del otro factor)









\frametitle{ANOVA de dos vías}
Tenemos en cuenta dos factores, $A$ y $B$. El factor $A$ tiene 
\red{$a$} niveles y el factor $B$,  \red{$b$} niveles.


Realizamos 
\red{$n$} observaciones para cada combinación de tratamientos.
El número total de observaciones será $n\cdot a\cdot b$.

Llamemos:

* $\mu_{i\bullet}$: media poblacional del nivel $i$-ésimo del factor $A$

* $\mu_{\bullet j}$: media poblacional del nivel $j$-ésimo del factor $B$

* $\mu_{ij}$: media poblacional de la combinación (nivel $i$-ésimo de $A$)--(nivel $j$-ésimo de $B$)







\frametitle{Contrastes a realizar}

En una ANOVA de 2 vías, nos pueden interesar 
los cuatro contrastes siguientes:

\emph{Contraste de medias del factor $A$}: Contrastamos si hay diferencias entre los niveles del factor $A$:
$$
\left\{
\begin{array}{l}
H_0 : \mu_{1\bullet}=\mu_{2\bullet}=\cdots
=\mu_{a\bullet} \\
H_1 : \mbox{Hay $i,i'$ tales que  $\mu_{i\bullet}\neq \mu_{i'\bullet}$}
\end{array}
\right.
$$


\emph{Contraste de medias del factor $B$}: Contrastamos si hay diferencias entre los niveles del factor $B$:
$$
\left\{
\begin{array}{l}
H_0 : \mu_{\bullet 1}=\mu_{\bullet 2}=\cdots =\mu_{\bullet b} \\
H_1 : \mbox{Hay $j,j''$ tales que  $\mu_{\bullet j}\neq \mu_{\bullet j'}$}
\end{array}
\right.
$$





\frametitle{Contrastes a realizar}

En una ANOVA de 2 vías, nos pueden interesar 
los cuatro contrastes siguientes:

\emph{Contraste de medias de la combinación}: Contrastamos si hay diferencias entre las parejas (nivel de $A$, nivel de $B$):
$$
\left\{
\begin{array}{l}
H_0 : \mbox{Para todos $i,j,i',j'$,  $\mu_{ij}=\mu_{i'j'}$} \\
H_1 : \mbox{Hay $i,j,i',j'$ tales que  $\mu_{ij}\neq \mu_{i'j'}$}
\end{array}
\right.
$$


\emph{Contraste de interacción}: Contrastamos si hay interacción entre los niveles de $A$ y $B$
$$
\left\{
\begin{array}{l}
H_0 : \mbox{No hay interacción entre ningún par de niveles} \\
H_1 : \mbox{Hay interacción entre algún par de niveles}
\end{array}
\right.
$$




\frametitle{Suposiciones del contraste}
Para que las conclusiones del ANOVA tengan sentido:



* Las observaciones para cada combinación de niveles constituyen
muestras aleatorias simples independientes, cada una de tamaño $n$, de $a\cdot b$
poblaciones 
 

* Cada una de las $a\cdot b$ poblaciones es normal y todas tienen la misma varianza $\sigma^2$


La primera condición es responsabilidad del investigador, la segunda se ha de comprobar con los tests adecuados



[fragile]
\frametitle{Ejemplo 3}

Aplicando \texttt{summary(aov( ))} \blue{multiplicando los dos factores} obtenemos la tabla de los contrastes del factor A, el factor B y la interacción


\begin{lstlisting}
> summary(aov(chol~frame*sex,data= Dat.Col))
           Df Sum Sq Mean Sq F value Pr(>F)  
frame       2  10243    5122   2.769 0.0655 .
sex         1   1748    1748   0.945 0.3323  
frame:sex   2    161      80   0.043 0.9576  
Residuals 174 321898    1850                 
---
Signif. codes:  0 `***' 0.001 `**' 0.01 `*' 0.05 `.' 0.1 ` ' 1
\end{lstlisting}
Con $\alpha=0.05$, no encontramos evidencia de ninguna diferencia ni de interacción




[fragile]
\frametitle{Ejemplo 3}

Aplicando \texttt{summary(aov( ))} \blue{combinando los dos factores con :} obtenemos la tabla del contraste de medias de la combinación

\begin{lstlisting}
> summary(aov(chol~frame:sex,data= Dat.Col))
           Df Sum Sq Mean Sq F value Pr(>F)
frame:sex   5  12152    2430   1.314   0.26
Residuals 174 321898    1850               
---
Signif. codes:  0 `***' 0.001 `**' 0.01 `*' 0.05 `.' 0.1 ` ' 1
\end{lstlisting}
No encontramos evidencia de  diferencia





\section{Contrastes no paramétricos}

[fragile]
\frametitle{Una vía}

Si en un experimento de 1 vía no podemos aplicar ANOVA porque no se cumplan las condiciones para que las conclusiones tengan sentido, hay que usar un test no paramétrico.

El más popular es el \red{test de Kruskal-Wallis}, implementado en la función \red{\tt kruskal.test}


\begin{lstlisting}
> kruskal.test(N.E~Trat, data=Datos1)

	Kruskal-Wallis rank sum test

data:  N.E by Trat
Kruskal-Wallis chi-squared = 9.0924, df = 2, p-value = 0.01061
\end{lstlisting}




[fragile] 
\frametitle{Bloques}
Si en un experimento de bloques no podemos aplicar ANOVA porque sospechéis que no se cumplen las condiciones para que las conclusiones tengan sentido, hay que usar un test no paramétrico

El más popular es el \red{test de Friedman}, implementado en la función \red{\tt friedman.test}


\begin{lstlisting}
> friedman.test(N.C~Trat|Bloques, data=Datos2)

	Friedman rank sum test

data:  N.C and Trat and Bloques
Friedman chi-squared = 11.4, df = 2, p-value = 0.003346
\end{lstlisting}





 
\frametitle{Dos vías}
Si en un experimento de 2 vías no podemos aplicar ANOVA porque no se cumplan las condiciones para que las conclusiones tengan sentido, hay que usar un test no paramétrico

A este nivel, no hay ninguna opción sencilla cuando hay interacción entre los factores




 
\frametitle{Dos vías}

Si sospecháis que no hay interacción, os recomendamos:

* Para el contraste de medias de la combinación, usar el test de Kruskal-Wallis para la combinación de factores (definida con \texttt{interaction})

* Para el contraste de medias de cada factor,  calcular las medias por combinaciones de niveles y luego usar el \red{test de Friedman}, implementado en la función \red{\tt friedman.test}, entrando en orden los factores 







[fragile]
\frametitle{Dos vías}

Contraste de medias de combinaciones:

\begin{lstlisting}
> kruskal.test(chol~interaction(frame,sex),data=Dat.Col)

	Kruskal-Wallis rank sum test

data:  chol by interaction(frame, sex)
Kruskal-Wallis chi-squared = 6.6889, df = 5, p-value = 0.2448
\end{lstlisting}




[fragile]
\frametitle{Dos vías}

Cálculo de las medias por combinaciones de niveles:

\begin{lstlisting}
> Datos3=aggregate(chol~frame+sex,
   data=Dat.Col, FUN=mean)
> Datos3
   frame    sex     chol
1  large female 213.6667
2 medium female 217.9333
3  small female 199.8667
4  large   male 204.7667
5 medium   male 213.1667
6  small   male 194.8333
\end{lstlisting}




[fragile]
\frametitle{Dos vías}

Contraste de las medias del factor \texttt{frame}:

\begin{lstlisting}
> friedman.test(chol~frame|sex,data=Datos3)

	Friedman rank sum test

data:  chol and frame and sex
Friedman chi-squared = 4, df = 2, 
   p-value = 0.1353
\end{lstlisting}

Contraste de las medias del factor \texttt{sex}:

\begin{lstlisting}
> friedman.test(chol~sex|frame,data=Datos3)

	Friedman rank sum test

data:  chol and sex and frame
Friedman chi-squared = 3, df = 1, 
   p-value = 0.08326
\end{lstlisting}






\end{document}


