<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lección 14 Contrastes de hipótesis | Bioestadística (Medicina UIB)</title>
  <meta name="description" content="Apunts Bioestadística per a Medicina bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Lección 14 Contrastes de hipótesis | Bioestadística (Medicina UIB)" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Apunts Bioestadística per a Medicina bookdown::gitbook." />
  <meta name="github-repo" content="AprendeR-UIB/INREMDN" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lección 14 Contrastes de hipótesis | Bioestadística (Medicina UIB)" />
  
  <meta name="twitter:description" content="Apunts Bioestadística per a Medicina bookdown::gitbook." />
  

<meta name="author" content="Irene García, Francesc Rosselló" />


<meta name="date" content="2024-04-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intervalos-de-confianza.html"/>
<link rel="next" href="qué-test-usar.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">INREMDN</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentación</a></li>
<li class="part"><span><b>Tema I: Introducción a los estudios médicos y la estadística</b></span></li>
<li class="chapter" data-level="1" data-path="introducción.html"><a href="introducción.html"><i class="fa fa-check"></i><b>1</b> Introducción</a></li>
<li class="chapter" data-level="2" data-path="estudios-médicos.html"><a href="estudios-médicos.html"><i class="fa fa-check"></i><b>2</b> Estudios médicos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="estudios-médicos.html"><a href="estudios-médicos.html#sec:pasos"><i class="fa fa-check"></i><b>2.1</b> Pasos de un estudio médico</a></li>
<li class="chapter" data-level="2.2" data-path="estudios-médicos.html"><a href="estudios-médicos.html#algunos-calificativos-para-los-estudios-médicos"><i class="fa fa-check"></i><b>2.2</b> Algunos calificativos para los estudios médicos</a></li>
<li class="chapter" data-level="2.3" data-path="estudios-médicos.html"><a href="estudios-médicos.html#estudios-descriptivos"><i class="fa fa-check"></i><b>2.3</b> Estudios descriptivos</a></li>
<li class="chapter" data-level="2.4" data-path="estudios-médicos.html"><a href="estudios-médicos.html#sec:cyc"><i class="fa fa-check"></i><b>2.4</b> Estudios de casos y controles</a></li>
<li class="chapter" data-level="2.5" data-path="estudios-médicos.html"><a href="estudios-médicos.html#estudios-de-cohorte"><i class="fa fa-check"></i><b>2.5</b> Estudios de cohorte</a></li>
<li class="chapter" data-level="2.6" data-path="estudios-médicos.html"><a href="estudios-médicos.html#estudios-transversales"><i class="fa fa-check"></i><b>2.6</b> Estudios transversales</a></li>
<li class="chapter" data-level="2.7" data-path="estudios-médicos.html"><a href="estudios-médicos.html#sec:ecol"><i class="fa fa-check"></i><b>2.7</b> Estudios ecológicos</a></li>
<li class="chapter" data-level="2.8" data-path="estudios-médicos.html"><a href="estudios-médicos.html#ensayos-clínicos"><i class="fa fa-check"></i><b>2.8</b> Ensayos clínicos</a></li>
<li class="chapter" data-level="2.9" data-path="estudios-médicos.html"><a href="estudios-médicos.html#a-modo-de-resumen"><i class="fa fa-check"></i><b>2.9</b> A modo de resumen</a></li>
<li class="chapter" data-level="2.10" data-path="estudios-médicos.html"><a href="estudios-médicos.html#revisiones-sistemáticas-y-metaanálisis"><i class="fa fa-check"></i><b>2.10</b> Revisiones sistemáticas y metaanálisis</a></li>
<li class="chapter" data-level="2.11" data-path="estudios-médicos.html"><a href="estudios-médicos.html#sec:causalidad"><i class="fa fa-check"></i><b>2.11</b> (Bonus track) Unos criterios de causalidad</a></li>
<li class="chapter" data-level="2.12" data-path="estudios-médicos.html"><a href="estudios-médicos.html#bonus-track-preguntas-clínicas-en-formato-pico"><i class="fa fa-check"></i><b>2.12</b> (Bonus track) Preguntas clínicas en formato PICO</a></li>
<li class="chapter" data-level="2.13" data-path="estudios-médicos.html"><a href="estudios-médicos.html#test"><i class="fa fa-check"></i><b>2.13</b> Test</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="algunos-conceptos-básicos-más.html"><a href="algunos-conceptos-básicos-más.html"><i class="fa fa-check"></i><b>3</b> Algunos conceptos básicos más</a>
<ul>
<li class="chapter" data-level="3.1" data-path="algunos-conceptos-básicos-más.html"><a href="algunos-conceptos-básicos-más.html#unidad-de-observación"><i class="fa fa-check"></i><b>3.1</b> Unidad de observación</a></li>
<li class="chapter" data-level="3.2" data-path="algunos-conceptos-básicos-más.html"><a href="algunos-conceptos-básicos-más.html#población-y-muestra"><i class="fa fa-check"></i><b>3.2</b> Población y muestra</a></li>
<li class="chapter" data-level="3.3" data-path="algunos-conceptos-básicos-más.html"><a href="algunos-conceptos-básicos-más.html#sec:muestreo"><i class="fa fa-check"></i><b>3.3</b> Tipos básicos de muestreo</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="algunos-conceptos-básicos-más.html"><a href="algunos-conceptos-básicos-más.html#sec:mas"><i class="fa fa-check"></i><b>3.3.1</b> Muestreo aleatorio con y sin reposición</a></li>
<li class="chapter" data-level="3.3.2" data-path="algunos-conceptos-básicos-más.html"><a href="algunos-conceptos-básicos-más.html#sec:sist"><i class="fa fa-check"></i><b>3.3.2</b> Muestreo sistemático</a></li>
<li class="chapter" data-level="3.3.3" data-path="algunos-conceptos-básicos-más.html"><a href="algunos-conceptos-básicos-más.html#sec:estr"><i class="fa fa-check"></i><b>3.3.3</b> Muestreo aleatorio estratificado</a></li>
<li class="chapter" data-level="3.3.4" data-path="algunos-conceptos-básicos-más.html"><a href="algunos-conceptos-básicos-más.html#sec:mcluster"><i class="fa fa-check"></i><b>3.3.4</b> Muestreo por conglomerados</a></li>
<li class="chapter" data-level="3.3.5" data-path="algunos-conceptos-básicos-más.html"><a href="algunos-conceptos-básicos-más.html#sec:oport"><i class="fa fa-check"></i><b>3.3.5</b> Muestreos no aleatorios</a></li>
<li class="chapter" data-level="3.3.6" data-path="algunos-conceptos-básicos-más.html"><a href="algunos-conceptos-básicos-más.html#sec:poli"><i class="fa fa-check"></i><b>3.3.6</b> Muestreo polietápico</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="algunos-conceptos-básicos-más.html"><a href="algunos-conceptos-básicos-más.html#sec:sesgos"><i class="fa fa-check"></i><b>3.4</b> Sesgos</a></li>
<li class="chapter" data-level="3.5" data-path="algunos-conceptos-básicos-más.html"><a href="algunos-conceptos-básicos-más.html#test-1"><i class="fa fa-check"></i><b>3.5</b> Test</a></li>
</ul></li>
<li class="part"><span><b>Tema II: Probabilidades</b></span></li>
<li class="chapter" data-level="4" data-path="probabilidades-elementales-las-mates.html"><a href="probabilidades-elementales-las-mates.html"><i class="fa fa-check"></i><b>4</b> Probabilidades elementales: Las mates</a>
<ul>
<li class="chapter" data-level="4.1" data-path="probabilidades-elementales-las-mates.html"><a href="probabilidades-elementales-las-mates.html#álgebra-de-conjuntos"><i class="fa fa-check"></i><b>4.1</b> Álgebra de conjuntos</a></li>
<li class="chapter" data-level="4.2" data-path="probabilidades-elementales-las-mates.html"><a href="probabilidades-elementales-las-mates.html#algunas-fórmulas-básicas"><i class="fa fa-check"></i><b>4.2</b> Algunas fórmulas básicas</a></li>
<li class="chapter" data-level="4.3" data-path="probabilidades-elementales-las-mates.html"><a href="probabilidades-elementales-las-mates.html#sec:odds"><i class="fa fa-check"></i><b>4.3</b> Odds</a></li>
<li class="chapter" data-level="4.4" data-path="probabilidades-elementales-las-mates.html"><a href="probabilidades-elementales-las-mates.html#probabilidad-condicionada"><i class="fa fa-check"></i><b>4.4</b> Probabilidad condicionada</a></li>
<li class="chapter" data-level="4.5" data-path="probabilidades-elementales-las-mates.html"><a href="probabilidades-elementales-las-mates.html#sucesos-independientes"><i class="fa fa-check"></i><b>4.5</b> Sucesos independientes</a></li>
<li class="chapter" data-level="4.6" data-path="probabilidades-elementales-las-mates.html"><a href="probabilidades-elementales-las-mates.html#odds-condicionadas-y-odds-ratios-relativas"><i class="fa fa-check"></i><b>4.6</b> Odds condicionadas y odds ratios relativas</a></li>
<li class="chapter" data-level="4.7" data-path="probabilidades-elementales-las-mates.html"><a href="probabilidades-elementales-las-mates.html#el-teorema-de-la-probabilidad-total"><i class="fa fa-check"></i><b>4.7</b> El teorema de la probabilidad total</a></li>
<li class="chapter" data-level="4.8" data-path="probabilidades-elementales-las-mates.html"><a href="probabilidades-elementales-las-mates.html#la-fórmula-de-bayes"><i class="fa fa-check"></i><b>4.8</b> La fórmula de Bayes</a></li>
<li class="chapter" data-level="4.9" data-path="probabilidades-elementales-las-mates.html"><a href="probabilidades-elementales-las-mates.html#test-2"><i class="fa fa-check"></i><b>4.9</b> Test</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="probabilidades-elementales-aplicaciones-en-medicina.html"><a href="probabilidades-elementales-aplicaciones-en-medicina.html"><i class="fa fa-check"></i><b>5</b> Probabilidades elementales: Aplicaciones en medicina</a>
<ul>
<li class="chapter" data-level="5.1" data-path="probabilidades-elementales-aplicaciones-en-medicina.html"><a href="probabilidades-elementales-aplicaciones-en-medicina.html#pruebas-diagnósticas"><i class="fa fa-check"></i><b>5.1</b> Pruebas diagnósticas</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="probabilidades-elementales-aplicaciones-en-medicina.html"><a href="probabilidades-elementales-aplicaciones-en-medicina.html#sensibilidad-especificidad-valores-predictivos-etc."><i class="fa fa-check"></i><b>5.1.1</b> Sensibilidad, especificidad, valores predictivos etc.</a></li>
<li class="chapter" data-level="5.1.2" data-path="probabilidades-elementales-aplicaciones-en-medicina.html"><a href="probabilidades-elementales-aplicaciones-en-medicina.html#curvas-roc"><i class="fa fa-check"></i><b>5.1.2</b> Curvas ROC</a></li>
<li class="chapter" data-level="5.1.3" data-path="probabilidades-elementales-aplicaciones-en-medicina.html"><a href="probabilidades-elementales-aplicaciones-en-medicina.html#con-jamovi"><i class="fa fa-check"></i><b>5.1.3</b> Con JAMOVI</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="probabilidades-elementales-aplicaciones-en-medicina.html"><a href="probabilidades-elementales-aplicaciones-en-medicina.html#sec:probaplic2"><i class="fa fa-check"></i><b>5.2</b> Riesgos</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="probabilidades-elementales-aplicaciones-en-medicina.html"><a href="probabilidades-elementales-aplicaciones-en-medicina.html#sec:riesgosRR"><i class="fa fa-check"></i><b>5.2.1</b> Riesgos relativos y absolutos</a></li>
<li class="chapter" data-level="5.2.2" data-path="probabilidades-elementales-aplicaciones-en-medicina.html"><a href="probabilidades-elementales-aplicaciones-en-medicina.html#sec:riesgosCyC"><i class="fa fa-check"></i><b>5.2.2</b> <em>Odds ratios</em></a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="probabilidades-elementales-aplicaciones-en-medicina.html"><a href="probabilidades-elementales-aplicaciones-en-medicina.html#tratamientos"><i class="fa fa-check"></i><b>5.3</b> Tratamientos</a></li>
<li class="chapter" data-level="5.4" data-path="probabilidades-elementales-aplicaciones-en-medicina.html"><a href="probabilidades-elementales-aplicaciones-en-medicina.html#test-3"><i class="fa fa-check"></i><b>5.4</b> Test</a></li>
</ul></li>
<li class="part"><span><b>Tema III: Estadística descriptiva</b></span></li>
<li class="chapter" data-level="6" data-path="sec:tiposdatos.html"><a href="sec:tiposdatos.html"><i class="fa fa-check"></i><b>6</b> Tipos de datos</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sec:tiposdatos.html"><a href="sec:tiposdatos.html#test-4"><i class="fa fa-check"></i><b>6.1</b> Test</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="descripción-de-datos-cualitativos.html"><a href="descripción-de-datos-cualitativos.html"><i class="fa fa-check"></i><b>7</b> Descripción de datos cualitativos</a>
<ul>
<li class="chapter" data-level="7.1" data-path="descripción-de-datos-cualitativos.html"><a href="descripción-de-datos-cualitativos.html#sec:frecs"><i class="fa fa-check"></i><b>7.1</b> Frecuencias</a></li>
<li class="chapter" data-level="7.2" data-path="descripción-de-datos-cualitativos.html"><a href="descripción-de-datos-cualitativos.html#gráficos"><i class="fa fa-check"></i><b>7.2</b> Gráficos</a></li>
<li class="chapter" data-level="7.3" data-path="descripción-de-datos-cualitativos.html"><a href="descripción-de-datos-cualitativos.html#tablas-de-frecuencias-multidimensionales"><i class="fa fa-check"></i><b>7.3</b> Tablas de frecuencias multidimensionales</a></li>
<li class="chapter" data-level="7.4" data-path="descripción-de-datos-cualitativos.html"><a href="descripción-de-datos-cualitativos.html#sec:barrasbidim"><i class="fa fa-check"></i><b>7.4</b> Diagramas de barras bidimensionales</a></li>
<li class="chapter" data-level="7.5" data-path="descripción-de-datos-cualitativos.html"><a href="descripción-de-datos-cualitativos.html#diagramas-de-mosaico"><i class="fa fa-check"></i><b>7.5</b> Diagramas de mosaico</a></li>
<li class="chapter" data-level="7.6" data-path="descripción-de-datos-cualitativos.html"><a href="descripción-de-datos-cualitativos.html#test-5"><i class="fa fa-check"></i><b>7.6</b> Test</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="descripción-de-datos-ordinales.html"><a href="descripción-de-datos-ordinales.html"><i class="fa fa-check"></i><b>8</b> Descripción de datos ordinales</a>
<ul>
<li class="chapter" data-level="8.1" data-path="descripción-de-datos-ordinales.html"><a href="descripción-de-datos-ordinales.html#frecuencias-y-diagramas-de-barras"><i class="fa fa-check"></i><b>8.1</b> Frecuencias y diagramas de barras</a></li>
<li class="chapter" data-level="8.2" data-path="descripción-de-datos-ordinales.html"><a href="descripción-de-datos-ordinales.html#test-6"><i class="fa fa-check"></i><b>8.2</b> Test</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html"><i class="fa fa-check"></i><b>9</b> Descripción de datos cuantitativos</a>
<ul>
<li class="chapter" data-level="9.1" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html#frecuencias"><i class="fa fa-check"></i><b>9.1</b> Frecuencias</a></li>
<li class="chapter" data-level="9.2" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html#medidas-de-tendencia-central"><i class="fa fa-check"></i><b>9.2</b> Medidas de tendencia central</a></li>
<li class="chapter" data-level="9.3" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html#medidas-de-posición"><i class="fa fa-check"></i><b>9.3</b> Medidas de posición</a></li>
<li class="chapter" data-level="9.4" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html#medidas-de-dispersión"><i class="fa fa-check"></i><b>9.4</b> Medidas de dispersión</a></li>
<li class="chapter" data-level="9.5" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html#diagramas-de-puntos-y-de-caja"><i class="fa fa-check"></i><b>9.5</b> Diagramas de puntos y de caja</a></li>
<li class="chapter" data-level="9.6" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html#histogramas"><i class="fa fa-check"></i><b>9.6</b> Histogramas</a></li>
<li class="chapter" data-level="9.7" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html#polígonos-de-frecuencias"><i class="fa fa-check"></i><b>9.7</b> Polígonos de frecuencias</a></li>
<li class="chapter" data-level="9.8" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html#asimetría-y-curtosis"><i class="fa fa-check"></i><b>9.8</b> Asimetría y curtosis</a></li>
<li class="chapter" data-level="9.9" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html#estadísticos-y-gráficos-con-jamovi"><i class="fa fa-check"></i><b>9.9</b> Estadísticos y gráficos con JAMOVI</a></li>
<li class="chapter" data-level="9.10" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html#sec:estagrup"><i class="fa fa-check"></i><b>9.10</b> Estadísticos sobre datos agrupados</a></li>
<li class="chapter" data-level="9.11" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html#sec:edbivar"><i class="fa fa-check"></i><b>9.11</b> Datos cuantitativos bivariantes</a></li>
<li class="chapter" data-level="9.12" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html#gráficos-en-escala-logarítmica"><i class="fa fa-check"></i><b>9.12</b> Gráficos en escala logarítmica</a></li>
<li class="chapter" data-level="9.13" data-path="descripción-de-datos-cuantitativos.html"><a href="descripción-de-datos-cuantitativos.html#test-7"><i class="fa fa-check"></i><b>9.13</b> Test</a></li>
</ul></li>
<li class="part"><span><b>Tema IV: Variables aleatorias</b></span></li>
<li class="chapter" data-level="10" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html"><i class="fa fa-check"></i><b>10</b> Variables aleatorias discretas</a>
<ul>
<li class="chapter" data-level="10.1" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#densidad-y-distribución"><i class="fa fa-check"></i><b>10.1</b> Densidad y distribución</a></li>
<li class="chapter" data-level="10.2" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#esperanza"><i class="fa fa-check"></i><b>10.2</b> Esperanza</a></li>
<li class="chapter" data-level="10.3" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#varianza-y-desviación-típica"><i class="fa fa-check"></i><b>10.3</b> Varianza y desviación típica</a></li>
<li class="chapter" data-level="10.4" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#cuantiles"><i class="fa fa-check"></i><b>10.4</b> Cuantiles</a></li>
<li class="chapter" data-level="10.5" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#familias-importantes-de-variables-aleatorias-discretas"><i class="fa fa-check"></i><b>10.5</b> Familias importantes de variables aleatorias discretas</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#variables-aleatorias-binomiales"><i class="fa fa-check"></i><b>10.5.1</b> Variables aleatorias binomiales</a></li>
<li class="chapter" data-level="10.5.2" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#variables-aleatorias-hipergeométricas"><i class="fa fa-check"></i><b>10.5.2</b> Variables aleatorias hipergeométricas</a></li>
<li class="chapter" data-level="10.5.3" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#variables-aleatorias-de-poisson"><i class="fa fa-check"></i><b>10.5.3</b> Variables aleatorias de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#test-8"><i class="fa fa-check"></i><b>10.6</b> Test</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html"><i class="fa fa-check"></i><b>11</b> Variables aleatorias continuas</a>
<ul>
<li class="chapter" data-level="11.1" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#densidad-y-distribución-1"><i class="fa fa-check"></i><b>11.1</b> Densidad y distribución</a></li>
<li class="chapter" data-level="11.2" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#esperanza-varianza-cuantiles"><i class="fa fa-check"></i><b>11.2</b> Esperanza, varianza, cuantiles…</a></li>
<li class="chapter" data-level="11.3" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#sec:normal"><i class="fa fa-check"></i><b>11.3</b> Variables aleatorias normales</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#propiedades-básicas"><i class="fa fa-check"></i><b>11.3.1</b> Propiedades básicas</a></li>
<li class="chapter" data-level="11.3.2" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#intervalos-de-referencia"><i class="fa fa-check"></i><b>11.3.2</b> Intervalos de referencia</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#test-9"><i class="fa fa-check"></i><b>11.4</b> Test</a></li>
</ul></li>
<li class="part"><span><b>Tema V: Estadística inferencial</b></span></li>
<li class="chapter" data-level="12" data-path="estimadores.html"><a href="estimadores.html"><i class="fa fa-check"></i><b>12</b> Estimadores</a>
<ul>
<li class="chapter" data-level="12.1" data-path="estimadores.html"><a href="estimadores.html#la-media-muestral"><i class="fa fa-check"></i><b>12.1</b> La media muestral</a></li>
<li class="chapter" data-level="12.2" data-path="estimadores.html"><a href="estimadores.html#la-proporción-muestral"><i class="fa fa-check"></i><b>12.2</b> La proporción muestral</a></li>
<li class="chapter" data-level="12.3" data-path="estimadores.html"><a href="estimadores.html#la-varianza-muestral"><i class="fa fa-check"></i><b>12.3</b> La varianza muestral</a></li>
<li class="chapter" data-level="12.4" data-path="estimadores.html"><a href="estimadores.html#la-distribución-t-de-student"><i class="fa fa-check"></i><b>12.4</b> La distribución t de Student</a></li>
<li class="chapter" data-level="12.5" data-path="estimadores.html"><a href="estimadores.html#test-10"><i class="fa fa-check"></i><b>12.5</b> Test</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html"><i class="fa fa-check"></i><b>13</b> Intervalos de confianza</a>
<ul>
<li class="chapter" data-level="13.1" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#sec:IC"><i class="fa fa-check"></i><b>13.1</b> Definiciones básicas</a></li>
<li class="chapter" data-level="13.2" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#un-ejemplo-ic-95-para-la-media-de-una-variable-aleatoria-normal"><i class="fa fa-check"></i><b>13.2</b> Un ejemplo: IC-95% para la media de una variable aleatoria normal</a></li>
<li class="chapter" data-level="13.3" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-la-media-basado-en-la-t-de-student"><i class="fa fa-check"></i><b>13.3</b> Intervalo de confianza para la media basado en la t de Student</a></li>
<li class="chapter" data-level="13.4" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalos-de-confianza-para-proporciones"><i class="fa fa-check"></i><b>13.4</b> Intervalos de confianza para proporciones</a></li>
<li class="chapter" data-level="13.5" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#bonus-track-otros-intervalos-de-confianza"><i class="fa fa-check"></i><b>13.5</b> (Bonus track) Otros intervalos de confianza</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#un-intervalo-de-confianza-para-la-diferencia-de-proporciones"><i class="fa fa-check"></i><b>13.5.1</b> Un intervalo de confianza para la diferencia de proporciones</a></li>
<li class="chapter" data-level="13.5.2" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalos-de-confianza-para-diferencias-de-medias"><i class="fa fa-check"></i><b>13.5.2</b> Intervalos de confianza para diferencias de medias</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#test-11"><i class="fa fa-check"></i><b>13.6</b> Test</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="contrastes-de-hipótesis.html"><a href="contrastes-de-hipótesis.html"><i class="fa fa-check"></i><b>14</b> Contrastes de hipótesis</a>
<ul>
<li class="chapter" data-level="14.1" data-path="contrastes-de-hipótesis.html"><a href="contrastes-de-hipótesis.html#hipótesis-nula-y-alternativa"><i class="fa fa-check"></i><b>14.1</b> Hipótesis nula y alternativa</a></li>
<li class="chapter" data-level="14.2" data-path="contrastes-de-hipótesis.html"><a href="contrastes-de-hipótesis.html#sec:moneda"><i class="fa fa-check"></i><b>14.2</b> Un ejemplo</a></li>
<li class="chapter" data-level="14.3" data-path="contrastes-de-hipótesis.html"><a href="contrastes-de-hipótesis.html#sec:pval"><i class="fa fa-check"></i><b>14.3</b> El p-valor</a></li>
<li class="chapter" data-level="14.4" data-path="contrastes-de-hipótesis.html"><a href="contrastes-de-hipótesis.html#tipo-de-errores"><i class="fa fa-check"></i><b>14.4</b> Tipo de errores</a></li>
<li class="chapter" data-level="14.5" data-path="contrastes-de-hipótesis.html"><a href="contrastes-de-hipótesis.html#sec:exttest"><i class="fa fa-check"></i><b>14.5</b> Ejemplo: El test t</a></li>
<li class="chapter" data-level="14.6" data-path="contrastes-de-hipótesis.html"><a href="contrastes-de-hipótesis.html#la-potencia-de-un-contraste"><i class="fa fa-check"></i><b>14.6</b> La potencia de un contraste</a></li>
<li class="chapter" data-level="14.7" data-path="contrastes-de-hipótesis.html"><a href="contrastes-de-hipótesis.html#intervalo-de-confianza-de-un-contraste"><i class="fa fa-check"></i><b>14.7</b> Intervalo de confianza de un contraste</a></li>
<li class="chapter" data-level="14.8" data-path="contrastes-de-hipótesis.html"><a href="contrastes-de-hipótesis.html#ajuste-de-p-valores"><i class="fa fa-check"></i><b>14.8</b> Ajuste de p-valores</a></li>
<li class="chapter" data-level="14.9" data-path="contrastes-de-hipótesis.html"><a href="contrastes-de-hipótesis.html#resultados-estadísticamente-significativos-versus-resultados-clínicamente-significativos"><i class="fa fa-check"></i><b>14.9</b> Resultados estadísticamente significativos <em>versus</em> resultados clínicamente significativos</a></li>
<li class="chapter" data-level="14.10" data-path="contrastes-de-hipótesis.html"><a href="contrastes-de-hipótesis.html#test-12"><i class="fa fa-check"></i><b>14.10</b> Test</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="qué-test-usar.html"><a href="qué-test-usar.html"><i class="fa fa-check"></i><b>15</b> ¿Qué test usar?</a>
<ul>
<li class="chapter" data-level="15.1" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-para-medias"><i class="fa fa-check"></i><b>15.1</b> Contrastes para medias</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-para-una-media"><i class="fa fa-check"></i><b>15.1.1</b> Contrastes para una media</a></li>
<li class="chapter" data-level="15.1.2" data-path="qué-test-usar.html"><a href="qué-test-usar.html#inciso-tests-de-normalidad"><i class="fa fa-check"></i><b>15.1.2</b> Inciso: tests de normalidad</a></li>
<li class="chapter" data-level="15.1.3" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-para-dos-medias"><i class="fa fa-check"></i><b>15.1.3</b> Contrastes para dos medias</a></li>
<li class="chapter" data-level="15.1.4" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-para-más-de-dos-medias"><i class="fa fa-check"></i><b>15.1.4</b> Contrastes para más de dos medias</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-para-varianzas"><i class="fa fa-check"></i><b>15.2</b> Contrastes para varianzas</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-bilaterales-para-dos-varianzas"><i class="fa fa-check"></i><b>15.2.1</b> Contrastes bilaterales para dos varianzas</a></li>
<li class="chapter" data-level="15.2.2" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-de-homogeneidad-para-más-de-dos-varianzas"><i class="fa fa-check"></i><b>15.2.2</b> Contrastes de homogeneidad para más de dos varianzas</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-para-proporciones"><i class="fa fa-check"></i><b>15.3</b> Contrastes para proporciones</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-para-una-proporción"><i class="fa fa-check"></i><b>15.3.1</b> Contrastes para una proporción</a></li>
<li class="chapter" data-level="15.3.2" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-para-dos-proporciones"><i class="fa fa-check"></i><b>15.3.2</b> Contrastes para dos proporciones</a></li>
<li class="chapter" data-level="15.3.3" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-para-más-de-dos-proporciones"><i class="fa fa-check"></i><b>15.3.3</b> Contrastes para más de dos proporciones</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-para-distribuciones"><i class="fa fa-check"></i><b>15.4</b> Contrastes para distribuciones</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-de-bondad-de-ajuste-de-una-muestra-a-una-distribución"><i class="fa fa-check"></i><b>15.4.1</b> Contrastes de bondad de ajuste de una muestra a una distribución</a></li>
<li class="chapter" data-level="15.4.2" data-path="qué-test-usar.html"><a href="qué-test-usar.html#sec:testindep"><i class="fa fa-check"></i><b>15.4.2</b> Contrastes de igualdad de dos o más distribuciones</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="qué-test-usar.html"><a href="qué-test-usar.html#contrastes-de-correlación"><i class="fa fa-check"></i><b>15.5</b> Contrastes de correlación</a></li>
<li class="chapter" data-level="15.6" data-path="qué-test-usar.html"><a href="qué-test-usar.html#test-13"><i class="fa fa-check"></i><b>15.6</b> Test</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="regresión-lineal.html"><a href="regresión-lineal.html"><i class="fa fa-check"></i><b>16</b> Regresión lineal</a>
<ul>
<li class="chapter" data-level="16.1" data-path="regresión-lineal.html"><a href="regresión-lineal.html#sec:rls"><i class="fa fa-check"></i><b>16.1</b> Regresión lineal simple</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="regresión-lineal.html"><a href="regresión-lineal.html#la-recta-de-regresión-lineal-por-mínimos-cuadrados"><i class="fa fa-check"></i><b>16.1.1</b> La recta de regresión lineal por mínimos cuadrados</a></li>
<li class="chapter" data-level="16.1.2" data-path="regresión-lineal.html"><a href="regresión-lineal.html#el-coeficiente-de-determinación"><i class="fa fa-check"></i><b>16.1.2</b> El coeficiente de determinación</a></li>
<li class="chapter" data-level="16.1.3" data-path="regresión-lineal.html"><a href="regresión-lineal.html#sec:confintrls"><i class="fa fa-check"></i><b>16.1.3</b> Intervalos de confianza</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="regresión-lineal.html"><a href="regresión-lineal.html#regresión-lineal-múltiple"><i class="fa fa-check"></i><b>16.2</b> Regresión lineal múltiple</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="regresión-lineal.html"><a href="regresión-lineal.html#la-función-de-regresión-lineal-múltiple"><i class="fa fa-check"></i><b>16.2.1</b> La función de regresión lineal múltiple</a></li>
<li class="chapter" data-level="16.2.2" data-path="regresión-lineal.html"><a href="regresión-lineal.html#coeficientes-de-determinación"><i class="fa fa-check"></i><b>16.2.2</b> Coeficientes de determinación</a></li>
<li class="chapter" data-level="16.2.3" data-path="regresión-lineal.html"><a href="regresión-lineal.html#intervalos-de-confianza-1"><i class="fa fa-check"></i><b>16.2.3</b> Intervalos de confianza</a></li>
<li class="chapter" data-level="16.2.4" data-path="regresión-lineal.html"><a href="regresión-lineal.html#adecuación-del-modelo"><i class="fa fa-check"></i><b>16.2.4</b> Adecuación del modelo</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="regresión-lineal.html"><a href="regresión-lineal.html#regresión-logística"><i class="fa fa-check"></i><b>16.3</b> Regresión logística</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Bioestadística (Medicina UIB)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="contrastes-de-hipótesis" class="section level1 hasAnchor" number="14">
<h1><span class="header-section-number">Lección 14</span> Contrastes de hipótesis<a href="contrastes-de-hipótesis.html#contrastes-de-hipótesis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En muchas situaciones, queremos tomar una <strong>decisión</strong> sobre si podemos aceptar o rechazar una <strong>hipótesis</strong> relativa al valor de un parámetro en una o varias poblaciones, y para tomar esta decisión, nos basamos en los datos de una muestra. Por ejemplo:</p>
<ul>
<li><p>Queremos saber si una moneda está trucada a favor de cara.</p>
<p>Para decidirlo, la lanzamos varias veces y contamos cuántas caras salen.</p></li>
<li><p>Queremos decidir si un tratamiento nuevo A es más efectivo que el tratamiento anterior B en la curación de una enfermedad X.</p>
<p>Para decidirlo, llevamos a cabo un ensayo clínico, tratando con A un grupo de enfermos y con B otro grupo de enfermos, y comparamos la tasa de curación de los tratamientos sobre estos dos grupos.</p></li>
</ul>
<p>El método estadístico que se usa para aceptar o rechazar una hipótesis a partir de los datos de una muestra recibe el nombre de <strong>contraste de hipótesis</strong>.</p>
<div id="hipótesis-nula-y-alternativa" class="section level2 hasAnchor" number="14.1">
<h2><span class="header-section-number">14.1</span> Hipótesis nula y alternativa<a href="contrastes-de-hipótesis.html#hipótesis-nula-y-alternativa" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En un contraste de hipótesis, se comparan siempre dos hipótesis alternativas: la <strong>hipótesis nula</strong> <span class="math inline">\(H_{0}\)</span> y la <strong>hipótesis alternativa</strong> <span class="math inline">\(H_{1}\)</span>. Se suele plantear formalmente
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}:\text{hipótesis nula}\\
H_{1}:\text{hipótesis alternativa}
\end{array}
\right.
\]</span></p>
<p>En los contrastes de hipótesis de este curso:</p>
<ul>
<li><p>La <strong>hipótesis nula</strong> <span class="math inline">\(H_{0}\)</span> es “no hay diferencia”, “no pasa nada”, “no hay nada extraño” o el equivalente en el contexto del contraste:</p>
<ul>
<li><p>La moneda es equilibrada (50% de probabilidad de cara).</p></li>
<li><p>Los tratamientos A y B son igual de efectivos en la curación de la enfermedad X.</p></li>
</ul></li>
<li><p>La <strong>hipótesis alternativa</strong> <span class="math inline">\(H_{1}\)</span> plantea la diferencia de la que buscamos evidencia:</p>
<ul>
<li><p>La moneda está trucada a favor de cara (más del 50% de probabilidad de cara).</p></li>
<li><p>A es más efectivo que B en la curación de la enfermedad X.</p></li>
</ul></li>
<li><p>Estamos dispuestos a aceptar <span class="math inline">\(H_0\)</span> por defecto: que no hay diferencia, que no pasa nada.</p>
<ul>
<li><p>Por defecto, estamos dispuestos a aceptar que la moneda es equilibrada (la mayoría lo son, ¿no?).</p></li>
<li><p>Por defecto, estamos dispuestos a aceptar que los dos tratamientos son igual de efectivos (si tomáis dos sustancias cualesquiera y las administráis a enfermos de X, lo más normal es que ninguna de los dos tenga efecto alguno, y por lo tanto que las dos sean igual de (in)efectivas).</p></li>
</ul></li>
<li><p>Si obtenemos evidencia suficiente de que <span class="math inline">\(H_0\)</span> es falsa, rechazaremos <span class="math inline">\(H_0\)</span> en favor de <span class="math inline">\(H_1\)</span> y concluiremos que <span class="math inline">\(H_1\)</span> es verdadera.</p>
<p>¿Qué quiere decir “obtener evidencia suficiente de que <span class="math inline">\(H_0\)</span> es falsa”? Pues que las pruebas obtenidas hacen que <span class="math inline">\(H_0\)</span> sea <strong>inverosímil</strong> (difícil de creer) por comparación con <span class="math inline">\(H_1\)</span>:</p>
<ul>
<li><p>Tendremos evidencia de que la moneda está trucada a favor de cara si en nuestra serie de lanzamientos la proporción de caras es tan grande que se nos hace muy difícil creer que la moneda sea equilibrada.</p></li>
<li><p>Tendremos evidencia de que A es más efectivo que B en la curación de X si en nuestro ensayo la tasa de curación de la enfermedad X con el tratamiento A es tan superior a la de B que se nos hace muy difícil creer que los dos tratamientos tengan la misma efectividad.</p></li>
</ul></li>
<li><p>Si no obtenemos evidencia suficiente de que <span class="math inline">\(H_0\)</span> es falsa, es decir, si nuestros datos son razonablemente compatibles con <span class="math inline">\(H_0\)</span>, no podremos rechazarla. Entonces, aceptaremos la hipótesis nula.</p>
<ul>
<li><p>Aceptaremos que la moneda no está trucada a favor de cara si en nuestra serie de lanzamientos la proporción de caras no es lo bastante grande como para hacernos dudar de que sea equilibrada</p></li>
<li><p>Aceptaremos que A es igual de efectivo que B en la curación de X si en nuestro ensayo la tasa de curación de la enfermedad X con el tratamiento A no es lo bastante superior a la de B como para hacernos dudar de que los dos tratamientos sean igual de efectivos.</p></li>
</ul></li>
</ul>

<div class="rmdrecordau">
Rechazamos la hipótesis nula en favor de la alternativa cuando sería mucha casualidad obtener los resultados obtenidos si la hipótesis nula fuera cierta en vez de la alternativa.
</div>

<div class="rmdcaution">
Si rechazamos <span class="math inline">\(H_0\)</span> en favor de <span class="math inline">\(H_1\)</span>, en general <strong>no</strong> será porque hayamos demostrado que <span class="math inline">\(H_0\)</span> sea imposible, ni siquiera que sea improbable: tan solo resultará difícil de creer a la vista de los resultados de nuestro experimento.
</div>
<p>Por ejemplo, si en una secuencia de 30 lanzamientos de una moneda obtenemos todas las veces cara, seguramente lo consideraremos evidencia de que la moneda está trucada, pero <strong>no demuestra que la moneda esté trucada</strong>. Sí, cuesta creer que no esté trucada, pero no es imposible: la moneda podría ser equilibrada y por puro azar nosotros haber tenido esta racha de caras. Y tampoco podemos decir que sea improbable que sea equilibrada, puesto que no sabemos calcular
<span class="math display">\[
P(\text{La moneda es equilibrada}\,|\,\text{30 caras en 30 lanzamientos}).
\]</span>
Lo que sabemos calcular es
<span class="math display">\[
P(\text{30 caras en 30 lanzamientos}\,|\,\text{La moneda es equilibrada})
\]</span>
que vale <span class="math inline">\(0.5^{30}=9.3\cdot 10^{-10}\)</span> (y por lo tanto, de media, aproximadamente en una de cada mil millones de veces que se efectúan 30 lanzamientos seguidos de una moneda equilibrada, se obtienen 30 caras: no es imposible).</p>

<div class="rmdcaution">
Si aceptamos la hipótesis nula es porque no encontramos motivos para dudar de ella, pero no habremos encontrado evidencia de que sea verdadera ni habremos demostrado que sea probable (y posible en principio lo es siempre).
</div>
<p>Por ejemplo, si en una secuencia de 4 lanzamientos de una moneda obtenemos 2 caras, tendremos que aceptar que la moneda es equilibrada. Pero podría ser que estuviera ligeramente sesgada hacia cara y no haberse notado en una secuencia tan corta de lanzamientos. Así que no hemos encontrado evidencia de que sea equilibrada, simplemente no lo podemos descartar (como tampoco podemos descartar que la probabilidad de cara sea, por ejemplo, 0.50001).</p>
<div class="example">
<p><span id="exm:juicio" class="example"><strong>Ejemplo 14.1  </strong></span>En un juicio (en el que el acusado es inocente si no se demuestra lo contrario) se busca evidencia suficiente de que el acusado es culpable. Por lo tanto, esta es la hipótesis alternativa. Por otro lado, que “no pase nada” significa que el acusado es inocente: casi todo el mundo es inocente del cargo concreto que se juzga en ese momento. Esta será la hipótesis nula. Por lo tanto, el contraste es:</p>
</div>
<p><span class="math display">\[
\left\{\begin{array}{ll}
H_{0}:\text{El acusado es inocente}\\
H_{1}:\text{El acusado es culpable}
\end{array}
\right.
\]</span>
En el juicio se aportan pruebas, y:</p>
<ul>
<li><p>Si el jurado las encuentra lo bastante incriminatorias, “más allá de toda duda razonable”, declara <strong>culpable</strong> el acusado (rechaza <span class="math inline">\(H_0\)</span> en favor de <span class="math inline">\(H_1\)</span>).</p></li>
<li><p>Si el jurado no las encuentra lo bastante incriminatorias, lo considera <strong>no culpable</strong> (no rechaza <span class="math inline">\(H_{0}\)</span>).</p></li>
</ul>
<p>Observad que considerar no culpable no es lo mismo que demostrar que es inocente: simplemente, se considera que el acusado no es culpable porque no se ha encontrado evidencia suficiente de que sea culpable.</p>
<div class="example">
<p><span id="exm:examen" class="example"><strong>Ejemplo 14.2  </strong></span>Un examen es un contraste de hipótesis. En este caso, “no pasa nada” significa que el estudiante es como si no hubiera ido al curso, no ha aprendido nada, y por lo tanto esta es la hipótesis nula. Con el examen buscamos evidencia de que el estudiante ha aprendido la materia, por lo tanto esta será la hipótesis alternativa. Así pues, el contraste es:</p>
</div>
<p><span class="math display">\[
\left\{\begin{array}{ll}
H_{0}:\text{El estudiante no sabe la materia}\\
H_{1}:\text{El estudiante sabe la materia}
\end{array}
\right.
\]</span>
Tomamos una muestra de los conocimientos del estudiante (el estudiante hace el examen), y:</p>
<ul>
<li><p>Si hay suficiente evidencia en favor de <span class="math inline">\(H_1\)</span> (si el examen le sale lo bastante bien), rechazamos <span class="math inline">\(H_0\)</span>: decidimos que el estudiante sabe la materia, aprueba la asignatura.</p></li>
<li><p>Si no hay evidencia suficiente en favor de <span class="math inline">\(H_1\)</span> (si el examen no le sale lo bastante bien), nos quedamos con <span class="math inline">\(H_0\)</span>: concluimos que el estudiante no ha aprendido la materia, suspende la asignatura.</p></li>
</ul>
<div class="example">
<p><span id="exm:CHdiag" class="example"><strong>Ejemplo 14.3  </strong></span>Una prueba diagnóstica de una enfermedad es un contraste de hipótesis. En este caso, “no pasa nada” significa que la persona no tiene la enfermedad, y por lo tanto esta es la hipótesis nula. Con la prueba diagnóstica buscamos evidencia de que tiene la enfermedad, por lo tanto esta será la hipótesis alternativa. Es decir, el contraste es</p>
</div>
<p><span class="math display">\[
\left\{\begin{array}{ll}
H_{0}:\text{La persona no tiene la enfermedad}\\
H_{1}:\text{La persona sí tiene la enfermedad}
\end{array}
\right.
\]</span></p>
<div class="example">
<p><span id="exm:esport1" class="example"><strong>Ejemplo 14.4  </strong></span>Si leemos la noticia siguiente en el diario, puede que nos preguntemos si es verdad que las mujeres practican menos deporte que los hombres.</p>
</div>
<p><img src="INREMDN_files/figure-html/mujeresdeporte.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Esta pregunta la podemos plantear de muchas maneras:</p>
<ul>
<li><p>¿Toda mujer hace cada día menos horas de deporte que cualquier hombre?</p></li>
<li><p>Si tomo una mujer y un hombre al azar, ¿es más probable que ella practique menos deporte que él?</p></li>
<li><p>¿La mayoría de las mujeres hacen cada día menos horas de deporte que la mayoría de los hombres?</p></li>
<li><p>¿La proporción de practicantes de deporte entre las mujeres es menor que entre los hombres?</p></li>
<li><p>¿La media semanal de veces que las mujeres practican deporte es menor que la de los hombres?</p></li>
<li><p>¿La media semanal de horas que las mujeres practican deporte es menor que la de los hombres?</p></li>
<li><p>…</p></li>
</ul>
<p>Cada una de estas preguntas se traduciría en un contraste de hipótesis diferente. Puesto que aquí estamos tratando contrastes sobre parámetros poblacionales (medias, proporciones, etc.), podríamos plantear alguno de los tres últimos contrastes. Vamos a centrarnos en la última cuestión, sobre medias semanales de horas de deporte.</p>
<p>En este contraste, las variables poblacionales de interés son:</p>
<ul>
<li><p><span class="math inline">\(X_m\)</span>: “Tomo una mujer y calculo su número medio de horas semanales de deporte”, con media <span class="math inline">\(\mu_m\)</span>: la media semanal de horas de deporte de las mujeres (la media de las medias de horas semanales de deporte de todas las mujeres es la media de horas semanales de deporte de las mujeres).</p></li>
<li><p><span class="math inline">\(X_h\)</span>: “Tomo un hombre y calculo su número medio de horas semanales de deporte”, con media <span class="math inline">\(\mu_h\)</span>: la media semanal de horas de deporte de los hombres.</p></li>
</ul>
<p>El contraste que queremos realizar es</p>
<ul>
<li><p><strong>Hipótesis nula</strong>: no hay diferencia entre las medias semanales de horas de deporte de hombres y mujeres.</p></li>
<li><p><strong>Hipótesis alternativa</strong>: la media semanal de horas de deporte de las mujeres es menor que la de los hombres.</p></li>
</ul>
<p>Es decir
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}: \mu_m=\mu_h\\
H_{1}:\mu_m&lt;\mu_h
\end{array}
\right.
\]</span></p>
<p>El procedimiento para llevar a cabo este contraste sería:</p>
<ul>
<li><p>Tomaríamos muestras aleatorias de mujeres y de hombres y les preguntaríamos sus hábitos de práctica de deporte.</p></li>
<li><p>Calcularíamos la media muestral <span class="math inline">\(\overline{X}_m\)</span> de horas semanales de deporte de las mujeres de la muestra.</p></li>
<li><p>Calcularíamos la media muestral <span class="math inline">\(\overline{X}_h\)</span> de horas semanales de deporte de los hombres de la muestra.</p></li>
<li><p>Si <span class="math inline">\(\overline{X}_m\)</span> fuera mucho menor que <span class="math inline">\(\overline{X}_h\)</span>, lo tomaríamos como evidencia de que <span class="math inline">\(\mu_m&lt;\mu_h\)</span>.</p></li>
<li><p>Si <span class="math inline">\(\overline{X}_m\)</span> no fuera mucho menor que <span class="math inline">\(\overline{X}_h\)</span>, no podríamos rechazar que <span class="math inline">\(\mu_m=\mu_h\)</span>.</p></li>
</ul>
<p>¿Qué significa “<span class="math inline">\(\overline{X}_m\)</span> mucho menor que <span class="math inline">\(\overline{X}_h\)</span>”? Una opción, que podríamos importar del tema anterior, seria calcular un intervalo de confianza del 95% para <span class="math inline">\(\mu_m-\mu_h\)</span> a partir de la muestra. Entonces:</p>
<ul>
<li><p>Si este intervalo de confianza estuviera totalmente a la izquierda del 0, con un 95% de confianza podríamos concluir que <span class="math inline">\(\mu_m&lt;\mu_h\)</span> (porque tendríamos un 95% de seguridad de que el valor real de la diferencia <span class="math inline">\(\mu_m-\mu_h\)</span> pertenece a un intervalo de números estrictamente negativos).</p></li>
<li><p>En caso contrario (si contuviera el 0 o si estuviera totalmente a la derecha del 0), con un 95% de confianza no podríamos concluir que <span class="math inline">\(\mu_m&lt;\mu_h\)</span>.</p></li>
</ul>
<p>Aquí querremos afinar un poco más que lo del “nivel de confianza”, por lo que el procedimiento será algo más complicado. Básicamente, la idea es que vamos a usar diferentes fórmulas para calcular los intervalos de confianza según la forma de la hipótesis alternativa, ya lo veremos.</p>
<p>Antes de cerrar esta sección, queremos destacar algunas advertencias.</p>

<div class="rmdcaution">
Las hipótesis de los contrastes son sobre parámetros de las poblaciones, NO sobre estadísticos de las muestras.
</div>
<p>En el ejemplo anterior, las hipótesis del contraste comparaban las <strong>medias poblacionales</strong> de horas semanales de deporte de las mujeres y los hombres, no las medias de horas semanales de deporte de las mujeres y los hombres de la muestra.</p>
<p>Para comparar las medias muestrales no nos hace falta un contraste de hipótesis: las calculamos y punto. En cambio, como no podemos calcular las medias semanales de horas de deporte de todas las mujeres y de todos los hombres, nos vemos obligados a hacer un contraste de hipótesis.</p>

<div class="rmdcaution">
La falta de evidencia en favor de <span class="math inline">\(H_1\)</span> no es evidencia en favor de <span class="math inline">\(H_0\)</span>.
</div>
<p>Si no podemos asegurar que las mujeres practiquen menos deporte que los hombres (porque no hayamos encontrado evidencia a favor de esta hipótesis), esto no significará que hayamos encontrado evidencia de que los hombres y las mujeres practiquen la misma cantidad de deporte o de que las mujeres practiquen más deporte. Lo que significará es que la evidencia en favor de <span class="math inline">\(H_1\)</span> <strong>no ha sido lo bastante contundente como para poder concluir que esta es la hipótesis verdadera</strong> y por lo tanto aceptamos que no hay diferencia en la media semanal de horas de deporte de ambos sexos.</p>

<div class="rmdcaution">
De hecho, (casi) nunca podremos encontrar evidencia de la hipótesis nula.
</div>
<p>Si por ejemplo en nuestro estudio hubiéramos encontrado que <span class="math inline">\(\overline{X}_m=\overline{X}_h\)</span>, esto sería compatible con la hipótesis nula <span class="math inline">\(\mu_m=\mu_h\)</span>, y por eso no la podríamos rechazar. Pero no aportaría evidencia de que <span class="math inline">\(\mu_m=\mu_h\)</span>, puesto que seguramente también sería compatible, por ejemplo, con <span class="math inline">\(\mu_m=\mu_h+0.0007\)</span> (las mujeres hacen, de media, un minuto más de deporte a la semana que los hombres) y por lo tanto, si “ser compatible” fuera lo mismo que “aportar evidencia”, nuestros datos aportarían evidencia de que dos hipótesis que se contradicen son verdaderas.</p>

<div class="rmdcaution">
La pregunta (el contraste) se plantea <em>a priori</em> a partir de hipótesis o suposiciones previas, antes de obtener los datos. No vale cambiar de contraste a la vista de los datos obtenidos.
</div>
<p>Tenemos que plantear la pregunta antes de recoger la muestra. Si estamos interesados en el contraste
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}: \mu_m=\mu_h\\
H_{1}:\mu_m&lt;\mu_h
\end{array}
\right.
\]</span>
y obtenemos que <span class="math inline">\(\overline{X}_m\)</span> es mucho mayor que <span class="math inline">\(\overline{X}_h\)</span> en nuestra muestra, concluimos que no tenemos evidencia de que <span class="math inline">\(\mu_m&lt;\mu_h\)</span> y punto. <strong>Sería hacer trampas</strong> decir: “No hemos encontrado evidencia de que las mujeres practiquen menos deporte que los hombres, pero si con estos mismos datos realizamos el contraste
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}: \mu_m=\mu_h\\
H_{1}:\mu_m&gt;\mu_h
\end{array}
\right.
\]</span>
sí que obtenemos evidencia de que ellas practican más deporte que ellos.”</p>
<p>De esto se dice <strong>ir a pescar evidencias</strong> o también <strong>torturar los datos</strong>: obtener unos datos y buscar de qué dan evidencia. Es mala praxis científica. Cualquier conjunto de datos, si lo torturamos lo suficiente, acaba dando evidencia de algo.</p>

<div class="rmdcaution">
Escoged la hipótesis alternativa en función de lo que buscáis evidencia.
</div>
<p>No confundáis
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}: \mu_m=\mu_h\\
H_{1}:\mu_m&lt;\mu_h
\end{array}
\right.
\]</span>
con
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}: \mu_m=\mu_h\\
H_{1}:\mu_m \neq \mu_h
\end{array}
\right.
\]</span>
que traduce la pregunta “Los hombres y las mujeres, ¿practican deporte un número diferente de horas a la semana, de media?”</p>

<div class="rmdimportant">
<p><strong>Reglas para elegir <span class="math inline">\(H_0\)</span> y <span class="math inline">\(H_1\)</span> en este curso</strong>:</p>
<ul>
<li><p><span class="math inline">\(H_0\)</span> siempre se tiene que definir mediante una igualdad.</p></li>
<li><p><span class="math inline">\(H_1\)</span> es la hipótesis de la que buscamos evidencia, y se tiene que definir mediante algo “estricto”:</p>
<ul>
<li><p><strong>Hipótesis unilateral</strong> (<em>one-sided</em>; también <strong>de una cola</strong>, <em>one-tailed</em>): definida con <strong>&lt;</strong> o con <strong>&gt;</strong>.</p></li>
<li><p><strong>Hipótesis bilateral</strong> (<em>two-sided</em>; también <strong>de dos colas</strong>, <em>two-tailed</em>): definida con <span class="math inline">\(\mathbf{\neq}\)</span>.</p>
</div></li>
</ul></li>
</ul>
<p>Los contrastes toman el nombre del tipo de hipótesis alternativa: <strong>contraste unilateral</strong>, <strong>contraste de dos colas</strong>, etc.</p>
</div>
<div id="sec:moneda" class="section level2 hasAnchor" number="14.2">
<h2><span class="header-section-number">14.2</span> Un ejemplo<a href="contrastes-de-hipótesis.html#sec:moneda" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Tenemos una moneda, y creemos que está trucada en favor de cara. Queremos contrastarlo.</p>
<p>Aquí la variable aleatoria <span class="math inline">\(X\)</span> que nos interesa es “lanzamos la moneda y miramos si sale cara”, que es de Bernoulli con probabilidad de éxito (es decir, probabilidad de sacar cara con nuestra moneda) <span class="math inline">\(p_{\mathit{Cara}}\)</span>.</p>
<p>La hipótesis nula será que la moneda no está trucada (no le pasa nada a nuestra moneda), y la alternativa que la moneda está trucada en favor de cara. En términos de <span class="math inline">\(p_{\mathit{Cara}}\)</span>, el contraste es
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}:p_{\mathit{Cara}}= 0.5\\
H_{1}:p_{\mathit{Cara}}&gt; 0.5
\end{array}
\right.
\]</span></p>
<div class="example">
<p><span id="exm:unnamed-chunk-548" class="example"><strong>Ejemplo 14.5  </strong></span>Supongamos que lanzamos la moneda 3 veces y obtenemos 3 caras. ¿Es evidencia suficiente de que está trucada a favor de cara?</p>
</div>
<p>Llamemos <span class="math inline">\(S_3\)</span> a la variable aleatoria “Número de caras en 3 lanzamientos de esta moneda.” Si la moneda no está trucada, <span class="math inline">\(S_3\)</span> es binomial <span class="math inline">\(B(3,0.5)\)</span>, y por lo tanto
<span class="math display">\[
P(S_3=3)=0.5^{3}=0.125.
\]</span></p>
<p>El resultado obtenido no es muy improbable con una moneda equilibrada: pasa, de media, en 1 de cada 8 secuencias de 3 lanzamientos. Por lo tanto, no vamos a considerarlo evidencia suficiente de que la moneda esté trucada. Aceptamos que la moneda es equilibrada.</p>

<div class="rmdrecordau">
A este tipo de procedimiento, usar la distribución binomial del número de éxitos en una muestra aleatoria simple de una variable aleatoria de Bernoulli para contrastar un valor de su probabilidad poblacional de éxito, lo llamaremos un <strong>test binomial</strong>.
</div>
<div class="example">
<p><span id="exm:unnamed-chunk-550" class="example"><strong>Ejemplo 14.6  </strong></span>Supongamos que ahora lanzamos la moneda 10 veces y obtenemos 10 caras. ¿Es evidencia suficiente de que está trucada a favor de cara?</p>
</div>
<p>Llamemos <span class="math inline">\(S_{10}\)</span> a la variable aleatoria “Número de caras en 10 lanzamientos.” Si la moneda no está trucada, <span class="math inline">\(S_{10}\)</span> es <span class="math inline">\(B(10,0.5)\)</span> y por lo tanto
<span class="math display">\[
P(S_{10}=10)=0.5^{10}=0.001
\]</span></p>
<p>El resultado obtenido es bastante improbable si la moneda no está trucada: si la moneda fuera equilibrada, de media solo en 1 de cada 1000 secuencias de 10 lanzamientos obtendríamos 10 caras. Es decir:</p>
<blockquote>
<p>El resultado de nuestro experimento sería muy raro si la moneda fuera equilibrada, lo que nos hace dudar de que sea equilibrada.</p>
</blockquote>
<p>Lo consideramos evidencia de que está trucada.</p>

<div class="rmdnote">
<p>Observad el razonamiento que hemos efectuado. Tenemos una hipótesis nula y una alternativa, realizamos un experimento y obtenemos un resultado que es muy improbable si la hipótesis nula es verdadera. Una de dos:</p>
<ul>
<li>O la hipótesis nula es falsa.</li>
<li>O la hipótesis nula es verdadera y ha pasado algo muy raro.</li>
</ul>
¿Qué es lo más sensato concluir? Teniendo en cuenta que las cosas muy raras no suelen pasar, lo más sensato es concluir que la hipótesis nula es falsa.
</div>
<p>El procedimiento que hemos seguido en los dos ejemplos anteriores ha sido el siguiente:</p>
<ol style="list-style-type: decimal">
<li><p>Hemos planteado el contraste:
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}:p_{\mathit{Cara}}= 0.5\\
H_{1}:p_{\mathit{Cara}}&gt; 0.5
\end{array}
\right.
\]</span></p></li>
<li><p>Hemos recogido una muestra aleatoria simple de valores: la secuencia de lanzamientos.</p></li>
<li><p>Hemos elegido un <strong>estadístico de contraste</strong> con distribución de probabilidades conocida cuando <span class="math inline">\(H_0\)</span> es verdadera: en nuestro caso, el número de caras.</p></li>
<li><p>Hemos calculado el valor de este estadístico sobre nuestra muestra.</p></li>
<li><p>Hemos calculado la probabilidad de que el estadístico tome el valor observado si <span class="math inline">\(H_0\)</span> es verdadera.</p></li>
<li><p>Si esta probabilidad es muy pequeña, lo tomamos como evidencia de que <span class="math inline">\(H_1\)</span> es verdadera.</p></li>
<li><p>Si no es lo bastante pequeña, no consideramos que hayamos obtenido evidencia de que <span class="math inline">\(H_0\)</span> sea falsa y <span class="math inline">\(H_1\)</span> verdadera.</p></li>
</ol>
<p>Bien, esto es lo que hemos hecho, pero no es del todo correcto. En los puntos (5) y (6) decimos que: “Calculamos la probabilidad de que el estadístico tome el valor observado si <span class="math inline">\(H_0\)</span> es verdadera y si es muy pequeña, lo consideramos evidencia de que <span class="math inline">\(H_1\)</span> es verdadera.” ¿Seguro que queremos hacer esto?</p>
<ul>
<li><p>Supongamos que, en el contraste anterior, lanzamos la moneda 10 veces y obtenemos 10 <strong>cruces</strong>. ¿Es evidencia suficiente de que está trucada en favor de cara? Obviamente no lo puede ser, pero la probabilidad es la misma que antes:
<span class="math display">\[
P(S_{10}=0)=0.5^{10}=0.001
\]</span></p></li>
<li><p>En muchos casos, <strong>la probabilidad de obtener exactamente lo que hemos obtenido puede ser muy pequeña, independientemente de lo que hayamos obtenido</strong>. Por ejemplo, supongamos que lanzamos la moneda 10000 veces y obtenemos 5000 caras. Si la moneda es equilibrada, el número de caras seguirá una distribución binomial <span class="math inline">\(B(10000,0.5)\)</span> y la probabilidad de obtener 5000 caras será
<span class="math display">\[
\binom{10000}{5000}0.5^{10000}=0.008
\]</span>
muy pequeña, pero está claro que si la mitad de lanzamientos dan cara, no se puede considerar evidencia de que la moneda esté trucada.</p>
<p>O, más exagerado aún, si el estadístico de contraste es una variable continua, la probabilidad de que tome un valor concreto, el que sea, es 0 por definición. Más pequeño imposible, pero no siempre rechazaremos la hipótesis nula.</p></li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-552"></span>
<img src="https://imgs.xkcd.com/comics/null_hypothesis.png" alt="&quot;Null hypothesis&quot; (https://xkcd.com/892/ (CC-BI-NC 2.5))" width="40%" />
<p class="caption">
Figura 14.1: “Null hypothesis” (<a href="https://xkcd.com/892/" class="uri">https://xkcd.com/892/</a> (CC-BI-NC 2.5))
</p>
</div>
<p>Así que:</p>

<div class="rmdrecordau">
En realidad, en (5) se calcula la probabilidad de que, si <span class="math inline">\(H_0\)</span> es verdadera, el estadístico tome un valor tan extremo o más, en el sentido de <span class="math inline">\(H_1\)</span>, que el obtenido. A esta probabilidad la llamamos el <strong>p-valor</strong>.
</div>
<p>En nuestro ejemplo de la moneda, como la hipótesis nula es <span class="math inline">\(p_{\mathit{Cara}}= 0.5\)</span> y la hipótesis alternativa es <span class="math inline">\(p_{\mathit{Cara}}&gt; 0.5\)</span>, el p-valor es la probabilidad de que, si <span class="math inline">\(p_{\mathit{Cara}}= 0.5\)</span>, el número de caras sea mayor o igual que el obtenido en nuestra muestra.</p>
<p>En los dos ejemplos anteriores concretos, donde obteníamos 3 caras en 3 lanzamientos y 10 caras en 10 lanzamientos, era lo mismo pedir que el número de caras fuera igual al obtenido y pedir que el número de caras fuera mayor o igual que el obtenido, porque en los dos experimentos hemos obtenido el número máximo posible de caras; por ejemplo, sacar 3 o más caras en 3 lanzamientos es exactamente lo mismo que sacar 3 caras en 3 lanzamientos. Pero en general esto no será así.</p>
<div class="example">
<p><span id="exm:unnamed-chunk-554" class="example"><strong>Ejemplo 14.7  </strong></span>Volvamos a nuestro contraste
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}:p_{\mathit{Cara}}= 0.5\\
H_{1}:p_{\mathit{Cara}}&gt; 0.5
\end{array}
\right.
\]</span>
Supongamos que lanzamos la moneda 10 veces y obtenemos 7 caras. ¿Es evidencia suficiente de que está trucada a favor de cara?</p>
</div>
<p>Seguimos llamando <span class="math inline">\(S_{10}\)</span> a la variable aleatoria “Número de caras en 10 lanzamientos”. Si la moneda no está trucada, <span class="math inline">\(S_{10}\)</span> es <span class="math inline">\(B(10,0.5)\)</span>. Como la hipótesis alternativa es <span class="math inline">\(p_{\mathit{Cara}}&gt; 0.5\)</span>, “obtener un número de caras tan extremo o más que el que hemos obtenido en el sentido de la hipótesis alternativa” es sacar <strong>tantas caras como las que hemos obtenido o más</strong>, es decir sacar 7 o más caras. Por lo tanto
<span class="math display">\[
\text{p-valor}=P(S_{10}\geqslant 7)=0.172
\]</span></p>
<p>Un número de caras igual o superior al obtenido no es muy improbable si la moneda no está trucada: pasaría en 1 de cada 6 secuencias de 10 lanzamientos. Por lo tanto, como es bastante compatible con el equilibrio de la moneda, no lo podemos considerar evidencia de que esté trucada a favor de cara.</p>
<div class="example">
<p><span id="exm:unnamed-chunk-555" class="example"><strong>Ejemplo 14.8  </strong></span>Tenemos una moneda, y ahora creemos que está trucada a favor de cruz. Queremos contrastarlo. Planteado en términos de <span class="math inline">\(p_{\mathit{Cara}}\)</span>, el contraste que queremos realizar es
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}:p_{\mathit{Cara}}= 0.5\\
H_{1}: p_{\mathit{Cara}}&lt; 0.5
\end{array}
\right.
\]</span>
Imaginad que lanzamos la moneda 10 veces y obtenemos 1 cara. ¿Es suficiente evidencia de que <span class="math inline">\(p_{\mathit{Cara}}&lt; 0.5\)</span>?</p>
</div>
<p>Seguimos llamando <span class="math inline">\(S_{10}\)</span> a la variable aleatoria “Número de caras en 10 lanzamientos de esta moneda.” Si la moneda no está trucada, <span class="math inline">\(S_{10}\)</span> es <span class="math inline">\(B(10,0.5)\)</span>.</p>
<p>Ahora, como <span class="math inline">\(H_{1}\)</span> es <span class="math inline">\(p_{\mathit{Cara}}&lt; 0.5\)</span>, “obtener un número de caras tan extremo o más que el que hemos obtenido, en el sentido de la hipótesis alternativa” es sacar tantas caras como las que hemos obtenido <strong>o menos</strong>, es decir sacar como máximo 1 cara. Por lo tanto
<span class="math display">\[
\text{p-valor}=P(S_{10}\leqslant 1)=0.01
\]</span>
Un resultado tan o más extremo como el obtenido es muy improbable si <span class="math inline">\(p_{\mathit{Cara}}= 0.5\)</span>: de media, solo ocurre en 1 de cada 100 secuencias de 10 lanzamientos. Lo podemos considerar evidencia de que la moneda sí que está trucada en favor de cruz.</p>
</div>
<div id="sec:pval" class="section level2 hasAnchor" number="14.3">
<h2><span class="header-section-number">14.3</span> El p-valor<a href="contrastes-de-hipótesis.html#sec:pval" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El <strong>p-valor</strong> de un contraste es la probabilidad de que, si la hipótesis nula es verdadera, el estadístico de contraste tome en una muestra aleatoria simple del mismo tamaño que la nuestra un valor tan o más extremo, en el sentido de la hipótesis alternativa, que el obtenido con la muestra usada para realizar el contraste.</p>
<p>Lo repetimos, poniendo énfasis en los componentes fundamentales de la definición. El <strong>p-valor</strong> es:</p>
<ul>
<li>La probabilidad de que,</li>
<li>si la hipótesis nula es verdadera,</li>
<li>el estadístico de contraste tome en una muestra aleatoria simple del mismo tamaño que la nuestra</li>
<li>un valor tan o más extremo, en el sentido de la hipótesis alternativa,</li>
<li>que el obtenido con nuestra muestra.</li>
</ul>
<div class="example">
<p><span id="exm:unnamed-chunk-556" class="example"><strong>Ejemplo 14.9  </strong></span>Supongamos que en el contraste de las medias semanales de horas de deporte de hombres y mujeres del Ejemplo <a href="contrastes-de-hipótesis.html#exm:esport1">14.4</a> usamos como estadístico de contraste la diferencia entre las medias muestrales <span class="math inline">\(\overline{X}_m-\overline{X}_h\)</span> (no será así: ¡solo es un ejemplo!), que hemos tomado muestras de 50 mujeres y de 50 hombres, y que la diferencia de medias muestrales ha sido -1.2. Entonces, el p-valor del contraste es</p>
</div>
<ul>
<li><p>La probabilidad de que,</p></li>
<li><p>si la hipótesis nula es verdadera,</p>
<p>si <span class="math inline">\(\mu_m=\mu_h\)</span>, es decir, si los hombres y las mujeres practican de media el mismo número de horas de deporte a la semana,</p></li>
<li><p>el estadístico de contraste tome en una muestra aleatoria simple del mismo tamaño que la nuestra</p>
<p>el valor de <span class="math inline">\(\overline{X}_m-\overline{X}_h\)</span>, es decir, de la diferencia entre las medias muestrales de horas semanales de deporte en las mujeres y en los hombres, en una muestra aleatoria formada por 50 mujeres y 50 hombres, sea</p></li>
<li><p>un valor tan o más extremo, en el sentido de la hipótesis alternativa,</p>
<p><strong>menor o igual</strong> (porque la hipótesis alternativa es <span class="math inline">\(\mu_m&lt;\mu_h\)</span>, es decir <span class="math inline">\(\mu_m-\mu_h&lt;0\)</span>)</p></li>
<li><p>que el obtenido con nuestra muestra.</p>
<p>que el de nuestra muestra, -1.2.</p></li>
</ul>
<p>En resumen, el p-valor seria en este caso</p>
<blockquote>
<p>La probabilidad de que, si <span class="math inline">\(\mu_m=\mu_h\)</span>, el valor de <span class="math inline">\(\overline{X}_m-\overline{X}_h\)</span> en una muestra aleatoria de 50 mujeres y 50 hombres sea menor o igual que -1.2.</p>
</blockquote>
<p>Si esta probabilidad es muy pequeña, la muestra obtenida es poco consistente con la hipótesis nula y por lo tanto concluiremos que la hipótesis alternativa es verdadera. Si, en cambio, esta probabilidad no es muy pequeña, la muestra obtenida es consistente con la hipótesis nula y por lo tanto no podremos rechazar que <span class="math inline">\(H_0\)</span> sea verdadera.</p>

<div class="rmdimportant">
<p>El p-valor <strong>NO</strong> es:</p>
<ul>
<li><p>La probabilidad de que <span class="math inline">\(H_0\)</span> sea verdadera condicionada a nuestro resultado.</p></li>
<li><p>La probabilidad de que <span class="math inline">\(H_1\)</span> sea falsa condicionada a nuestro resultado.</p></li>
</ul>
</div>
<p>Es al revés: El p-valor es la probabilidad de nuestro resultado (o uno más extremo) condicionada a que <span class="math inline">\(H_0\)</span> sea verdadera. Por lo tanto, el p-valor es una evidencia <strong>indirecta inversa</strong> de <span class="math inline">\(H_1\)</span>:</p>
<blockquote>
<p>Cuanto menor sea el p-valor, más raro sería lo que hemos obtenido si <span class="math inline">\(H_0\)</span> fuera verdadera y <span class="math inline">\(H_1\)</span> falsa, y por lo tanto más evidencia aporta de que <span class="math inline">\(H_0\)</span> no puede ser verdadera y de que la verdadera es <span class="math inline">\(H_1\)</span>.</p>
</blockquote>
<p>Por ejemplo, si el p-valor de un contraste es 0.03:</p>
<ul>
<li><p><strong>Significa</strong> que, si <span class="math inline">\(H_0\)</span> fuera verdadera, el estadístico de contraste valdría en 3 de cada 100 muestras algo al menos tan extremo, en el sentido de <span class="math inline">\(H_1\)</span>, como lo que hemos obtenido.</p>
<ul>
<li><p><strong>¿Lo encontráis poco?</strong> Lo tomáis como evidencia de que <span class="math inline">\(H_0\)</span> es falsa y <span class="math inline">\(H_1\)</span> verdadera.</p></li>
<li><p><strong>¿No lo encontráis poco?</strong> No tenéis evidencia para rechazar que <span class="math inline">\(H_0\)</span> sea verdadera.</p></li>
</ul></li>
<li><p>Pero <strong>no significa</strong> que:</p>
<ul>
<li><p>La probabilidad de que <span class="math inline">\(H_0\)</span> sea verdadera es 0.03.</p></li>
<li><p><span class="math inline">\(H_0\)</span> es verdadera un 3% de las veces.</p></li>
</ul></li>
</ul>

<div class="rmdimportant">
En un contraste de hipótesis no obtenemos ninguna información directa sobre la probabilidad de <span class="math inline">\(H_0\)</span> o de <span class="math inline">\(H_1\)</span>.
</div>
<div class="example">
<p><span id="exm:unnamed-chunk-559" class="example"><strong>Ejemplo 14.10  </strong></span>Tenemos una moneda y nos preguntamos si está trucada; a favor de cara o a favor de cruz, nos da igual, solo si está trucada o es equilibrada.</p>
</div>
<p>Planteado en términos de la probabilidad de sacar cara <span class="math inline">\(p_{\mathit{Cara}}\)</span>, el contraste que queremos realizar ahora es
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}:p_{\mathit{Cara}}= 0.5\\
H_{1}:p_{\mathit{Cara}}\neq 0.5
\end{array}
\right.
\]</span>
Supongamos que la lanzamos 10 veces y obtenemos 9 caras. ¿Es evidencia suficiente de que está trucada?</p>
<p>Como en la sección anterior, sea <span class="math inline">\(S_{10}\)</span> la variable “Número de caras en 10 lanzamientos”. Si <span class="math inline">\(p_{\mathit{Cara}}= 0.5\)</span>, <span class="math inline">\(S_{10}\)</span> es <span class="math inline">\(B(10,0.5)\)</span>.</p>
<p>Si la hipótesis nula fuera verdadera, esperaríamos sacar 5 caras y 5 cruces. Como la hipótesis alternativa es <span class="math inline">\(H_{1}:p_{\mathit{Cara}}\neq 0.5\)</span>, ahora “obtener un resultado tan o más extremo, en el sentido de la hipótesis alternativa, que el obtenido” es <strong>sacar un resultado que se aleje tanto, o más, de 5 caras y 5 cruces como el que hemos obtenido</strong>. Es decir, sacar al menos 9 caras o al menos 9 cruces, o lo que es el mismo, sacar o bien 9 o más caras, o bien 1 o menos caras. Por lo tanto, el p-valor es
<span class="math display">\[
\begin{array}{l}
P(S_{10}\geqslant 9\text{ o }S_{10}\leqslant 1) =P(S_{10}\geqslant 9) + P(S_{10}\leqslant 1)\\
\qquad = 0.0107+0.0107=0.0214
\end{array}
\]</span></p>
<p>Por lo tanto, si la moneda no estuviera trucada, un resultado tan alejado de “mitad caras, mitad cruces” como el nuestro se obtendría en alrededor de 1 de cada 50 secuencias de 10 lanzamientos. ¿Es evidencia suficiente de que esté trucada?</p>
<p>La respuesta corta es que seguramente sí. La respuesta larga es que depende de cuánto estemos dispuestos a arriesgarnos a rechazar la hipótesis nula cuando es verdadera.</p>
</div>
<div id="tipo-de-errores" class="section level2 hasAnchor" number="14.4">
<h2><span class="header-section-number">14.4</span> Tipo de errores<a href="contrastes-de-hipótesis.html#tipo-de-errores" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La comparación entre la realidad y la conclusión de un contraste da lugar a cuatro situaciones posibles, resumidas en la tabla siguiente:</p>
<p><img src="INREMDN_files/figure-html/errors.png" width="75%" style="display: block; margin: auto;" /></p>
<ul>
<li><p>Si <span class="math inline">\(H_0\)</span> es la hipótesis verdadera en la realidad y nosotros decidimos que <span class="math inline">\(H_1\)</span> es verdadera:</p>
<ul>
<li><p>La conclusión del contraste es errónea. Lo llamaremos un <strong>error de tipo I</strong>, <strong>error <span class="math inline">\(\alpha\)</span></strong> o <strong>falso positivo</strong>.</p></li>
<li><p>Denotaremos por <span class="math inline">\(\alpha\)</span> la probabilidad de cometer un error de tipo I, es decir, de rechazar <span class="math inline">\(H_0\)</span> si es verdadera, y la llamaremos el <strong>nivel de significación</strong>:
<span class="math display">\[
\alpha=P(\text{Rechazar } H_0\,|\, H_0\text{ verdadera}).
\]</span></p></li>
</ul></li>
<li><p>Si <span class="math inline">\(H_1\)</span> es la hipótesis verdadera en la realidad y nosotros aceptamos <span class="math inline">\(H_0\)</span>:</p>
<ul>
<li><p>La conclusión del contraste es errónea. Lo llamaremos un <strong>error de tipo II</strong>, <strong>error <span class="math inline">\(\beta\)</span></strong> o <strong>falso negativo</strong>.</p></li>
<li><p>Denotaremos por <span class="math inline">\(\beta\)</span> la probabilidad de cometer un error de tipo II, es decir, de aceptar <span class="math inline">\(H_0\)</span> si <span class="math inline">\(H_1\)</span> es verdadera:
<span class="math display">\[
\beta=P(\text{Aceptar } H_0\,|\, H_1\text{ verdadera}).
\]</span></p></li>
</ul></li>
<li><p>Si <span class="math inline">\(H_1\)</span> es la hipótesis verdadera en la realidad y nosotros decidimos rechazar <span class="math inline">\(H_0\)</span> en favor de <span class="math inline">\(H_1\)</span>:</p>
<ul>
<li><p>La conclusión del contraste es correcta. Lo llamaremos un <strong>verdadero positivo</strong>.</p></li>
<li><p>La probabilidad de acertar con un verdadero positivo es <span class="math inline">\(1-\beta\)</span> y la llamaremos la <strong>potencia</strong>:</p></li>
</ul></li>
</ul>
<p><span class="math display">\[
1-\beta=P(\text{Rechazar } H_0\,|\, H_1\text{ verdadera}).
\]</span></p>
<ul>
<li><p>Si <span class="math inline">\(H_0\)</span> es la hipótesis verdadera en la realidad y nosotros la aceptamos:</p>
<ul>
<li><p>La conclusión del contraste es correcta. Lo llamaremos un <strong>verdadero negativo</strong>.</p></li>
<li><p>La probabilidad de acertar con un verdadero negativo es <span class="math inline">\(1-\alpha\)</span> y la llamaremos el <strong>nivel de confianza</strong>:
<span class="math display">\[
1-\alpha=P(\text{Aceptar } H_0\,|\, H_0\text{ verdadera}).
\]</span></p></li>
</ul></li>
</ul>

<div class="rmdrecordau">
<p>En el contexto de un contraste de hipótesis,</p>
<ul>
<li><p>Un <strong>resultado positivo</strong> es rechazar la hipótesis nula y decidir que la alternativa es la verdadera (hemos encontrado algo).</p></li>
<li><p>Un <strong>resultado negativo</strong> es aceptar la hipótesis nula (no hemos encontrado nada y nos quedamos con la hipótesis nula).</p></li>
</ul>
</div>
<p>Repetimos:</p>
<ul>
<li><p>El <strong>nivel de significación</strong> de un contraste es la probabilidad de que, <strong>si la hipótesis nula es verdadera</strong>, nosotros nos equivoquemos y la rechacemos en favor de la alternativa:
<span class="math display">\[
\alpha=P(\text{Rechazar } H_0\,|\, H_0\text{ verdadera}).
\]</span></p></li>
<li><p>La <strong>potencia</strong> de un contraste es la probabilidad de que, <strong>si la hipótesis alternativa es verdadera</strong>, nosotros lo detectemos y rechacemos la hipótesis nula en favor de la alternativa:
<span class="math display">\[
1-\beta=P(\text{Rechazar } H_0\,|\, H_1\text{ verdadera}).
\]</span></p></li>
</ul>
<div class="example">
<p><span id="exm:unnamed-chunk-562" class="example"><strong>Ejemplo 14.11  </strong></span>En un test de embarazo, el contraste que se realiza es:
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}:\text{No estás embarazada}\\
H_{1}:\text{Estás embarazada}
\end{array}
\right.
\]</span></p>
</div>
<p><img src="INREMDN_files/figure-html/types.png" width="60%" style="display: block; margin: auto;" /></p>
<div class="example">
<p><span id="exm:unnamed-chunk-564" class="example"><strong>Ejemplo 14.12  </strong></span>En un juicio, donde se tiene que declarar un acusado inocente o culpable, el contraste era
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}:\text{El acusado es inocente}\\
H_{1}:\text{El acusado es culpable}
\end{array}
\right.
\]</span></p>
</div>
<p>Se pueden cometer dos errores:</p>
<ul>
<li><p><strong>Error de tipo I</strong>: Declarar culpable a un inocente.</p></li>
<li><p><strong>Error de tipo II</strong>: Declarar inocente a un culpable.</p></li>
</ul>
<p>Es peor el error de tipo I, conviene minimizar la probabilidad de cometerlo. Por eso solo se declara a alguien culpable cuando las pruebas “lo demuestran más allá de toda duda razonable”.</p>
<div class="example">
<p><span id="exm:unnamed-chunk-565" class="example"><strong>Ejemplo 14.13  </strong></span>En un examen, el contraste era
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}:\text{El estudiante no sabe la materia}\\
H_{1}:\text{El estudiante sabe la materia}
\end{array}
\right.
\]</span></p>
</div>
<p>Los errores que pueden darse son:</p>
<ul>
<li><p>Que apruebe un estudiante que no sabe la materia</p></li>
<li><p>Que suspenda un estudiante que sí sabe la materia</p></li>
</ul>

<div class="rmdexercici">
¿Cuál es el de tipo I y cuál el de tipo II? ¿Cuál creéis que es peor?
</div>

<div class="rmdexercici">
Recordad la interpretación de una prueba diagnóstica como un contraste de hipótesis (Ejemplo <a href="contrastes-de-hipótesis.html#exm:CHdiag">14.3</a>). Interpretad su especificidad y sensibilidad en términos de <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(\beta\)</span>.
</div>
<p>Normalmente, se considera peor cometer un error de tipo I que cometer un error de tipo II. Por lo tanto, el objetivo primario en un contraste es encontrar una regla de decisión que tenga poca probabilidad <span class="math inline">\(\alpha\)</span> de error de tipo I. Pero también querríamos minimizar la probabilidad <span class="math inline">\(\beta\)</span> de error de tipo II.
El problema es que cuando hacemos que <span class="math inline">\(\alpha\)</span> disminuya, <span class="math inline">\(\beta\)</span> suele aumentar, porque al hacer más difícil rechazar la hipótesis nula, aumenta el riesgo de no rechazarla aunque sea falsa.</p>
<p><img src="INREMDN_files/figure-html/columpio.png" width="50%" style="display: block; margin: auto;" /></p>
<p>¿Qué se suele hacer?</p>
<ol style="list-style-type: decimal">
<li><p>Se da una regla de decisión para el nivel de significación <span class="math inline">\(\alpha\)</span> deseado.</p></li>
<li><p>Después, se toma el tamaño <span class="math inline">\(n\)</span> adecuado de la muestra para que la potencia sea la deseada.</p></li>
</ol>

<div class="rmdimportant">
Es costumbre (pero solo eso, una costumbre, no un dogma de fe) tomar <span class="math inline">\(\alpha=0.05\)</span>, una probabilidad de 1 entre 20: algo menos que la probabilidad de sacar 4 caras seguidas con una moneda equilibrada.
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-570"></span>
<img src="INREMDN_files/figure-html/worship.png" alt="No adoraréis falsos dioses." width="50%" />
<p class="caption">
Figura 14.2: No adoraréis falsos dioses.
</p>
</div>
<p>Tomando este <span class="math inline">\(\alpha=0.05\)</span>, aceptamos una probabilidad de equivocarnos rechazando <span class="math inline">\(H_0\)</span> en favor de <span class="math inline">\(H_1\)</span> de 0.05. Es decir, asumimos que, de media, nos vamos a equivocar en 1 de cada 20 veces en que la hipótesis nula sea verdadera.</p>
</div>
<div id="sec:exttest" class="section level2 hasAnchor" number="14.5">
<h2><span class="header-section-number">14.5</span> Ejemplo: El test t<a href="contrastes-de-hipótesis.html#sec:exttest" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La concentración media de calcio en plasma en hombres sanos de 22 a 44 años es de 2.5 mmol/l.
Nos preguntamos si los hombres jóvenes con diabetes tienen una concentración de calcio en plasma mayor que estos 2.5 mmol/l. Traducimos esta cuestión en un contraste de hipótesis sobre la concentración media de calcio en plasma en los hombres jóvenes con diabetes, a la que llamaremos <span class="math inline">\(\mu\)</span>:</p>
<ul>
<li><p>La hipótesis nula será que no hay diferencia entre <span class="math inline">\(\mu\)</span> y la concentración media de calcio en plasma en los hombres jóvenes sanos, es decir, que <span class="math inline">\(\mu=2.5\)</span></p></li>
<li><p>La hipótesis alternativa es de lo que buscamos evidencia: que <span class="math inline">\(\mu&gt;2.5\)</span>.</p></li>
</ul>
<p>Por lo tanto, el contraste que queremos realizar es
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=2.5\\
H_{1}:\mu &gt;2.5
\end{array}
\right.
\]</span></p>
<p>Llamemos <span class="math inline">\(X\)</span> a la variable aleatoria “Tomamos un hombre diabético de 22 a 44 años y le medimos la concentración de calcio en plasma en mmol/l”, cuya media hemos llamado <span class="math inline">\(\mu\)</span>. Vamos a suponer en esta sección que esta variable <span class="math inline">\(X\)</span> sigue una ley normal.</p>
<p>En una muestra de 40 diabéticos de esta franja de edad, se obtuvo una concentración media de calcio en plasma de <span class="math inline">\(\overline{x}=3.2\)</span> mmol/l con una desviación típica muestral <span class="math inline">\(\widetilde{s}=1.5\)</span>. Vamos a suponer que podemos considerar esta muestra de diabéticos jóvenes como aleatoria simple.</p>
<p>Nos encontramos ante un caso particular de la situación siguiente. Tenemos una variable aleatoria poblacional <span class="math inline">\(X\)</span> normal de media <span class="math inline">\(\mu\)</span> y planteamos el contraste
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\
H_{1}:\mu &gt;\mu_0
\end{array}
\right.
\]</span>
para un valor concreto <span class="math inline">\(\mu_0\)</span>. Queremos tomar una decisión a partir de una muestra aleatoria simple.</p>
<p>La idea es que rechazaremos <span class="math inline">\(H_0\)</span> en favor de <span class="math inline">\(H_1\)</span> si la media muestral es mucho mayor que <span class="math inline">\(\mu_0\)</span>: tanto, que sería muy improbable que fuera así de grande si la media poblacional fuera exactamente <span class="math inline">\(\mu_0\)</span>. El problema es que no sabemos calcular <span class="math inline">\(P(\overline{X}-\mu_0)\)</span> si solo sabemos que <span class="math inline">\(X\)</span> es normal de media <span class="math inline">\(\mu_0\)</span>, porque no sabemos la distribución de <span class="math inline">\(\overline{X}\)</span> (sabemos que será normal de media <span class="math inline">\(\mu_0\)</span>, pero desconocemos su desviación típica). Por lo tanto tenemos que usar otro estadístico de contraste, <span class="math inline">\(\overline{X}\)</span> no funcionará.</p>
<p>Llegados a este punto, nos acordamos de que si <span class="math inline">\(H_0\)</span> es verdadera, es decir, si la media de <span class="math inline">\(X\)</span> es <span class="math inline">\(\mu_0\)</span>, entonces
<span class="math display">\[
T=\frac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}
\]</span>
tiene distribución <span class="math inline">\(t_{n-1}\)</span>. Y podemos traducir que “<span class="math inline">\(\overline{X}\)</span> sea mucho mayor que <span class="math inline">\(\mu_0\)</span>” en que “<span class="math inline">\(T\)</span> sea mucho mayor que 0”.</p>
<p>Entonces, la idea que guiará el procedimiento para tomar una decisión en este contraste será la siguiente:</p>
<blockquote>
<p>Rechazaremos <span class="math inline">\(H_0\)</span> en favor de <span class="math inline">\(H_1\)</span> si este <strong>estadístico de contraste</strong> <span class="math inline">\(T\)</span> toma un valor “muy grande” sobre la muestra.</p>
</blockquote>
<p>La definición precisa de “muy grande” dependerá del valor de <span class="math inline">\(\alpha\)</span> que queramos tomar, es decir, de la probabilidad de cometer un error de tipo I que estemos dispuestos a asumir: cuanto menor queramos que sea <span class="math inline">\(\alpha\)</span>, mayor tendrá que ser la evidencia a favor de <span class="math inline">\(\mu&gt;\mu_0\)</span>, es decir, mayor tendrá que ser <span class="math inline">\(T\)</span>. Aquí vamos a tomar el valor usual <span class="math inline">\(\alpha=0.05\)</span>.</p>
<p>Sea <span class="math inline">\(T_0\)</span> el valor que toma el estadístico de contraste <span class="math inline">\(T\)</span> en nuestra muestra. Rechazaremos <span class="math inline">\(H_{0}\)</span> si <span class="math inline">\(T_0\)</span> es mayor que un cierto umbral <span class="math inline">\(L_0\)</span>, que determinamos a partir de <span class="math inline">\(\alpha\)</span>:</p>
<p><span class="math display">\[
\begin{array}{l}
\alpha = P(\text{Rechazar } H_{0}\,|\, H_{0} \text{ cierta})=P(T&gt; L_0)\\
\qquad\quad \Longrightarrow 1-\alpha= P(T\leqslant L_0)\Longrightarrow
L_0= t_{n-1,1-\alpha}
\end{array}
\]</span></p>
<p><img src="INREMDN_files/figure-html/unnamed-chunk-571-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Por lo tanto, para que el nivel de significación del contraste sea <span class="math inline">\(\alpha\)</span>,</p>
<blockquote>
<p>Rechazaremos <span class="math inline">\(H_0\)</span> si <span class="math inline">\(T_0&gt;t_{n-1,1-\alpha}\)</span></p>
</blockquote>
<p>Llamaremos a esta regla una <strong>regla de rechazo</strong> para este tipo de contraste.</p>
<p>Volvamos a nuestro ejemplo de los jóvenes diabéticos
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=2.5\\
H_{1}:\mu &gt; 2.5
\end{array}
\right.
\]</span>
Si <span class="math inline">\(\alpha=0.05\)</span> y <span class="math inline">\(n=40\)</span>, el umbral a partir del cual rechazamos <span class="math inline">\(H_0\)</span> es <span class="math inline">\(t_{n-1,1-\alpha}=t_{39,0.95}=1.685\)</span>.</p>
<p>En nuestra muestra tenemos que <span class="math inline">\(\overline{x}=3.2\)</span>, <span class="math inline">\(\widetilde{s}=1.5\)</span> y <span class="math inline">\(n=40\)</span>, por lo tanto el estadístico de contraste vale
<span class="math display">\[
T_0=\frac{3.2-2.5}{1.5/\sqrt{40}}=2.95
\]</span></p>
<p><img src="INREMDN_files/figure-html/unnamed-chunk-572-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Como 2.95&gt;1.685, concluimos con un nivel de significación del 5% que el nivel medio de calcio en sangre en los jóvenes diabéticos es mayor que en los jóvenes sanos.</p>
<p>Vamos a ver cómo entra en juego el p-valor. Recordad que rechazamos <span class="math inline">\(H_0\)</span> cuando <span class="math inline">\(T_0&gt;t_{n-1,1-\alpha}\)</span>:
<span class="math display">\[
\begin{array}{l}
\text{Rechazamos $H_0$} \Longleftrightarrow T_0&gt; t_{n-1,1-\alpha}\\
\qquad \Longleftrightarrow P(T\geqslant T_0)&lt; P(T\geqslant t_{n-1,1-\alpha})\\
\qquad \Longleftrightarrow P(T\geqslant T_0)&lt; 1-P(T\leqslant t_{n-1,1-\alpha})=1-(1-\alpha)=\alpha\\
\qquad \Longleftrightarrow P(T\geqslant T_0)&lt;\alpha
\end{array}
\]</span></p>
<p>I ahora notad que <span class="math inline">\(P(T\geqslant T_0)\)</span> es la probabilidad de que, si <span class="math inline">\(H_0\)</span> es verdadera, el estadístico de contraste <span class="math inline">\(T\)</span> tome un valor tan o más extremo, en el sentido de <span class="math inline">\(H_1: \mu&gt;2.5\)</span>, que el obtenido en nuestra muestra, <span class="math inline">\(T_0\)</span>: ¡es el <strong>p-valor</strong> del contraste! Por lo tanto, tenemos otra regla de rechazo, equivalente a la anterior:</p>
<blockquote>
<p>Rechazaremos <span class="math inline">\(H_0\)</span> si el p-valor es menor que <span class="math inline">\(\alpha\)</span></p>
</blockquote>
<p>En nuestro ejemplo, ya hemos calculado <span class="math inline">\(T_0=2.95\)</span>. Entonces,
<span class="math display">\[
\text{p-valor} =P(T\geqslant 2.95)=P(t_{39}\geqslant 2.95)=0.003
\]</span>
Como el p-valor es menor que 0.05:</p>
<blockquote>
<p>Concluimos con un nivel de significación del 5% que el nivel medio de calcio en plasma de los jóvenes diabéticos es mayor que el de los jóvenes sanos.</p>
</blockquote>
<p>Esto se suele expresar diciendo que</p>
<blockquote>
<p>Hemos obtenido evidencia estadísticamente significativa de que el nivel medio de calcio en plasma de los jóvenes diabéticos es mayor que el de los jóvenes sanos.</p>
</blockquote>
<p><img src="INREMDN_files/figure-html/pfm.png" width="35%" style="display: block; margin: auto;" /></p>

<div class="rmdrecordau">
A este tipo de procedimiento para comparar la <span class="math inline">\(\mu\)</span> de una variable con un valor dado <span class="math inline">\(\mu_0\)</span>, usando que<br />
<span class="math display">\[
T=\frac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}
\]</span>
sigue una distribución t de Student con <span class="math inline">\(n-1\)</span> grados de libertad, <span class="math inline">\(t_{n-1}\)</span>, se le llama un <strong>test t</strong>. En la próxima lección explicaremos cuándo se puede usar.
</div>
<p>Fijaos en que nuestra conclusión ha sido que “concluimos con un <strong>nivel de significación del 5%</strong> que el nivel medio de calcio en sangre de los jóvenes diabéticos es mayor que el de los jóvenes sanos.” Por lo tanto, <strong>aceptamos una probabilidad del 5% de cometer un falso positivo</strong>. Si en realidad el nivel medio de calcio en sangre de los jóvenes diabéticos fuera el mismo que el de los sanos, la probabilidad que tendríamos de equivocarnos y concluir que el nivel medio de calcio en sangre de los jóvenes diabéticos es mayor que el de los sanos es del 5%.</p>

<div class="rmdimportant">
Que tengamos un 5% de probabilidad de equivocarnos significa que, si la hipótesis nula es verdadera, un 5% de las muestras aleatorias de 40 diabéticos sanos dan un valor de <span class="math inline">\(T\)</span> que nos hace rechazar la hipótesis nula.
</div>
<div class="example">
<p><span id="exm:unnamed-chunk-576" class="example"><strong>Ejemplo 14.14  </strong></span>Vamos a estudiar esta tasa de aciertos por medio de una simulación.</p>
</div>
<p>Primero supondremos que el nivel medio real es 2.5, y simularemos la probabilidad de error de tipo I. Como estamos realizando el contraste con nivel de significación 0.05, esperamos alrededor de un 5% de errores de tipo I. Para fijar ideas, modelaremos la población de jóvenes diabéticos por medio de una variable aleatoria normal <span class="math inline">\(N(2.5,0.5)\)</span>. La <span class="math inline">\(\sigma=0.5\)</span> nos la hemos inventado. Damos el código R de la simulación, por si la queréis repetir en casa. Cada simulación dará resultados diferentes, pero en general serán muy parecidos a los nuestros.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="contrastes-de-hipótesis.html#cb64-1" tabindex="-1"></a>mu0<span class="ot">=</span><span class="fl">2.5</span></span>
<span id="cb64-2"><a href="contrastes-de-hipótesis.html#cb64-2" tabindex="-1"></a>sigma0<span class="ot">=</span><span class="fl">0.5</span></span></code></pre></div>
<p>El umbral <span class="math inline">\(L_0\)</span> para <span class="math inline">\(n=40\)</span> y <span class="math inline">\(\alpha=0.05\)</span> es <span class="math inline">\(t_{39,0.975}\)</span>:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="contrastes-de-hipótesis.html#cb65-1" tabindex="-1"></a>L0<span class="ot">=</span><span class="fu">qt</span>(<span class="fl">0.95</span>,<span class="dv">39</span>)</span>
<span id="cb65-2"><a href="contrastes-de-hipótesis.html#cb65-2" tabindex="-1"></a>L0</span></code></pre></div>
<pre><code>## [1] 1.684875</code></pre>
<p>La función <code>estadístico</code> siguiente toma una muestra aleatoria de tamaño <span class="math inline">\(n\)</span> de una variable <span class="math inline">\(N(\mu, \sigma)\)</span> y calcula el estadístico de contraste <span class="math inline">\(T\)</span>:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="contrastes-de-hipótesis.html#cb67-1" tabindex="-1"></a>estadístico<span class="ot">=</span><span class="cf">function</span>(n,mu,sigma){</span>
<span id="cb67-2"><a href="contrastes-de-hipótesis.html#cb67-2" tabindex="-1"></a>muestra<span class="ot">=</span><span class="fu">rnorm</span>(n,mu,sigma) </span>
<span id="cb67-3"><a href="contrastes-de-hipótesis.html#cb67-3" tabindex="-1"></a>(<span class="fu">mean</span>(muestra)<span class="sc">-</span>mu0)<span class="sc">/</span>(<span class="fu">sd</span>(muestra)<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb67-4"><a href="contrastes-de-hipótesis.html#cb67-4" tabindex="-1"></a>}</span></code></pre></div>
<p>Ahora, repetimos 200 veces el proceso de tomar una muestra aleatoria de tamaño 40 de nuestra población y calcular la <span class="math inline">\(T\)</span> correspondiente. Llamamos <code>Tes</code> al vector de estos valores de <span class="math inline">\(T\)</span>:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="contrastes-de-hipótesis.html#cb68-1" tabindex="-1"></a>Tes<span class="ot">=</span><span class="fu">replicate</span>(<span class="dv">200</span>,estadístico(<span class="dv">40</span>,mu0,sigma0))</span>
<span id="cb68-2"><a href="contrastes-de-hipótesis.html#cb68-2" tabindex="-1"></a>Tes</span></code></pre></div>
<pre><code>##   [1] -0.204556115  0.551277014  0.317804933 -1.916424317  0.228799593
##   [6] -0.636252541  0.546424036 -0.411971051 -0.424224911  1.184281984
##  [11] -1.372747727  0.319514212 -0.485567240  0.724620331 -1.114121167
##  [16]  1.002994827 -0.892700484 -2.394044325 -1.024911510 -1.273715103
##  [21] -0.676221781  0.012311445  1.558797931 -0.189208386  1.137960594
##  [26] -0.362377491 -1.342997649  0.100980325  0.532357160 -0.370579439
##  [31]  0.577851111 -0.047777832  0.684704147 -1.208505741 -1.329676807
##  [36] -0.284045263 -0.284095079 -0.291495898 -0.878941168  1.051862629
##  [41]  1.579509611  1.251686082  2.045852094 -2.360865854 -0.103192516
##  [46]  0.390701261  1.880219725 -0.018662794 -3.024762654  0.123696814
##  [51]  0.761344572 -0.090605574 -2.687031800  0.801886366 -0.536807420
##  [56] -0.028474151  0.196027879  0.682146866  1.411321489 -0.188707738
##  [61]  1.546524165 -0.347908999 -0.026022121  0.209821139  0.805317582
##  [66]  1.314081240 -0.839884569  0.396920453  0.660980262 -0.906549698
##  [71] -0.359463173 -0.147452173 -0.064257189 -2.155846414 -0.139568976
##  [76] -0.376455346  2.092808159 -0.709729535 -1.463534383 -1.809695988
##  [81]  0.742383769 -0.622674376  0.983232702  0.788220841 -0.154184656
##  [86] -1.161571197 -0.004649001 -0.438892198 -0.423543531 -0.264518977
##  [91]  0.767939038 -0.182387180  0.080963916  0.320526506  0.280413272
##  [96]  0.513633868 -1.638150471 -0.296678393 -0.543844147  0.392508189
## [101] -1.998219688 -1.462626783 -1.047438984 -1.051544062  0.875209713
## [106] -2.259121522 -0.001964387 -0.373639492  0.666057937  0.789694009
## [111] -0.702070906  3.201760850  0.722601940  0.197681171 -0.628662655
## [116]  2.445684957 -1.564835664 -0.421947252 -0.115222019 -0.670212416
## [121]  1.074994408 -1.144731548  0.014513287 -0.045690803  1.767038039
## [126] -0.490172630 -0.515288612 -0.723240119  0.114766130  2.233403900
## [131]  1.044936465 -0.924690832  1.853218655 -1.907551408  0.126266762
## [136] -0.688907166  1.117818143  1.821936572  0.329612552  0.071381075
## [141] -0.021639874  0.676769124  0.520849057 -2.006704343 -0.914341584
## [146]  0.585164132  0.655106533  0.119263816  0.262166125  0.803028099
## [151] -0.980923973  0.771922952  1.409751739 -0.831274271  0.946192097
## [156] -0.069357657 -2.266986664  1.339021435 -0.749638232  0.908952239
## [161]  0.413367570  2.009701264  0.455159446 -1.104914158 -0.643085983
## [166] -0.429874411 -0.196858070 -1.429470266 -2.181882962  1.466635278
## [171]  0.742815143  1.213190128  1.085521457 -1.497524599 -0.672070568
## [176]  0.262390233  0.852553576  0.390132290  1.692839873 -1.970368198
## [181] -1.173300556 -0.076807106  0.969328371 -0.284565211 -2.289453979
## [186]  0.535255778 -2.899705754  0.156836454  1.670103115  0.568690995
## [191] -2.543506854 -0.577244792 -1.696047276  0.991672787 -0.582753120
## [196] -2.219149723  0.109210103  0.279098618 -0.847558940 -1.390283286</code></pre>
<p>Finalmente, calculamos la proporción de veces que la <span class="math inline">\(T\)</span> ha dado un valor mayor que el umbral <span class="math inline">\(L_0\)</span>, es decir, la proporción de veces que rechazamos la hipótesis nula <span class="math inline">\(\mu=2.5\)</span> y que por lo tanto cometemos un error de tipo I.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="contrastes-de-hipótesis.html#cb70-1" tabindex="-1"></a>p.error.Tipo.I<span class="ot">=</span><span class="fu">length</span>(<span class="fu">which</span>((Tes<span class="sc">&gt;</span>L0)<span class="sc">==</span><span class="cn">TRUE</span>))<span class="sc">/</span><span class="dv">200</span></span>
<span id="cb70-2"><a href="contrastes-de-hipótesis.html#cb70-2" tabindex="-1"></a>p.error.Tipo.I</span></code></pre></div>
<pre><code>## [1] 0.055</code></pre>
<p>Hemos cometido un 5.5% de errores de tipo I, muy cercano al 5% “poblacional” (en el conjunto de todas las muestras aleatorias que pudiéramos tomar).</p>
<p>Ahora vamos a suponer que el nivel medio real es estrictamente mayor que 2.5, y vamos a simular los errores de tipo II, para ver con qué frecuencia los cometemos. Para empezar, generamos al azar un vector de 100 <span class="math inline">\(\mu\)</span>’s entre 2.6 y 3, de manera que todos los valores tengan la misma probabilidad de salir.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="contrastes-de-hipótesis.html#cb72-1" tabindex="-1"></a>mus<span class="ot">=</span><span class="fu">runif</span>(<span class="dv">100</span>,<span class="fl">2.6</span>,<span class="dv">3</span>)</span></code></pre></div>
<p>Para cada <span class="math inline">\(\mu_i\)</span> de este vector, tomaremos como “población de diabéticos” una variable <span class="math inline">\(N(\mu_i,0.5)\)</span>. A continuación, para cada una de estas poblaciones, repetiremos 200 veces el proceso de tomar una muestra aleatoria simple de tamaño 40 de esta población y calcular la <span class="math inline">\(T\)</span> correspondiente. Después, para cada población, miraremos la proporción de veces que la <span class="math inline">\(T\)</span> ha dado menor o igual que el umbral <span class="math inline">\(L_0\)</span>, es decir, la proporción de veces que aceptaríamos la hipótesis nula <span class="math inline">\(\mu=2.5\)</span> y que por lo tanto cometeríamos un error de tipo II. Organizamos todas estas proporciones en un vector que llamamos <code>p.error.Tipo.II</code>.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="contrastes-de-hipótesis.html#cb73-1" tabindex="-1"></a>p.error.Tipo.II<span class="ot">=</span><span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">100</span>)</span>
<span id="cb73-2"><a href="contrastes-de-hipótesis.html#cb73-2" tabindex="-1"></a><span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb73-3"><a href="contrastes-de-hipótesis.html#cb73-3" tabindex="-1"></a>  Tes<span class="ot">=</span><span class="fu">replicate</span>(<span class="dv">200</span>,estadístico(<span class="dv">40</span>,mus[j],sigma0))    </span>
<span id="cb73-4"><a href="contrastes-de-hipótesis.html#cb73-4" tabindex="-1"></a>  p.error.Tipo.II[j]<span class="ot">=</span><span class="fu">length</span>(<span class="fu">which</span>((Tes<span class="sc">&lt;=</span>L0)<span class="sc">==</span><span class="cn">TRUE</span>))<span class="sc">/</span><span class="dv">200</span></span>
<span id="cb73-5"><a href="contrastes-de-hipótesis.html#cb73-5" tabindex="-1"></a>}</span>
<span id="cb73-6"><a href="contrastes-de-hipótesis.html#cb73-6" tabindex="-1"></a>p.error.Tipo.II</span></code></pre></div>
<pre><code>##   [1] 0.015 0.275 0.055 0.005 0.495 0.040 0.000 0.005 0.420 0.090 0.000 0.085
##  [13] 0.245 0.000 0.195 0.000 0.080 0.000 0.525 0.000 0.000 0.410 0.140 0.000
##  [25] 0.000 0.330 0.050 0.000 0.010 0.610 0.460 0.575 0.000 0.000 0.005 0.000
##  [37] 0.110 0.000 0.000 0.000 0.000 0.000 0.015 0.115 0.020 0.000 0.000 0.000
##  [49] 0.040 0.015 0.000 0.005 0.000 0.000 0.045 0.190 0.000 0.005 0.560 0.085
##  [61] 0.000 0.000 0.595 0.015 0.005 0.000 0.000 0.000 0.500 0.000 0.085 0.195
##  [73] 0.370 0.645 0.015 0.000 0.245 0.130 0.140 0.590 0.315 0.325 0.000 0.105
##  [85] 0.000 0.085 0.000 0.460 0.000 0.000 0.005 0.175 0.065 0.390 0.000 0.000
##  [97] 0.010 0.000 0.000 0.000</code></pre>
<p>En algunos casos no hemos cometido ningún error de tipo II, y en otros, en más de la mitad de las veces. La proporción media de errores de tipo II ha sido:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="contrastes-de-hipótesis.html#cb75-1" tabindex="-1"></a><span class="fu">mean</span>(p.error.Tipo.II)</span></code></pre></div>
<pre><code>## [1] 0.1179</code></pre>
<p>Si tomamos muestras más grandes, la probabilidad de error de tipo II disminuye. Comprobémoslo repitiendo este segundo experimento con muestras de tamaño 400.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="contrastes-de-hipótesis.html#cb77-1" tabindex="-1"></a>p.error.Tipo.II<span class="fl">.400</span><span class="ot">=</span><span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">100</span>)</span>
<span id="cb77-2"><a href="contrastes-de-hipótesis.html#cb77-2" tabindex="-1"></a><span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb77-3"><a href="contrastes-de-hipótesis.html#cb77-3" tabindex="-1"></a>Tes<span class="ot">=</span><span class="fu">replicate</span>(<span class="dv">200</span>,estadístico(<span class="dv">400</span>,mus[j],sigma0))    </span>
<span id="cb77-4"><a href="contrastes-de-hipótesis.html#cb77-4" tabindex="-1"></a>  p.error.Tipo.II<span class="fl">.400</span>[j]<span class="ot">=</span><span class="fu">length</span>(<span class="fu">which</span>((Tes<span class="sc">&lt;=</span>L0)<span class="sc">==</span><span class="cn">TRUE</span>))<span class="sc">/</span><span class="dv">200</span></span>
<span id="cb77-5"><a href="contrastes-de-hipótesis.html#cb77-5" tabindex="-1"></a>}</span>
<span id="cb77-6"><a href="contrastes-de-hipótesis.html#cb77-6" tabindex="-1"></a><span class="fu">mean</span>(p.error.Tipo.II<span class="fl">.400</span>)</span></code></pre></div>
<pre><code>## [1] 2e-04</code></pre>

<div class="rmdcorbes">
Por si no os habéis encontrado nunca con la notación que ha usado R para dar este resultado, es la llamada <strong>notación científica</strong> y se usa para expresar números muy grandes o muy pequeños. La <code>e</code> significa “multiplica el número que me precede por 10 elevado al número que me sigue”. Así, <code>2e-04</code> significa <span class="math inline">\(2\times 10^{-4}\)</span>, o sea, 0.0002.
</div>
<p>Multiplicando por 10 el tamaño de las muestras, hemos bajado de una tasa de errores de tipo II del 11.79% al 0.02%.</p>
<p>Recordad que la <strong>potencia</strong> de un contraste es la probabilidad de <strong>no</strong> cometer un error de tipo II. Hemos visto que tomando muestras más grandes, la proporción de errores de tipo II ha disminuido. Esto es general:</p>

<div class="rmdimportant">
Si fijamos el nivel de significación, cuanto mayores son las muestras, mayor es la potencia del contraste.
</div>
<p>Volvemos a la situación general en la que tenemos una variable aleatoria <span class="math inline">\(X\)</span> normal <span class="math inline">\(N(\mu,\sigma)\)</span> y queremos comparar <span class="math inline">\(\mu\)</span> con cierto valor <span class="math inline">\(\mu_0\)</span> y supongamos que ahora buscamos evidencia de que <span class="math inline">\(\mu&lt;\mu_0\)</span>, de manera que el contraste es
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\
H_{1}:\mu &lt; \mu_0
\end{array}
\right.
\]</span>
En este caso, el p-valor es <span class="math inline">\(P(T\leqslant T_0)\)</span> y, razonando exactamente igual que antes, obtenemos las dos reglas de rechazo equivalentes siguientes:</p>
<blockquote>
<p>Rechazaremos <span class="math inline">\(H_0\)</span> si <span class="math inline">\(T_0&lt; t_{n-1,\alpha}\)</span></p>
</blockquote>
<blockquote>
<p>Rechazaremos <span class="math inline">\(H_0\)</span> si el p-valor es menor que <span class="math inline">\(\alpha\)</span></p>
</blockquote>
<p>¿Y qué pasa si ahora buscamos evidencia de que <span class="math inline">\(\mu\)</span> <strong>es diferente</strong> de <span class="math inline">\(\mu_0\)</span>? Es decir, si nos planteamos el contraste
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\
H_{1}:\mu\
\neq \mu_0
\end{array}
\right.
\]</span></p>
<p>En este caso, rechazaremos <span class="math inline">\(H_{0}\)</span> cuando <span class="math inline">\(\overline{X}\)</span> es muy diferente de <span class="math inline">\(\mu_0\)</span> y esto lo traducimos en que rechazaremos <span class="math inline">\(H_{0}\)</span> cuando el <strong>valor absoluto</strong> de <span class="math inline">\(T_0\)</span>, <span class="math inline">\(|T_0|\)</span>, sea mayor que un cierto umbral <span class="math inline">\(L_0\)</span>, que determinamos a partir de <span class="math inline">\(\alpha\)</span> como antes:</p>
<p><span class="math display">\[
\begin{array}{l}
\alpha = P(\text{Rechazar } H_{0}| H_{0} \text{ verdadera})=P(|T|&gt; L_0)\\
\hphantom{\alpha} = P(T&lt; -L_0\text{ o } T&gt;L_0)= P(T&lt; -L_0)+P(T&gt;L_0)\\
\hphantom{\alpha} =2P(T&gt;L_0) \text{ (por la simetría de $t_{n-1}$)}\\
\Longrightarrow \alpha/2=P(T&gt;L_0)= 1-P(T\leqslant L_0) \\
\Longrightarrow P(T\leqslant L_0)=1-\alpha/2\Longrightarrow
L_0= t_{n-1,1-\alpha/2}
\end{array}
\]</span></p>
<p>Por lo tanto, en un contraste bilateral con nivel de significación <span class="math inline">\(\alpha\)</span>, tenemos la regla de rechazo siguiente:</p>
<blockquote>
<p>Rechazaremos <span class="math inline">\(H_0\)</span> si <span class="math inline">\(|T_0|&gt;t_{n-1,1-\alpha/2}\)</span></p>
</blockquote>
<p>En este caso, el p-valor será la probabilidad de que <span class="math inline">\(T\)</span> tome un valor tan o más extremo que <span class="math inline">\(T_0\)</span> en el sentido de la hipótesis alternativa, es decir, más lejos de 0 que <span class="math inline">\(T_0\)</span>: mayor que <span class="math inline">\(|T_0|\)</span> o menor que <span class="math inline">\(-|T_0|\)</span>:
<span class="math display">\[
\text{p-valor} =P(T\leqslant -|T_0|)+P(T\geqslant |T_0|)=2 P(T\geqslant |T_0|).
\]</span>
Fijaos en que usamos que, por la simetría de las variables t de Student, <span class="math inline">\(P(T\leqslant -|T_0|)=P(T\geqslant |T_0|)\)</span>.</p>
<p>Por lo tanto,
<span class="math display">\[
\begin{array}{l}
\text{Rechazamos $H_0$} \Longleftrightarrow |T_0|&gt;t_{n-1,1-\alpha/2}\\
\qquad \Longleftrightarrow P(T\geqslant |T_0|)&lt;{\alpha}/{2}\\
\qquad\Longleftrightarrow 2 P(T\geqslant |T_0|)&lt;\alpha\\
\qquad \Longleftrightarrow \text{p-valor} &lt; \alpha
\end{array}
\]</span></p>
<p>Así pues, en un contraste bilateral con nivel de significación <span class="math inline">\(\alpha\)</span> también tenemos la regla de rechazo:</p>
<blockquote>
<p>Rechazaremos <span class="math inline">\(H_0\)</span> si el p-valor es menor que <span class="math inline">\(\alpha\)</span></p>
</blockquote>

<div class="rmdimportant">
<p>En resumen, en un contraste de una media <span class="math inline">\(\mu\)</span> usando un test t sobre una muestra de tamaño <span class="math inline">\(n\)</span> y nivel de significación <span class="math inline">\(\alpha\)</span>:</p>
<ul>
<li><p>Si <span class="math inline">\(H_1:\mu&gt; \mu_0\)</span>:</p>
<ul>
<li>Rechazamos <span class="math inline">\(H_0\)</span> si <span class="math inline">\(T_0&gt;t_{n-1,1-\alpha}\)</span></li>
<li>El p-valor es <span class="math inline">\(P(T\geqslant T_0)\)</span></li>
<li>Rechazamos <span class="math inline">\(H_0\)</span> si el p-valor es menor que <span class="math inline">\(\alpha\)</span></li>
</ul></li>
<li><p>Si <span class="math inline">\(H_1:\mu&lt; \mu_0\)</span>:</p>
<ul>
<li>Rechazamos <span class="math inline">\(H_0\)</span> si <span class="math inline">\(T_0&lt; t_{n-1,\alpha}\)</span></li>
<li>El p-valor es <span class="math inline">\(P(T\leqslant T_0)\)</span></li>
<li>Rechazamos <span class="math inline">\(H_0\)</span> si el p-valor es menor que <span class="math inline">\(\alpha\)</span></li>
</ul></li>
<li><p>Si <span class="math inline">\(H_1:\mu\neq \mu_0\)</span>:</p>
<ul>
<li>Rechazamos <span class="math inline">\(H_0\)</span> si <span class="math inline">\(|T_0|&gt;t_{n-1,1-\alpha/2}\)</span></li>
<li>El p-valor es <span class="math inline">\(2P(T\geqslant |T_0|)\)</span></li>
<li>Rechazamos <span class="math inline">\(H_0\)</span> si el p-valor es menor que <span class="math inline">\(\alpha\)</span></li>
</ul></li>
</ul>
</div>

<div class="rmdrecordau">
Siempre, en todos los contrastes y no solo en los tests t, <strong>se rechaza la hipótesis nula en favor de la alternativa si el p-valor es menor que el nivel de significación</strong>.
</div>
<div class="example">
<p><span id="exm:ttestmu20" class="example"><strong>Ejemplo 14.15  </strong></span>Sea <span class="math inline">\(X\)</span> una variable poblacional normal. Queremos realizar el contraste
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=20\\ H_{1}:\mu&gt;20
\end{array}
\right.
\]</span>
con un nivel de significación de 0.05. Tomamos una muestra aleatoria simple de <span class="math inline">\(n=25\)</span> observaciones y obtenemos <span class="math inline">\(\overline{x}=20.7\)</span> y <span class="math inline">\(\widetilde{s}=1.8\)</span>. ¿Qué decidimos?</p>
</div>
<ul>
<li><p>El estadístico de contraste que usaremos es
<span class="math display">\[
T=\dfrac{\overline{X}-\mu_0}{\widetilde{S}_X/\sqrt{n}}
\]</span>
con <span class="math inline">\(\mu_0=20\)</span> y <span class="math inline">\(n=25\)</span>.</p></li>
<li><p>Su valor en nuestra muestra es
<span class="math display">\[
T_0=\dfrac{20.7-20}{{1.8}/{\sqrt{25}}}=1.944
\]</span></p></li>
<li><p>El p-valor es
<span class="math display">\[
P(T\geqslant 1.944)=P(t_{24}\geqslant 1.944)=0.032
\]</span></p></li>
<li><p><strong>Decisión</strong>: Como el p-valor es menor que 0.05, rechazamos <span class="math inline">\(H_0\)</span> y concluimos (con <span class="math inline">\(\alpha=0.05\)</span>) que <span class="math inline">\(\mu&gt;20\)</span>. Es decir, hemos obtenido evidencia estadísticamente significativa de que <span class="math inline">\(\mu&gt;20\)</span>.</p></li>
</ul>
<div class="example">
<p><span id="exm:unnamed-chunk-591" class="example"><strong>Ejemplo 14.16  </strong></span>Sea <span class="math inline">\(X\)</span> una variable poblacional normal. Queremos realizar el contraste
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=20\\ H_{1}:\mu&gt;20
\end{array}
\right.
\]</span>
con un nivel de significación de 0.01. Con la misma muestra aleatoria simple del ejemplo anterior, ¿qué decidimos?</p>
</div>
<p>El p-valor es el mismo que antes, 0.032, porque el contraste y la muestra son los mismos. Como este p-valor es mayor que 0.01, no podemos rechazar <span class="math inline">\(H_0\)</span> con <span class="math inline">\(\alpha=0.01\)</span> y tenemos que aceptar que <span class="math inline">\(\mu=20\)</span>. Con este nivel de significación, no hemos obtenido evidencia de que <span class="math inline">\(\mu&gt;20\)</span>.</p>

<div class="rmdnote">
Fijaos en que para reducir la probabilidad de equivocarnos rechazando <span class="math inline">\(H_0\)</span> si es verdadera, facilitamos aceptarla “por si acaso”.
</div>
<div class="example">
<p><span id="exm:ttestmu20petit" class="example"><strong>Ejemplo 14.17  </strong></span>Sea <span class="math inline">\(X\)</span> una variable poblacional normal. Queremos realizar el contraste
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=20\\ H_{1}:\mu&lt; 20
\end{array}
\right.
\]</span>
con un nivel de significación de 0.05. Con la misma muestra aleatoria simple de los ejemplos anteriores (<span class="math inline">\(n=25\)</span>, <span class="math inline">\(\overline{x}=20.7\)</span>, <span class="math inline">\(\widetilde{s}=1.8\)</span>), ¿qué decidimos?</p>
</div>
<ul>
<li><p>El estadístico de contraste y su valor <span class="math inline">\(T_0\)</span> son el mismos que antes.</p></li>
<li><p>p-valor
<span class="math display">\[
P(T\leqslant 1.944)=P(t_{24}\leqslant 1.944)=0.968
\]</span></p></li>
<li><p><strong>Decisión</strong>: Como el p-valor es mayor que 0.05, no podemos rechazar <span class="math inline">\(H_0\)</span> y tenemos que aceptar que <span class="math inline">\(\mu=20\)</span>. Es decir, no hemos obtenido evidencia estadísticamente significativa de que <span class="math inline">\(\mu&lt;20\)</span>.</p></li>
</ul>

<div class="rmderror">
Vamos a ver, ¿cómo queríais que hubiéramos encontrado evidencia de que <span class="math inline">\(\mu&lt;20\)</span> si nos ha salido una media muestral 20.7, mayor que 20? No hacía falta hacer ningún cálculo (y exponernos a equivocarnos), bastaba razonar un poco.
</div>
<div class="example">
<p><span id="exm:ttest1bis" class="example"><strong>Ejemplo 14.18  </strong></span>Sea <span class="math inline">\(X\)</span> una variable poblacional normal. Queremos realizar el contraste
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=20\\ H_{1}:\mu\neq 20
\end{array}
\right.
\]</span>
con un nivel de significación de 0.05. Con la misma muestra aleatoria simple de los ejemplos anteriores, ¿qué decidimos?</p>
</div>
<p>Recordemos que <span class="math inline">\(n=25\)</span>, <span class="math inline">\(\overline{x}=20.7\)</span> y <span class="math inline">\(\widetilde{s}=1.8\)</span>. El estadístico de contraste valía <span class="math inline">\(T_0=1.944\)</span>.</p>
<p>Ahora el p-valor es
<span class="math display">\[
2\cdot P(T\geqslant 1.944)=2\cdot P(t_{24}\geqslant 1.944)=0.064
\]</span></p>
<p>Como el p-valor es mayor que <span class="math inline">\(\alpha\)</span>, no podemos rechazar <span class="math inline">\(H_0\)</span>: no podemos afirmar con <span class="math inline">\(\alpha=0.05\)</span> que <span class="math inline">\(\mu\neq 20\)</span>. Es decir, no hemos obtenido evidencia estadísticamente significativa de que <span class="math inline">\(\mu\neq 20\)</span>.</p>

<div class="rmdromans">
¿Cómo puede ser que, con la misma muestra y mismo nivel de significación, podamos concluir que <span class="math inline">\(\mu&gt; 20\)</span> pero no podamos concluir que <span class="math inline">\(\mu \neq 20\)</span>? ¿Acaso <span class="math inline">\(\mu&gt; 20\)</span> no implica que <span class="math inline">\(\mu \neq 20\)</span>?
</div>
<p>Veamos, si hubiéramos demostrado que seguro que <span class="math inline">\(\mu&gt; 20\)</span>, está claro que esto implicaría que <span class="math inline">\(\mu \neq 20\)</span>. Pero habíamos llegado a la conclusión de que <span class="math inline">\(\mu&gt; 20\)</span> asumiendo una cierta probabilidad de cometer un error de tipo I, y ahora nos preguntamos si podemos decidir que <span class="math inline">\(\mu \neq 20\)</span> asumiendo el mismo riesgo de equivocarnos. En esta situación las reglas de la lógica aristotélica ya no funcionan.</p>
<p>Fijaos en que, en realidad, lo que pasa es que encontraríamos evidencia de que <span class="math inline">\(\mu \neq 20\)</span> si <span class="math inline">\(T\)</span> fuera muy grande o muy pequeño. Por lo tanto, en el contraste bilateral tenemos dos fuentes de error de tipo I: que por puro azar <span class="math inline">\(T\)</span> nos salga muy grande o que nos salga muy pequeño. En cambio, solo encontraremos evidencia de que <span class="math inline">\(\mu&gt; 20\)</span> si <span class="math inline">\(T\)</span> es muy grande, y por consiguiente en el contraste unilateral tenemos una sola fuente de error de tipo I. Entonces, para garantizar la misma probabilidad de error de tipo I, tenemos que ser mucho más exigentes en el contraste bilateral, donde nos podemos equivocar de dos maneras diferentes, que en el unilateral. Por eso es más fácil rechazar la hipótesis nula en un contraste unilateral que en uno bilateral.</p>
<div class="example">
<p><span id="exm:unnamed-chunk-595" class="example"><strong>Ejemplo 14.19  </strong></span>Sea <span class="math inline">\(X\)</span> una variable poblacional normal. Queremos realizar el contraste
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=20\\ H_{1}:\mu \neq 20
\end{array}
\right.
\]</span>
con un nivel de significación de 0.05. Tomamos una muestra aleatoria simple de <span class="math inline">\(n=25\)</span> observaciones y obtenemos <span class="math inline">\(\overline{x}=19\)</span> y <span class="math inline">\(\widetilde{s}=1.8\)</span>. ¿Qué decidimos?</p>
</div>
<ul>
<li><p>El estadístico de contraste
<span class="math display">\[
T=\dfrac{\overline{X}-\mu_0}{\widetilde{S}_X/\sqrt{n}}
\]</span>
ahora vale
<span class="math display">\[
T_0=\dfrac{19-20}{{1.8}/{\sqrt{25}}}=-2.778
\]</span></p></li>
<li><p>El p-valor es
<span class="math display">\[
2P(T\geqslant -2.778)=P(t_{24}\geqslant -2.778)=1.99
\]</span></p></li>
<li><p>Decisión: como el p-valor es mayor que <span class="math inline">\(\alpha\)</span>, no podemos rechazar <span class="math inline">\(H_0\)</span>.</p></li>
</ul>

<div class="rmderror">
El p-valor es una probabilidad. ¿Cómo queréis que dé 1.99?
</div>
<p><strong>¡NO!</strong> El p-valor no es <span class="math inline">\(2\cdot P(T\geqslant T_0)\)</span>, sino <span class="math inline">\(2\cdot P(T\geqslant |T_0|)\)</span>. Por lo tanto, el p-valor es
<span class="math display">\[
2\cdot P(T\geqslant 2.778)=2\cdot P(t_{24}\geqslant 2.778)=0.01
\]</span>
y como este p-valor es menor que <span class="math inline">\(\alpha\)</span>, podemos rechazar <span class="math inline">\(H_0\)</span> y concluir, con nivel de significación 0.05, que <span class="math inline">\(\mu\neq 20\)</span>. Es decir, hemos obtenido evidencia estadísticamente significativa de que <span class="math inline">\(\mu\neq 20\)</span>.</p>
</div>
<div id="la-potencia-de-un-contraste" class="section level2 hasAnchor" number="14.6">
<h2><span class="header-section-number">14.6</span> La potencia de un contraste<a href="contrastes-de-hipótesis.html#la-potencia-de-un-contraste" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Recordad que la <strong>potencia</strong> <span class="math inline">\(1-\beta\)</span> es la probabilidad de rechazar <span class="math inline">\(H_0\)</span> cuando <span class="math inline">\(H_1\)</span> es verdadera.</p>
<p>Por ejemplo, en el ejemplo del calcio en diabéticos de la Sección <a href="contrastes-de-hipótesis.html#sec:exttest">14.5</a>, la regla de rechazo era
<span class="math display">\[
T=\frac{\overline{X}-2.5}{\widetilde{S}_X/\sqrt{n}}&gt;1.685,
\]</span>
por lo tanto la potencia era
<span class="math display">\[
1-\beta=P(\text{Rechazar } H_0\,|\, H_1\text{ verdadera})=P(T&gt;1.685\,|\, \mu&gt;2.5).
\]</span>
Esta probabilidad es imposible de calcular, pero hay programas que la saben estimar para los tests más usuales. Por ejemplo, el paquete <strong>pwr</strong> de R, el módulo <strong>jpower</strong> de JAMOVI o la aplicación G*Power que podéis descargar del url <a href="https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower" class="uri">https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower</a>.</p>
<p>Esta estimación de la potencia se basa en la idea siguiente. Para cada tipo de contraste se tiene una relación numérica entre:</p>
<ul>
<li><p>La <strong>potencia</strong></p></li>
<li><p>El <strong>tamaño</strong> de la muestra <span class="math inline">\(n\)</span>: la potencia crece con <span class="math inline">\(n\)</span></p></li>
<li><p>El <strong>nivel de significación</strong> <span class="math inline">\(\alpha\)</span>: la potencia decrece con <span class="math inline">\(\alpha\)</span></p></li>
<li><p>El <strong>tamaño del efecto</strong>, un valor que cuantifica la diferencia entre el parámetro muestral y el valor contrastado. La potencia crece con el valor absoluto del tamaño del efecto.</p></li>
</ul>
<p>Esta relación permite calcular cualquiera de los cuatro valores a partir de los otros tres. Así, sabiendo <span class="math inline">\(n\)</span>, <span class="math inline">\(\alpha\)</span> y el tamaño del efecto, podemos calcular la potencia del contraste efectuado.</p>
<p>La aplicación más importante de estos cálculos es la determinación del tamaño de la muestra necesario para la potencia deseada. Al planear un experimento para realizar un contraste, hay que:</p>
<ul>
<li><p>Fijar el nivel de significación deseado</p></li>
<li><p>Fijar la potencia deseada</p></li>
<li><p>Estimar el tamaño del efecto esperado (a partir de nuestra teoría, de nuestra experiencia, de los resultados de otros estudios…).</p></li>
</ul>
<p>y usar un programa adecuado que calcule el tamaño de la muestra necesario para lograr la potencia deseada a partir de estos valores.</p>

<div class="rmdcaution">
<p>Desconfiad de los trabajos donde esto no se haga. Podría ser que la potencia fuera muy baja y hubiera un <strong>sesgo de infrapotencia</strong> (<em>underpower</em>): se necesitaba un efecto muy grande para poder rechazar la hipótesis nula y publicar el artículo.</p>
Por ejemplo, imaginad que en un estudio para determinar si la tasa de efectividad de un cierto tratamiento de una enfermedad es mayor del 90% se prueba sobre una muestra de solo 10 enfermos. Entonces, para obtener un p-valor inferior al 0.05 sería necesario que los 10 enfermos se curaran. Por lo tanto, lo más seguro es que los resultados de este estudio solo vieran la luz en un revista científica si la tasa observada de curación en la muestra fuera del 100%. Animado por esta tasa de curación perfecta, uno prueba el tratamiento y comprueba en sus pacientes que su eficacia queda lejos del 100%.
</div>
</div>
<div id="intervalo-de-confianza-de-un-contraste" class="section level2 hasAnchor" number="14.7">
<h2><span class="header-section-number">14.7</span> Intervalo de confianza de un contraste<a href="contrastes-de-hipótesis.html#intervalo-de-confianza-de-un-contraste" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Repasemos los conceptos introducidos hasta ahora, y pongamos nombre a otros:</p>
<ul>
<li><p><strong>Nivel de significación</strong>, <span class="math inline">\(\alpha\)</span>: probabilidad de rechazar <span class="math inline">\(H_0\)</span> si esta es verdadera (probabilidad de <strong>error de tipo I</strong>, de falso positivo).</p></li>
<li><p><strong>Nivel de confianza</strong>, <span class="math inline">\(1-\alpha\)</span>: probabilidad de aceptar <span class="math inline">\(H_0\)</span> si esta es verdadera (probabilidad de verdadero negativo).</p></li>
<li><p><strong>Potencia</strong>, <span class="math inline">\(1-\beta\)</span>: probabilidad de rechazar <span class="math inline">\(H_0\)</span> si <span class="math inline">\(H_1\)</span> es verdadera (probabilidad de verdadero positivo).</p></li>
<li><p><strong>Estadístico de contraste</strong>: el valor que calculamos sobre una muestra aleatoria simple para efectuar el contraste</p></li>
<li><p><strong>Región crítica o de rechazo</strong>: el rango de valores del estadístico de contraste para los que rechazamos <span class="math inline">\(H_{0}\)</span> con un nivel de significación <span class="math inline">\(\alpha\)</span> dado.</p></li>
<li><p><strong>Región de aceptación</strong>: el complementario de la región de rechazo, es decir, el rango de valores del estadístico de contraste para los que aceptamos <span class="math inline">\(H_{0}\)</span> con un nivel de significación <span class="math inline">\(\alpha\)</span> dado.</p></li>
<li><p><strong>p-valor</strong>: la probabilidad de que, si <span class="math inline">\(H_0\)</span> es verdadera, el estadístico de contraste tome sobre una muestra aleatoria simple del mismo tamaño que la nuestra un valor tan o más extremo (en el sentido de <span class="math inline">\(H_1\)</span>) que el obtenido sobre nuestra muestra.</p></li>
</ul>
<blockquote>
<p>Rechazamos <span class="math inline">\(H_{0}\)</span> con un nivel de significación <span class="math inline">\(\alpha\)</span> si el p-valor es menor que <span class="math inline">\(\alpha\)</span>.</p>
</blockquote>
<div class="example">
<p><span id="exm:unnamed-chunk-598" class="example"><strong>Ejemplo 14.20  </strong></span>Si realizamos un test t para efectuar un contraste
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\
H_{1}:\mu &gt; \mu_0
\end{array}
\right.
\]</span>
rechazamos <span class="math inline">\(H_0\)</span> con nivel de significación <span class="math inline">\(\alpha\)</span> (o con nivel de confianza <span class="math inline">\(1-\alpha\)</span>) cuando
<span class="math display">\[
T=\dfrac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}&gt;t_{n-1,1-\alpha}
\]</span></p>
</div>
<p>Por lo tanto:</p>
<ul>
<li><p><strong>Estadístico de contraste</strong>: este <span class="math inline">\(T\)</span></p></li>
<li><p><strong>Región crítica</strong> para el nivel de significación <span class="math inline">\(\alpha\)</span>: el intervalo <span class="math inline">\((t_{n-1,1-\alpha},\infty)\)</span></p></li>
<li><p><strong>Región de aceptación</strong> para el nivel de significación <span class="math inline">\(\alpha\)</span>: el intervalo <span class="math inline">\((-\infty,t_{n-1,1-\alpha}]\)</span></p></li>
<li><p><strong>p-valor</strong>: <span class="math inline">\(P(T\geqslant T_0)\)</span>, donde <span class="math inline">\(T_0\)</span> denota el valor de <span class="math inline">\(T\)</span> en nuestra muestra</p></li>
</ul>
<p>Si en cambio el contraste que queremos efectuar es
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\
H_{1}:\mu &lt; \mu_0
\end{array}
\right.
\]</span>
rechazamos <span class="math inline">\(H_0\)</span> con nivel de significación <span class="math inline">\(\alpha\)</span> (o con nivel de confianza <span class="math inline">\(1-\alpha\)</span>) cuando
<span class="math display">\[
T=\dfrac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}&lt;t_{n-1,\alpha}
\]</span></p>
<p>Por lo tanto:</p>
<ul>
<li><p><strong>Estadístico de contraste</strong>: el mismo <span class="math inline">\(T\)</span> que antes</p></li>
<li><p><strong>Región crítica</strong> para el nivel de significación <span class="math inline">\(\alpha\)</span>: el intervalo <span class="math inline">\((-\infty,t_{n-1,\alpha})\)</span></p></li>
<li><p><strong>Región de aceptación</strong> para el nivel de significación <span class="math inline">\(\alpha\)</span>: el intervalo <span class="math inline">\([t_{n-1,\alpha},\infty)\)</span></p></li>
<li><p><strong>p-valor</strong>: <span class="math inline">\(P(T\leqslant T_0)\)</span></p></li>
</ul>
<p>Finalmente, si el contraste que queremos realizar es
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\
H_{1}:\mu
\neq \mu_0
\end{array}
\right.
\]</span>
rechazamos <span class="math inline">\(H_0\)</span> con nivel de significación <span class="math inline">\(\alpha\)</span> (o con nivel de confianza <span class="math inline">\(1-\alpha\)</span>) cuando
<span class="math display">\[
|T|=\left|\dfrac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}\right|&gt;t_{n-1,1-\alpha/2}
\]</span>
Por lo tanto:</p>
<ul>
<li><p><strong>Estadístico de contraste</strong>: el mismo <span class="math inline">\(T\)</span> que antes</p></li>
<li><p><strong>Región crítica</strong> para el nivel de significación <span class="math inline">\(\alpha\)</span>: la unión de intervalos <span class="math inline">\((-\infty,-t_{n-1,1-\alpha/2})\cup (t_{n-1,1-\alpha/2},\infty)\)</span></p></li>
<li><p><strong>Región de aceptación</strong> para el nivel de significación <span class="math inline">\(\alpha\)</span>: el intervalo <span class="math inline">\([-t_{n-1,1-\alpha/2},t_{n-1,1-\alpha/2}]\)</span></p></li>
<li><p><strong>p-valor</strong>: <span class="math inline">\(2P(T\geqslant |T_0|)\)</span></p></li>
</ul>
<p>El <strong>intervalo de confianza de nivel de confianza <span class="math inline">\(1-\alpha\)</span></strong> de un contraste es un intervalo que tiene una probabilidad <span class="math inline">\(1-\alpha\)</span> de contener el parámetro poblacional que contrastamos, en el sentido de los intervalos de confianza del tema anterior: se calcula con una fórmula que en un <span class="math inline">\((1-\alpha)\cdot 100\%\)</span> de las veces que se aplica a una muestra aleatoria simple, produce un intervalo que contiene el parámetro poblacional.</p>
<blockquote>
<p>El intervalo de confianza de un contraste se obtiene imponiendo que el estadístico de contraste pertenezca a la región de aceptación para el nivel de significación <span class="math inline">\(\alpha\)</span> y despejando el parámetro poblacional.</p>
</blockquote>

<div class="rmdimportant">
Cuando <span class="math inline">\(H_1\)</span> es bilateral, el intervalo de confianza del contraste coincide con el intervalo de confianza dado en el tema anterior. Pero cuando <span class="math inline">\(H_1\)</span> es unilateral, el intervalo de confianza del contraste es infinito en el lado definido por la hipótesis alternativa.
</div>
<p>Por ejemplo, consideremos el caso de un test t para efectuar un contraste
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\
H_{1}:\mu &gt; \mu_0
\end{array}
\right.
\]</span>
Aceptamos <span class="math inline">\(H_0\)</span> con nivel de significación <span class="math inline">\(\alpha\)</span> cuando
<span class="math display">\[
\dfrac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}\leqslant t_{n-1,1-\alpha}
\]</span>
Despejando <span class="math inline">\(\mu_0\)</span>, obtenemos
<span class="math display">\[
\overline{X}- t_{n-1,1-\alpha}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}\leqslant \mu_0
\]</span>
Por lo tanto, el <strong>intervalo de confianza de nivel de confianza <span class="math inline">\(1-\alpha\)</span> para este contraste</strong> es
<span class="math display">\[
\Bigg[\overline{X}- t_{n-1,1-\alpha}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}},\infty\Bigg)
\]</span>
Si la <span class="math inline">\(\mu_0\)</span> que contrastamos pertenece a este intervalo, no podemos concluir que la <span class="math inline">\(\mu\)</span> poblacional sea mayor que <span class="math inline">\(\mu_0\)</span>, y por lo tanto no podemos rechazar que <span class="math inline">\(\mu=\mu_0\)</span>.</p>

<div class="rmdimportant">
Los valores de <span class="math inline">\(\mu_0\)</span> en este intervalo son tan grandes que con nuestra muestra no hemos obtenido evidencia de que la <span class="math inline">\(\mu\)</span> real sea mayor que ellos.
</div>
<p>En el ejemplo de los diabéticos de la Sección <a href="contrastes-de-hipótesis.html#sec:exttest">14.5</a>, da el intervalo
<span class="math display">\[
\Bigg[3.2- 1.73\cdot \dfrac{1.5}{\sqrt{20}},\infty\Bigg)=[2.62,\infty)
\]</span></p>
<p>Concluimos que, con un nivel de confianza del 95%, la concentración media de calcio en sangre en los jóvenes diabéticos es como mínimo 2.62, y que por lo tanto, con este nivel de confianza, no puede ser 2.5, aunque por poco.</p>
<p>Si efectuamos un contraste bilateral con un test t
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\
H_{1}:\mu
\neq \mu_0
\end{array}
\right.
\]</span>
aceptamos <span class="math inline">\(H_0\)</span> con nivel de significación <span class="math inline">\(\alpha\)</span> cuando
<span class="math display">\[
-t_{n-1,1-\alpha/2}\leqslant \dfrac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}\leqslant t_{n-1,1-\alpha/2}
\]</span>
Despejando <span class="math inline">\(\mu_0\)</span>, obtenemos:
<span class="math display">\[
\overline{X}- t_{n-1,1-\alpha/2}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}\leqslant \mu_0 \leqslant \overline{X}+ t_{n-1,1-\alpha/2}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}
\]</span>
Por lo tanto, el intervalo de confianza de nivel de confianza <span class="math inline">\(1-\alpha\)</span> para este contraste es
<span class="math display">\[
\Bigg[\overline{X}- t_{n-1,1-\alpha/2}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}},\overline{X}+ t_{n-1,1-\alpha/2}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}\Bigg]
\]</span>
¿Os suena? Llamando <span class="math inline">\(q\)</span> a <span class="math inline">\(1-\alpha\)</span>, de manera que
<span class="math display">\[
1-\frac{\alpha}{2}=1-\frac{1-q}{2}=\frac{1+q}{2},
\]</span>
da
<span class="math display">\[
\Bigg[\overline{X}- t_{n-1,(1+q)/2}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}},\overline{X}+ t_{n-1,(1+q)/2}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}\Bigg]
\]</span></p>
<p>Es el intervalo de confianza para <span class="math inline">\(\mu\)</span> basado en la t de Student que vimos en el tema anterior.</p>

<div class="rmdrecordau">
<p>En resumen, dado un contraste de hipótesis, podemos decidir si rechazamos <span class="math inline">\(H_0\)</span> en favor de <span class="math inline">\(H_1\)</span> con nivel de significación <span class="math inline">\(\alpha\)</span> usando:</p>
<ul>
<li><p><strong>La región crítica</strong>: Si el estadístico de contraste cae dentro de la región crítica para el nivel de significación <span class="math inline">\(\alpha\)</span>, rechazamos <span class="math inline">\(H_0\)</span>.</p></li>
<li><p><strong>El p-valor</strong>: Si el p-valor es menor que el nivel de significación <span class="math inline">\(\alpha\)</span>, rechazamos <span class="math inline">\(H_0\)</span>.</p></li>
<li><p><strong>El intervalo de confianza</strong>: Si el valor que contrastamos del parámetro poblacional no pertenece al intervalo de confianza de nivel de confianza <span class="math inline">\(1-\alpha\)</span>, rechazamos <span class="math inline">\(H_0\)</span>.</p></li>
</ul>
Los tres métodos son equivalentes.
</div>
<p>En la práctica no se usa la región crítica: su papel se reduce a ser un paso intermedio en la obtención de las otras dos reglas de rechazo. Por otro lado, el uso del p-valor es muy discutido porque da lugar a falsas interpretaciones (la probabilidad de que la hipótesis nula sea verdadera; un valor a comparar con el umbral absoluto 0.05 sin tener nada más en consideración; …), pero bien entendido (como una medida de la consistencia de lo observado con la hipótesis nula) es útil.</p>
<p>Lo más adecuado es dar el p-valor y el intervalo de confianza:</p>
<ul>
<li>El p-valor, porque aun es lo que todo el mundo espera y para que el lector lo pueda comparar con el nivel de significación que considere oportuno.</li>
<li>El intervalo de confianza, porque muestra el margen con el cual hemos aceptado o rechazado la hipótesis nula con nuestro nivel de significación.</li>
</ul>
<p>Si no establecemos un nivel de significación <span class="math inline">\(\alpha\)</span>, lo habitual es:</p>
<ul>
<li><p>Aceptar <span class="math inline">\(H_0\)</span> si el p-valor es mayor que 0.1: se dice que el p-valor <strong>no es estadísticamente significativo</strong></p></li>
<li><p>Rechazar <span class="math inline">\(H_0\)</span> si el p-valor es menor que 0.05: se dice que el p-valor <strong>es estadísticamente significativo</strong></p></li>
<li><p>Si el p-valor está entre 0.05 y 0.1 y no se ha fijado nivel de significación, lo mejor que podéis hacer es no concluir nada y decir que es necesario repetir el estudio con una muestra mayor.</p></li>
</ul>
<p>Cuando el p-valor es menor que 0.05, se suelen distinguir tres franjas:</p>
<ul>
<li><strong>Significativo</strong> si está entre 0.01 y 0.05</li>
<li><strong>Fuertemente significativo</strong> si está entre 0.001 y 0.01</li>
<li><strong>Muy significativo</strong> si es menor que 0.001</li>
</ul>
<p>Normalmente estas franjas se indican con un código de asteriscos:</p>
<ul>
<li><p>Un asterisco, *, para los p-valores entre 0.01 y 0.05</p></li>
<li><p>Dos asteriscos, **, para los p-valores entre 0.001 y 0.01</p></li>
<li><p>Tres asteriscos, ***, para los p-valores por debajo de 0.001</p></li>
</ul>
<p>Aunque hay otras propuestas:</p>
<p><img src="INREMDN_files/figure-html/emojis.png" width="80%" style="display: block; margin: auto;" /></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-603"></span>
<img src="https://imgs.xkcd.com/comics/p_values.png" alt="&quot;P-values&quot; (https://xkcd.com/1478/ (CC-BI-NC 2.5))" width="40%" />
<p class="caption">
Figura 14.3: “P-values” (<a href="https://xkcd.com/1478/" class="uri">https://xkcd.com/1478/</a> (CC-BI-NC 2.5))
</p>
</div>
<p>Dado que rechazamos <span class="math inline">\(H_0\)</span> si, y solo si, el p-valor es menor que <span class="math inline">\(\alpha\)</span>, el p-valor de un contraste es el nivel de significación más pequeño para el cual rechazaríamos la hipótesis nula. Es decir:</p>

<div class="rmdimportant">
El p-valor obtenido en un contraste es la probabilidad mínima de equivocarnos que asumimos al rechazar la hipótesis nula si esta es verdadera.
</div>
<p>Por lo tanto, por favor, acostumbraos a dar el p-valor, y no la franja de significación donde cae.</p>
</div>
<div id="ajuste-de-p-valores" class="section level2 hasAnchor" number="14.8">
<h2><span class="header-section-number">14.8</span> Ajuste de p-valores<a href="contrastes-de-hipótesis.html#ajuste-de-p-valores" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Si efectuamos <span class="math inline">\(M\)</span> contrastes independientes usando una regla de decisión que garantice un nivel de significación <span class="math inline">\(\alpha\)</span> dado, y en todos ellos la <span class="math inline">\(H_0\)</span> es verdadera, el número de contrastes donde nos equivocaremos y rechazaremos <span class="math inline">\(H_0\)</span> tiene distribución binomial <span class="math inline">\(B(M,\alpha)\)</span>. En particular, esperamos cometer <span class="math inline">\(\alpha M\)</span> errores de tipo I, y la probabilidad de cometer alguno es <span class="math inline">\(1-(1-\alpha)^M\)</span>. Este valor es mayor que <span class="math inline">\(\alpha\)</span>. Por ejemplo, si realizamos 3 contrastes con nivel de significación <span class="math inline">\(\alpha =0.05\)</span> y en los tres la hipótesis nula es vertadera, la probabilidad de que cometamos algún Error de Tipo I es
<span class="math inline">\(1-(1-0.05)^{3} \approx 0.14\)</span>.</p>

<div class="rmdcaution">
Si efectuamos muchos contrastes, aumenta la probabilidad de “encontrar algo” aunque no haya nada que encontrar, y acabar diciendo que las gominolas verdes curan el acné.
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-606"></span>
<img src="http://imgs.xkcd.com/comics/significant.png" alt="&quot;Significant&quot; (https://xkcd.com/882/ (CC-BI-NC 2.5))" width="50%" />
<p class="caption">
Figura 14.4: “Significant” (<a href="https://xkcd.com/882/" class="uri">https://xkcd.com/882/</a> (CC-BI-NC 2.5))
</p>
</div>
<p>Si queremos mantener un nivel de significación global <span class="math inline">\(\alpha\)</span>, es decir, que la probabilidad de cometer <em>algún error de tipo I</em> sea <span class="math inline">\(\alpha\)</span>, hay que reducir el nivel de significación de cada uno de ellos, o equivalentemente aumentar (<strong>ajustar</strong>) el p-valor de cada contraste y comparar el valor ajustado con el <span class="math inline">\(\alpha\)</span> fijado.</p>
<p>Se han propuesto muchos métodos para ajustar los p-valores de grupos de contrastes. El más sencillo, y el más popular, es el <strong>de Bonferroni</strong>. Su idea es que, usando la aproximación <span class="math inline">\(1-(1-x)^M \approx M\cdot x\)</span>, para efectuar <span class="math inline">\(M\)</span> contrastes con un nivel de significación global <span class="math inline">\(\alpha\)</span>:</p>
<blockquote>
<p><em>tenemos que realizar cada contraste con nivel de significación <span class="math inline">\(\alpha/M\)</span></em> (y así el nivel de significación global será <span class="math inline">\(\approx\)</span> <span class="math inline">\(M\cdot \alpha/M=\alpha\)</span>)</p>
</blockquote>
<p>o equivalentemente:</p>
<blockquote>
<p><em>tenemos que multiplicar el p-valor de cada contraste por <span class="math inline">\(M\)</span></em> antes de compararlo con el nivel de significación <span class="math inline">\(\alpha\)</span>.</p>
</blockquote>
<p>Ambos métodos son equivalentes, porque
<span class="math display">\[
p&lt; \alpha/M\Longleftrightarrow M\cdot p&lt;\alpha
\]</span></p>
<p>Por ejemplo, si realizamos 3 contrastes, para obtener un nivel de significación global <span class="math inline">\(\alpha =0.05\)</span> el método de Bonferroni nos dice que tenemos que multiplicar cada p-valor por 3 y comparar los p-valores ajustados resultantes con 0.05.</p>

<div class="rmdnote">
Recordad que un p-valor es una probabilidad, por lo tanto no puede pasar de 1. Si al ajustar algún p-valor pasa de 1, se da 1 como resultado del ajuste.
</div>
</div>
<div id="resultados-estadísticamente-significativos-versus-resultados-clínicamente-significativos" class="section level2 hasAnchor" number="14.9">
<h2><span class="header-section-number">14.9</span> Resultados estadísticamente significativos <em>versus</em> resultados clínicamente significativos<a href="contrastes-de-hipótesis.html#resultados-estadísticamente-significativos-versus-resultados-clínicamente-significativos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Que en un contraste obtengamos un valor estadísticamente significativo quiere decir que es muy improbable que el valor del estadístico se obtenga por pura casualidad si la hipótesis nula es verdadera, y que es más verosímil que en la realidad sea la hipótesis alternativa la verdadera. Pero que un resultado sea estadísticamente significativo puede deberse a una diferencia muy pequeña en una muestra muy grande. Y esta diferencia tan pequeña puede que no sea clínicamente relevante.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:cyanide3"></span>
<img src="INREMDN_files/figure-html/cyanidesignest.png" alt="Estadísticamente significativo no significa clínicamente relevante." width="80%" />
<p class="caption">
Figura 14.5: Estadísticamente significativo no significa clínicamente relevante.
</p>
</div>
<p>Por ejemplo, imaginad que queremos estudiar si una vacuna para una determinada enfermedad es efectiva. Tomamos dos grupos de personas, vacunamos las de un grupo, dejamos sin vacunar las del otro, esperamos un tiempo prudencial, y contamos cuántos han enfermado en cada grupo. Fijemos el nivel de significación usual <span class="math inline">\(\alpha=0.05\)</span> y supongamos que obtenemos un p-valor por debajo de 0.05.
¡Gran júbilo! Hemos obtenido evidencia estadísticamente significativa de que nuestra vacuna funciona. Una diferencia entre las proporciones de enfermos en el grupo de control y el grupo de vacunados como la que hemos encontrado sería muy improbable si la vacuna no fuera efectiva.</p>
<p>Pero a este p-valor pequeño podemos llegar de muchas maneras. Por ejemplo:</p>
<ul>
<li><p>Puede que hayamos tomado 100 sujetos en cada grupo y que hayan enfermado 20 controles, un 20%, y 10 vacunados, un 10% (el p-valor del test aproximado de dos proporciones que explicaremos en el próximo tema es, con estos valores, 0.024). En este caso podríamos considerar el resultado no solo estadísticamente significativo, sino clínicamente relevante: en nuestro experimento, la vacuna ha reducido a la mitad el riesgo de contraer la enfermedad, 10 puntos porcentuales en términos absolutos.</p></li>
<li><p>Podríamos haber tomado 100000 sujetos en cada grupo y que hayan enfermado 20000 controles, un 20%, y 19600 vacunados, un 19.6% (el p-valor del test aproximado que hemos mencionado antes es, con estos valores, 0.0126). En este caso el resultado sigue siendo estadísticamente significativo, incluso más que antes, porque el p-valor es más pequeño, pero la relevancia clínica ya no está tan clara: estimamos que la vacuna reduce en un 2% el riesgo de contraer la enfermedad, en términos absolutos 4 décimas de punto porcentual.</p></li>
</ul>
<p>En el segundo caso, con una muestra tan grande, la potencia era muy grande y como consecuencia cualquier pequeña diferencia se convertía en estadísticamente significativa, aunque fuera eso, pequeña.</p>
<p>En este curso nos preocupamos sobre todo del significado estadístico del resultado de un estudio, que medimos con el p-valor. Más adelante en vuestra vida profesional, el significado clínico lo tendréis que decidir vosotros a partir de vuestra experiencia.</p>
<p>Y tened en cuenta que un resultado publicado puede ser estadísticamente significativo y no significar nada. Por ejemplo, el paquete <strong>statcheck</strong> de R permite revisar de manera automática todos los cálculos de un artículo escrito en un formato concreto usado en revistas de psicología y comprobar los p-valores. <a href="https://link.springer.com/article/10.3758/s13428-015-0664-2">Los autores del paquete analizaron 30,000 artículos</a> y concluyeron que:</p>
<blockquote>
<p>“Hemos encontrado que la mitad de los artículos contienen al menos un p-valor erróneo. Y uno de cada ocho artículos contiene un p-valor erróneo que además afecta la conclusión estadística.”</p>
</blockquote>
<p>Por lo tanto,</p>
<ul>
<li>Cualquier artículo puede dar un p-valor pequeño que esté equivocado</li>
</ul>
<p>No os fiéis de los resultados. Si las conclusiones os interesan, revisad los cálculos.</p>
<p>Además, tened presente que:</p>
<ul>
<li><p>Cualquier estudio mal diseñado o mal realizado puede dar un p-valor pequeño… que no signifique absolutamente nada.</p>
<p>Si las conclusiones de un artículo os interesan, revisad si el estudio ha sido bien diseñado, ejecutado y analizado.</p></li>
<li><p>Cualquier estudio perfectamente diseñado y realizado puede dar por puro azar un p-valor pequeño… que implique un falso positivo.</p>
<p>Contra esto último no podemos hacer nada, salvo ser escépticos.</p></li>
</ul>
<div class="example">
<p><span id="exm:unnamed-chunk-608" class="example"><strong>Ejemplo 14.21  </strong></span>En <a href="https://www.sciencedirect.com/science/article/abs/pii/S004113451001081X">un artículo publicado en 2010</a> se obtuvo evidencia de que una persona que fuera Aries, Tauro, Géminis, Leo, Escorpio o Capricornio tenía una mayor probabilidad de supervivencia a 5 años vista tras un alotransplante de células madre para tratar una leucemia mieloide crónica que una persona de fuera de los otros signos del zodíaco (58% de tasa de supervivencia frente a un 48%, p-valor 0.007). ¿Nos lo tenemos a creer? Spoiler: El subtítulo del artículo es <em>An artificial association</em>.</p>
</div>
</div>
<div id="test-12" class="section level2 hasAnchor" number="14.10">
<h2><span class="header-section-number">14.10</span> Test<a href="contrastes-de-hipótesis.html#test-12" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>(1)</strong> Cuando escribimos formalmente un contraste de hipótesis, ¿qué es <span class="math inline">\(H_1\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Es la primera hipótesis que hacemos y que después ya modificaremos en función de los datos obtenidos</li>
<li>Es la hipótesis nula</li>
<li>Es la hipótesis alternativa</li>
<li>Es la variable <em>h</em>aleatoria poblacional de interés</li>
<li>Ninguna de las otras respuestas es la correcta</li>
</ol>
<p><strong>(2)</strong> Un test de COVID-19 no es nada más que un contraste de hipótesis: tomas una muestra del individuo y decides si tiene COVID-19 o no. ¿Qué contraste es?</p>
<ol style="list-style-type: decimal">
<li>H<sub>0</sub>: El individuo tiene COVID-19; H<sub>1</sub>: El individuo no tiene COVID-19</li>
<li>H<sub>0</sub>: El individuo no tiene COVID-19; H<sub>1</sub>: El individuo tiene COVID-19</li>
<li>H<sub>0</sub>: El individuo no tiene COVID-19; H<sub>1</sub>: El individuo podría tener COVID-19</li>
<li>H<sub>0</sub>: No sé si el individuo tiene COVID-19; H<sub>1</sub>: El individuo tiene COVID-19</li>
</ol>
<p><strong>(3)</strong> Un científico publica un artículo donde afirma que las personas que toman un determinado medicamento tienen una mayor probabilidad de formación de cálculos renales. Más tarde se descubre que en realidad esta asociación no existe. ¿Qué tipo de error cometió el científico y por qué?</p>
<ol style="list-style-type: decimal">
<li>Tipo I, porque afirmó que la hipótesis nula es cierta cuando en realidad es falsa.</li>
<li>Tipo I, porque afirmó que la hipótesis nula es falsa cuando en realidad es cierta.</li>
<li>Tipo II, porque afirmó que la hipótesis nula es cierta cuando en realidad es falsa.</li>
<li>Tipo II, porque afirmó que la hipótesis nula es falsa cuando en realidad es cierta.</li>
</ol>
<p><strong>(4)</strong> En un examen considerado como un contraste (marca todas las respuestas
correctas):</p>
<ol style="list-style-type: decimal">
<li>Que el estudiante apruebe sin saber la materia es un error de tipo I</li>
<li>Que el estudiante apruebe sin saber la materia es un error de tipo II</li>
<li>Que el estudiante apruebe sin saber la materia es simultáneamente un error de tipo I y de tipo II</li>
<li>El nivel de significación es la probabilidad de que el estudiante apruebe sin saber la materia</li>
<li>El nivel de significación es la probabilidad de que el estudiante suspenda si no sabe la materia</li>
</ol>
<p><strong>(5)</strong> ¿Qué significa que en un contraste de hipótesis tomemos un nivel de significación del 1%? Marca la respuesta correcta:</p>
<ol style="list-style-type: decimal">
<li>Que un 1% de las veces que la hipótesis nula sea falsa la rechazaremos en favor de la alternativa.</li>
<li>Que un 1% de las veces que la hipótesis nula sea falsa la aceptaremos.</li>
<li>Que un 1% de las veces que la hipótesis nula sea verdadera la rechazaremos en favor de la alternativa.</li>
<li>Que un 1% de las veces que la hipótesis nula sea verdadera la aceptaremos.</li>
<li>Que un 1% de las veces rechazaremos la hipótesis nula.</li>
<li>Que un 1% de las veces aceptaremos la hipótesis nula.</li>
<li>Todas las otras respuestas son incorrectas.</li>
</ol>
<p><strong>(6)</strong> Al analizar los resultados de un ensayo clínico, se concluye que las tasas de curación de los dos tratamientos estudiados son diferentes, con un p-valor de 0.034. Esto significa (marca todas las respuestas correctas):</p>
<ol style="list-style-type: decimal">
<li>Que hay un 3.4% de probabilidad de que, si se repite el estudio, no se encuentren diferencias significativas.</li>
<li>Que hay un 3.4% de probabilidad de que la tasa de curación de los tratamientos estudiados sean iguales.</li>
<li>Que hay un 3.4% de diferencia, o más, en las tasas de curación de los tratamientos estudiados.</li>
<li>Que ha habido un 3.4% de diferencia, o más, en las tasas de curación de los tratamientos en nuestras muestras.</li>
<li>Que hay un 3.4% de probabilidad de que la diferencia obtenida entre las tasas de curación, o una aún mayor, se obtenga por pura casualidad.</li>
<li>Todas las otras respuestas son incorrectas.</li>
</ol>
<p><strong>(7)</strong> En un pequeño ensayo aleatorio simple ciego de un nuevo tratamiento en pacientes con infarto de miocardio agudo, la mortalidad en el grupo tratado fue la mitad que en el grupo control, pero
la diferencia no resultó estadísticamente significativa. Podemos concluir que (marca todas las respuestas correctas):</p>
<ol style="list-style-type: decimal">
<li>Como la diferencia no es estadísticamente significativa, el tratamiento es inútil.</li>
<li>Podría ser que el contraste tuviera poca potencia, y por eso la diferencia detectada no ha sido estadísticamente significativa.</li>
<li>La reducción observada de la mortalidad es tan grande que deberíamos introducir el tratamiento inmediatamente, aunque dicha reducción no sea estadísticamente significativa.</li>
<li>Esto se debe a que el ensayo fue simple ciego, y no doble ciego.</li>
<li>Es conveniente llevar a cabo un nuevo ensayo sobre una muestra de pacientes de mayor tamaño.</li>
<li>Todas las otras respuestas son incorrectas.</li>
</ol>
<p><strong>(8)</strong> En un estudio donde se contrastó si los individuos con hipertensión arterial tienen un mayor riesgo de sufrir un infarto de miocardio que los individuos normotensos, se obtuvo un p-valor de 0.02. ¿Qué quiere decir esto?
(Marca una sola respuesta.)</p>
<ol style="list-style-type: decimal">
<li>La probabilidad de que los hipertensos tengan más riesgo de sufrir un infarto de miocardio que los normotensos es 0.02</li>
<li>La probabilidad de que los hipertensos tengan más riesgo de sufrir un infarto de miocardio que los normotensos es 0.98</li>
<li>Un hipertenso tiene una probabilidad de sufrir un infarto de miocardio un 2% mayor que un normotenso.</li>
<li>En las muestras que hemos usado en el estudio, la proporción de hipertensos que han sufrido un infarto de miocardio es un 2% mayor que la de normotensos que han sufrido un infarto de miocardio</li>
<li>Ninguna de las otras respuestas es correcta.</li>
</ol>
<p><strong>(9)</strong> En un estudio sobre lactancia materna e inteligencia, a 300 niños
que fueron muy pequeños al nacer se les dio la leche materna de su madre o leche infantil, a elección de la madre. A la edad de 8 años, se midió el CI (cociente intelectual) de estos niños. El CI medio en el grupo de leche infantil fue 92.8, en comparación con un CI medio de 103.0 en el grupo de leche materna. La diferencia fue estadísticamente significativa, con un p-valor inferior a 0.001. Marca todas las afirmaciones correctas:</p>
<ol style="list-style-type: decimal">
<li>Hay evidencia estadísticamente significativa de que la alimentación mediante leche infantil de los bebés muy pequeños reduce su CI a los 8 años.</li>
<li>Hay evidencia estadísticamente significativa de que elegir alimentar un bebé muy pequeño con leche materna aumenta el CI del niño a los 8 años.</li>
<li>Hay evidencia estadísticamente significativa de que el tipo de leche no tiene ningún efecto en el CI subsecuente.</li>
<li>La probabilidad de que el tipo de leche no afecte al CI subsiguiente es inferior al 0.1%.</li>
<li>Si la elección del tipo de leche influyera en el CI, la probabilidad de que la diferencia observada del CI medio en el grupo de leche materna menos el del grupo de leche infantil fuera la de este estudio, o menor, es menor que 0.001.</li>
<li>Todas las otras respuestas son incorrectas.</li>
</ol>
<p><strong>(10)</strong> En un contraste de hipótesis, si la hipótesis alternativa es verdadera pero se acepta la hipótesis nula (marca todas las conclusiones correctas, hay al menos una):</p>
<ol style="list-style-type: decimal">
<li>Se comete un error de tipo I.</li>
<li>Se comete un error de tipo II.</li>
<li>La potencia disminuye.</li>
<li>El p-valor es mayor que el nivel de significación.</li>
<li>El p-valor es menor que el nivel de significación.</li>
</ol>
<p><strong>(11)</strong> Siempre que en un contraste de hipótesis NO se rechaza la hipótesis nula, ¿cuál o cuáles de las siguientes afirmaciones son correctas?</p>
<ol style="list-style-type: decimal">
<li>Se ha demostrado que la hipótesis nula es verdadera.</li>
<li>Se ha demostrado que la hipótesis alternativa es falsa.</li>
<li>Se ha encontrado evidencia de que la hipótesis nula es verdadera</li>
<li>Se ha encontrado evidencia de que la hipótesis alternativa es falsa</li>
<li>Ninguna de las otras afirmaciones es verdadera.</li>
</ol>
<p><strong>(12)</strong> Si en un contraste de hipótesis tomamos un nivel de significación del 10% y una potencia del 60% y obtenemos un p-valor de 0.28, ¿cuál de las afirmaciones siguientes es verdadera?</p>
<ol style="list-style-type: decimal">
<li>Aceptamos la hipótesis nula porque 0.28&gt;0.1.</li>
<li>Aceptamos la hipótesis nula porque 0.28&lt;0.6.</li>
<li>Rechazamos la hipótesis nula porque 0.28&gt;0.1.</li>
<li>Rechazamos la hipótesis nula porque 0.28&lt;0.6.</li>
<li>Con los datos dados, no tenemos criterio para aceptar o rechazar la hipótesis nula.</li>
</ol>
<p><strong>(13)</strong> En un estudio se trató con un suplemento dietético más dieta a 39 insuficientes renales y solamente con dieta a 40, de manera que los pacientes conocían qué tratamiento recibieron. Se compararon 20 variables entre ambos grupos y en una comparación se encontró una diferencia a favor del suplemento estadísticamente significativa con un nivel de significación del 5% (p-valor 0.000021). ¿Cómo interpretas estos resultados? Marca una sola respuesta.</p>
<ol style="list-style-type: decimal">
<li>El estudio no permite concluir nada, ya que si realizamos 20 contrastes con un nivel de significación del 5%, esperamos que alguno dé un resultado estadísticamente significativo aunque no haya diferencia entre los tratamientos</li>
<li>El p-valor tan pequeño descarta la posibilidad de un falso positivo en el caso en que se ha encontrado una diferencia estadísticamente significativa</li>
<li>El hecho de haber encontrado una diferencia estadísticamente significativa en una comparación puede deberse a un error de tipo II</li>
<li>Con unas muestras de pacientes tan pequeñas, la potencia de los contrastes seguramente es muy baja, lo que explica que hayamos obtenido algún resultado estadísticamente significativo</li>
<li>Como en un 5% (el nivel de significación) de los contrastes se obtuvo un resultado favorable a favor del suplemento dietético, concluimos que su introducción es eficaz</li>
</ol>
<p><strong>(14)</strong> En un contraste que hemos llevado a cabo con nivel de significación 0.05 hemos obtenido un p-valor de 1.8. ¿Cuál ha de ser nuestra decisión?</p>
<ol style="list-style-type: decimal">
<li>Aceptar la hipótesis nula, porque el p-valor es mayor que el nivel de significación.</li>
<li>Rechazar la hipótesis nula, porque el p-valor es tan raro que hace inverosímil que la hipótesis nula sea verdadera.</li>
<li>Revisar los cálculos, a ver dónde nos hemos equivocado.</li>
<li>Ninguna de las otras respuestas es correcta.</li>
</ol>
<p><strong>(15)</strong> En un contraste con <span class="math inline">\(\alpha=0.05\)</span> rechazamos la hipótesis nula. ¿Qué pasaría si, con la misma muestra, tomáramos <span class="math inline">\(\alpha=0.1\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Seguro que también rechazaríamos la hipótesis nula</li>
<li>Seguro que no rechazaríamos la hipótesis nula</li>
<li>Puede pasar cualquier cosa</li>
</ol>
<p><strong>(16)</strong> En un contraste con <span class="math inline">\(\alpha=0.05\)</span> no rechazamos la hipótesis nula. ¿Qué pasaría si, con la misma muestra, tomáramos <span class="math inline">\(\alpha=0.1\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Seguro que tampoco rechazaríamos la hipótesis nula</li>
<li>Seguro que sí que rechazaríamos la hipótesis nula</li>
<li>Puede pasar cualquier cosa</li>
</ol>
<p><strong>(17)</strong> En un contraste de una media usando un test t, el aumento del tamaño de la muestra (marca todas las respuestas correctas):</p>
<ol style="list-style-type: decimal">
<li>Mejora la aproximación del estadístico de contraste a una distribución normal.</li>
<li>Esperamos que disminuya la probabilidad de error de tipo I.</li>
<li>Esperamos que disminuya la probabilidad de error de tipo II.</li>
<li>Esperamos que disminuya la potencia del contraste.</li>
<li>Hace menos probable que la hipótesis nula sea verdadera.</li>
<li>Todas las otras respuestas son incorrectas.</li>
</ol>
<p><strong>(18)</strong> En un contraste de hipótesis en el que la hipótesis nula es verdadera (marca una sola respuesta):</p>
<ol style="list-style-type: decimal">
<li>Solo podemos cometer un error de tipo I.</li>
<li>Solo podemos cometer un error de tipo II.</li>
<li>Podemos cometer tanto un error de tipo I como un error de tipo II, pero no los dos.</li>
<li>Podemos cometer tanto un error de tipo I como un error de tipo II, y podemos cometerlos los dos simultáneamente.</li>
<li>Como la hipótesis nula es verdadera, no podemos cometer ni un error de tipo I ni un error de tipo II.</li>
<li>Todas las otras respuestas son falsas.</li>
</ol>
<p><strong>(19)</strong> ¿Qué es la región de aceptación de un contraste sobre un parámetro poblacional?</p>
<ol style="list-style-type: decimal">
<li>El conjunto de los valores del parámetro poblacional para los que tenemos que aceptar la hipótesis nula</li>
<li>El conjunto de los valores del parámetro poblacional para los que tenemos que aceptar la hipótesis alternativa</li>
<li>El conjunto de los valores del estadístico de contraste para los que tenemos que aceptar la hipótesis nula</li>
<li>El conjunto de los valores del estadístico de contraste para los que tenemos que aceptar la hipótesis alternativa</li>
<li>El conjunto de las estimaciones aceptables del parámetro poblacional a partir de la muestra</li>
</ol>
<p><strong>(20)</strong> Si efectuamos un mismo contraste con el mismo nivel de significación dos veces con dos muestras diferentes del mismo tamaño (marca las continuaciones correctas):</p>
<ol style="list-style-type: decimal">
<li>La región de aceptación del contraste será las dos veces la misma</li>
<li>La región de aceptación del contraste puede dar diferente con cada muestra</li>
<li>El intervalo de confianza del contraste será las dos veces el mismo</li>
<li>El intervalo de confianza del contraste puede dar diferente con cada muestra</li>
</ol>
<p><strong>(21)</strong> En un contraste de hipótesis hemos rechazado la hipótesis nula en favor de la alternativa con nivel de significación del 10%. El contraste ha tenido una potencia del 60%. ¿Cuál o cuáles de las afirmaciones siguientes son correctas en esta situación?</p>
<ol style="list-style-type: decimal">
<li>La probabilidad que la hipótesis nula sea verdadera es 0.1</li>
<li>La probabilidad que la hipótesis nula sea verdadera es 0.4</li>
<li>La probabilidad que la hipótesis alternativa sea verdadera es 0.1</li>
<li>La probabilidad que la hipótesis alternativa sea verdadera es 0.4</li>
<li>Ninguna de las otras respuestas es correcta.</li>
</ol>
<p><strong>(22)</strong> Hemos efectuado el mismo contraste con dos muestras: con la primera hemos obtenido un p-valor de 0.1 y con la segunda un p-valor de 0.01. ¿Cuál o cuáles de las afirmaciones siguientes son correctas?</p>
<ol style="list-style-type: decimal">
<li>Es más probable que sea verdadera la hipótesis nula del contraste con la primera muestra que la hipótesis nula del contraste con la segunda muestra</li>
<li>Es más probable que sea verdadera la hipótesis nula del contraste con la segunda muestra que la hipótesis nula del contraste con la primera muestra</li>
<li>No hay manera de saber si la hipótesis nula del contraste con la primera muestra es más probable o menos probable que la hipótesis nula del contraste con la segunda muestra</li>
<li>Ninguna de las otras respuestas es correcta</li>
</ol>
<p><strong>(23)</strong> Hemos efectuado un test t de una media, con hipótesis alternativa <span class="math inline">\(\mu\neq 2\)</span>. ¿Es posible que hayamos obtenido (con la misma muestra) un intervalo de confianza del contraste del 95% [2.1,3.2] y un p-valor 0.13?</p>
<ol style="list-style-type: decimal">
<li>Sí</li>
<li>No</li>
</ol>
<p><strong>(24)</strong> Hemos efectuado un test t de una media, con hipótesis alternativa <span class="math inline">\(\mu\neq 2\)</span>. ¿Es posible que hayamos obtenido (con la misma muestra) un intervalo de confianza del contraste del 95% [1.8,3.2] y un p-valor 0.13?</p>
<ol style="list-style-type: decimal">
<li>Sí</li>
<li>No</li>
</ol>
<p><strong>(25)</strong> Hemos efectuado un test t de una media, con hipótesis alternativa <span class="math inline">\(\mu&lt;2\)</span>. ¿Es posible que hayamos obtenido (con la misma muestra) un intervalo de confianza del contraste del 95% [1.8,3.2] y un p-valor 0.13?</p>
<ol style="list-style-type: decimal">
<li>Sí</li>
<li>No</li>
</ol>
<p><strong>(26)</strong> Hemos efectuado dos veces, con dos muestras diferentes, un mismo test t de una media, con hipótesis alternativa <span class="math inline">\(\mu\neq 2\)</span>. ¿Es posible que con una muestra hayamos obtenido un intervalo de confianza del contraste del 95% [2.1,3.2] y con la otra muestra un p-valor 0.13?</p>
<ol style="list-style-type: decimal">
<li>Sí</li>
<li>No</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intervalos-de-confianza.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="qué-test-usar.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
